In [1]:
from huggingface_hub import notebook_login

notebook_login()

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [ ]:
import os
import datasets
from langchain.docstore.document import Document
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_community.vectorstores.utils import DistanceStrategy
from transformers import AutoTokenizer
from tqdm import tqdm

In [3]:
def sanitize_filename(dataset_name):
    """Convert dataset name to a valid filename by replacing '/' with '_'"""
    return dataset_name.replace("/", "_")


def load_or_create_vectordb(dataset_name):
    """Load existing vectordb or create new one if it doesn't exist"""

    # Create sanitized filename
    safe_filename = sanitize_filename(dataset_name)
    vectordb_path = f"vectordb\\{safe_filename}"

    # Check if vectordb already exists
    if os.path.exists(vectordb_path):
        print(f"Found existing vector database at {vectordb_path}")
        print("Loading existing vector database...")

        # Load the embedding model (needed for loading)
        embedding_model = HuggingFaceEmbeddings(
            model_name="thenlper/gte-small")

        # Load the existing vectordb
        vectordb = FAISS.load_local(vectordb_path,
                                    embedding_model,
                                    allow_dangerous_deserialization=True)
        print("Vector database loaded successfully!")
        return vectordb

    else:
        print(f"No existing vector database found at {vectordb_path}")
        print("Creating new vector database...")

        # Load and process the dataset
        knowledge_base = datasets.load_dataset(dataset_name, split="train")
        source_docs = [
            Document(page_content=doc["text"],
                     metadata={"source": doc["source"].split("/")[1]})
            for doc in knowledge_base
        ]

        # Initialize text splitter
        text_splitter = RecursiveCharacterTextSplitter.from_huggingface_tokenizer(
            AutoTokenizer.from_pretrained("thenlper/gte-small"),
            chunk_size=200,
            chunk_overlap=20,
            add_start_index=True,
            strip_whitespace=True,
            separators=["\n\n", "\n", ".", " ", ""],
        )

        # Split docs and keep only unique ones
        print("Splitting documents...")
        docs_processed = []
        unique_texts = {}
        for doc in tqdm(source_docs):
            new_docs = text_splitter.split_documents([doc])
            for new_doc in new_docs:
                if new_doc.page_content not in unique_texts:
                    unique_texts[new_doc.page_content] = True
                    docs_processed.append(new_doc)

        print("Embedding documents...")
        embedding_model = HuggingFaceEmbeddings(
            model_name="thenlper/gte-small")
        vectordb = FAISS.from_documents(
            documents=docs_processed,
            embedding=embedding_model,
            distance_strategy=DistanceStrategy.COSINE,
        )

        # Save the vectordb
        print(f"Saving vector database to {vectordb_path}...")
        vectordb.save_local(vectordb_path)
        print("Vector database saved successfully!")

        return vectordb


# Usage
dataset_name = "m-ric/huggingface_doc"
vectordb = load_or_create_vectordb(dataset_name)

print(f"Vector database ready with {vectordb.index.ntotal} vectors!")

Found existing vector database at vectordb\m-ric_huggingface_doc
Loading existing vector database...
Vector database loaded successfully!
Vector database ready with 39785 vectors!

In [4]:
import os
import datasets
from langchain.docstore.document import Document
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_community.vectorstores.utils import DistanceStrategy
from transformers import AutoTokenizer
from tqdm import tqdm
from concurrent.futures import ThreadPoolExecutor
import threading
from typing import List


def sanitize_filename(dataset_name: str) -> str:
    """Convert dataset name to a valid filename by replacing '/' with '_'"""
    return dataset_name.replace("/", "_")


class DocumentProcessor:
    """Thread-safe document processor to avoid pickling issues"""

    def __init__(self):
        self.text_splitter = None
        self._lock = threading.Lock()

    def _get_text_splitter(self):
        """Initialize text splitter in thread-local manner"""
        if self.text_splitter is None:
            with self._lock:
                if self.text_splitter is None:
                    self.text_splitter = RecursiveCharacterTextSplitter.from_huggingface_tokenizer(
                        AutoTokenizer.from_pretrained("thenlper/gte-small"),
                        chunk_size=200,
                        chunk_overlap=20,
                        add_start_index=True,
                        strip_whitespace=True,
                        separators=["\n\n", "\n", ".", " ", ""],
                    )
        return self.text_splitter

    def split_documents_chunk(self,
                              docs_chunk: List[Document]) -> List[Document]:
        """Split a chunk of documents using the text splitter"""
        text_splitter = self._get_text_splitter()
        processed_docs = []
        for doc in docs_chunk:
            new_docs = text_splitter.split_documents([doc])
            processed_docs.extend(new_docs)
        return processed_docs


def parallel_document_splitting(source_docs: List[Document],
                                max_workers: int = None,
                                chunk_size: int = 100) -> List[Document]:
    """Split documents in parallel using ThreadPoolExecutor"""
    if max_workers is None:
        max_workers = min(8, len(source_docs) // chunk_size + 1)

    print(f"Splitting documents in parallel using {max_workers} threads...")

    # Split source_docs into chunks for parallel processing
    doc_chunks = [
        source_docs[i:i + chunk_size]
        for i in range(0, len(source_docs), chunk_size)
    ]

    # Create a shared processor instance
    processor = DocumentProcessor()

    # Use ThreadPoolExecutor instead of ProcessPoolExecutor
    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        # Process chunks in parallel with progress bar
        results = list(
            tqdm(executor.map(processor.split_documents_chunk, doc_chunks),
                 total=len(doc_chunks),
                 desc="Processing document chunks"))

    # Flatten results
    all_processed_docs = []
    for chunk_result in results:
        all_processed_docs.extend(chunk_result)

    return all_processed_docs


def remove_duplicates(docs: List[Document]) -> List[Document]:
    """Remove duplicate documents based on page_content"""
    print("Removing duplicate documents...")
    unique_texts = set()
    unique_docs = []

    for doc in tqdm(docs, desc="Checking for duplicates"):
        if doc.page_content not in unique_texts:
            unique_texts.add(doc.page_content)
            unique_docs.append(doc)

    print(f"Removed {len(docs) - len(unique_docs)} duplicate documents")
    return unique_docs


def batch_embed_documents(docs: List[Document],
                          embedding_model,
                          batch_size: int = 100) -> FAISS:
    """Create FAISS vectorstore with batch processing for embeddings"""
    print(f"Embedding documents in batches of {batch_size}...")

    if not docs:
        raise ValueError("No documents to embed")

    # Create initial vectorstore with first batch
    first_batch = docs[:batch_size]
    print(f"Creating initial vectorstore with {len(first_batch)} documents...")

    vectordb = FAISS.from_documents(
        documents=first_batch,
        embedding=embedding_model,
        distance_strategy=DistanceStrategy.COSINE,
    )

    # Process remaining documents in batches
    remaining_docs = docs[batch_size:]
    if remaining_docs:
        total_batches = (len(remaining_docs) + batch_size - 1) // batch_size

        for i in tqdm(range(0, len(remaining_docs), batch_size),
                      desc="Adding document batches",
                      total=total_batches):
            batch = remaining_docs[i:i + batch_size]

            # Create temporary vectorstore for this batch
            batch_vectordb = FAISS.from_documents(
                documents=batch,
                embedding=embedding_model,
                distance_strategy=DistanceStrategy.COSINE,
            )

            # Merge with main vectorstore
            vectordb.merge_from(batch_vectordb)

    return vectordb


def sequential_document_splitting(
        source_docs: List[Document]) -> List[Document]:
    """Fallback sequential document splitting if parallel processing fails"""
    print("Using sequential document splitting...")

    text_splitter = RecursiveCharacterTextSplitter.from_huggingface_tokenizer(
        AutoTokenizer.from_pretrained("thenlper/gte-small"),
        chunk_size=200,
        chunk_overlap=20,
        add_start_index=True,
        strip_whitespace=True,
        separators=["\n\n", "\n", ".", " ", ""],
    )

    docs_processed = []
    for doc in tqdm(source_docs, desc="Splitting documents"):
        new_docs = text_splitter.split_documents([doc])
        docs_processed.extend(new_docs)

    return docs_processed


def load_or_create_vectordb(dataset_name: str,
                            batch_size: int = 100,
                            max_workers: int = None,
                            doc_chunk_size: int = 100,
                            force_rebuild: bool = False,
                            use_parallel: bool = True) -> FAISS:
    """Load existing vectordb or create new one with optimized processing"""

    # Create sanitized filename
    safe_filename = sanitize_filename(dataset_name)
    vectordb_path = f"vectordb\\{safe_filename}"

    # Check if vectordb already exists and not forcing rebuild
    if os.path.exists(vectordb_path) and not force_rebuild:
        print(f"Found existing vector database at {vectordb_path}")
        print("Loading existing vector database...")

        try:
            # Load the embedding model (needed for loading)
            embedding_model = HuggingFaceEmbeddings(
                model_name="thenlper/gte-small")

            # Load the existing vectordb
            vectordb = FAISS.load_local(vectordb_path,
                                        embedding_model,
                                        allow_dangerous_deserialization=True)
            print("Vector database loaded successfully!")
            return vectordb

        except Exception as e:
            print(f"Error loading existing vectordb: {e}")
            print("Creating new vector database...")

    else:
        if force_rebuild:
            print("Force rebuild requested. Creating new vector database...")
        else:
            print(f"No existing vector database found at {vectordb_path}")
            print("Creating new vector database...")

    # Load and process the dataset
    print("Loading dataset...")
    knowledge_base = datasets.load_dataset(dataset_name, split="train")
    source_docs = [
        Document(page_content=doc["text"],
                 metadata={"source": doc["source"].split("/")[1]})
        for doc in tqdm(knowledge_base, desc="Processing dataset")
    ]

    print(f"Loaded {len(source_docs)} documents from dataset")

    # Split documents (with fallback to sequential processing)
    try:
        if use_parallel and len(
                source_docs) > 50:  # Only use parallel for larger datasets
            docs_processed = parallel_document_splitting(
                source_docs, max_workers, doc_chunk_size)
        else:
            docs_processed = sequential_document_splitting(source_docs)

    except Exception as e:
        print(f"Parallel processing failed: {e}")
        print("Falling back to sequential processing...")
        docs_processed = sequential_document_splitting(source_docs)

    print(f"Split into {len(docs_processed)} document chunks")

    # Remove duplicates
    docs_processed = remove_duplicates(docs_processed)

    print(f"Final document count after deduplication: {len(docs_processed)}")

    # Create embedding model
    print("Loading embedding model...")
    embedding_model = HuggingFaceEmbeddings(model_name="thenlper/gte-small")

    # Create vectordb with batch processing
    vectordb = batch_embed_documents(docs_processed, embedding_model,
                                     batch_size)

    # Save the vectordb
    print(f"Saving vector database to {vectordb_path}...")
    try:
        vectordb.save_local(vectordb_path)
        print("Vector database saved successfully!")
    except Exception as e:
        print(f"Error saving vectordb: {e}")
        print("Continuing without saving...")

    return vectordb


# Usage example with configurable parameters
dataset_name = "m-ric/huggingface_doc"

# Configure processing parameters
config = {
    "batch_size": 50,  # Batch size for embedding generation
    "max_workers": 4,  # Number of parallel workers for document splitting
    "doc_chunk_size": 100,  # Size of document chunks for parallel processing
    "force_rebuild": False,  # Whether to force rebuild even if vectordb exists
    "use_parallel":
    True  # Whether to use parallel processing (fallback to sequential)
}

vectordb = load_or_create_vectordb(dataset_name, **config)
print(f"Vector database ready with {vectordb.index.ntotal} vectors!")

Found existing vector database at vectordb\m-ric_huggingface_doc
Loading existing vector database...
Vector database loaded successfully!
Vector database ready with 39785 vectors!

In [6]:
# Example of using the vectordb for similarity search
query = "How to use transformers?"
results = vectordb.similarity_search(query, k=5)
for i, result in enumerate(results):
    print(f"Result {i+1}: {result.page_content}")

Result 1: . An example of how to use the [transformers pipelines](https://huggingface.co/docs/transformers/main/en/main_classes/pipelines#pipelines) can be found below.
Result 2: In the following, we try to give you a general recipe that we found most useful when porting a model to 🤗 Transformers.

The following list is a summary of everything that has to be done to add a model and can be used by you as a To-Do
List:
Result 3: ## Why should I use transformers?

1. Easy-to-use state-of-the-art models:
    - High performance on natural language understanding & generation, computer vision, and audio tasks.
    - Low barrier to entry for educators and practitioners.
    - Few user-facing abstractions with just three classes to learn.
    - A unified API for using all our pretrained models.

1. Lower compute costs, smaller carbon footprint:
    - Researchers can share trained models instead of always retraining.
    - Practitioners can reduce compute time and production costs.
    - Dozens of architectures with over 60,000 pretrained models across all modalities.
Result 4: Introduction[[introduction]]

<CourseFloatingBanner
    chapter={2}
    classNames="absolute z-10 right-0 top-0"
/>

As you saw in [Chapter 1](/course/chapter1), Transformer models are usually very large. With millions to tens of *billions* of parameters, training and deploying these models is a complicated undertaking. Furthermore, with new models being released on a near-daily basis and each having its own implementation, trying them all out is no easy task.

The 🤗 Transformers library was created to solve this problem. Its goal is to provide a single API through which any Transformer model can be loaded, trained, and saved. The library's main features are:
Result 5: First, you should get a general overview of 🤗 Transformers. Transformers
is a very opinionated library, so there is a chance that
you don't agree with some of the library's philosophies or design
choices. From our experience, however, we found that the fundamental
design choices and philosophies of the library are crucial to
efficiently scale Transformers while keeping maintenance costs at a
reasonable level.

A good first starting point to better understand the library is to read
the [documentation of our philosophy](https://huggingface.co/transformers/philosophy.html).
As a result of our way of working, there are some choices that we try to apply to all models:

In [ ]:
from smolagents import Tool
from langchain_core.vectorstores import VectorStore
from typing import Optional, Union
import logging


class RetrieverTool(Tool):
    name = "retriever"
    description = """
    Retrieves relevant documents from the knowledge base using semantic similarity search.
    Choose k based on query complexity:
    - k=3-4: For standard questions needing some context  
    - k=5-7: For complex topics requiring multiple perspectives
    - k=8-10: For comprehensive research or broad exploration
    """

    inputs = {
        "query": {
            "type":
            "string",
            "description":
            "The search query. Use descriptive keywords and phrases rather than questions. Example: 'machine learning algorithms' instead of 'what are ML algorithms?'",
        },
        "k": {
            "type": "integer",
            "description":
            "Number of documents to retrieve (3-10). Choose based on query complexity: 3 for standard questions, 5-7 for complex topics, 8-10 for comprehensive research. Default: 3 if not specified.",
            "nullable": True
        }
    }

    output_type = "string"

    def __init__(self,
                 vectordb: VectorStore,
                 k: int = 3,
                 score_threshold: Optional[float] = None,
                 max_content_length: int = 1000,
                 **kwargs):
        super().__init__(**kwargs)
        self.vectordb = vectordb
        self.k = k
        self.score_threshold = score_threshold
        self.max_content_length = max_content_length
        self.logger = logging.getLogger(self.__class__.__name__)

    def forward(self, query: str, k: Optional[int] = None) -> str:
        # Input validation
        if not query or not isinstance(query, str) or not query.strip():
            return "Error: Query must be a non-empty string"

        # Parameter validation
        retrieval_k = k if k is not None else self.k
        if retrieval_k is not None and (not isinstance(retrieval_k, int) or
                                        retrieval_k < 3 or retrieval_k > 20):
            retrieval_k = self.k

        query = query.strip()

        try:
            # Try to get documents with scores if available
            if hasattr(self.vectordb, 'similarity_search_with_score'
                       ) and self.score_threshold is not None:
                docs_with_scores = self.vectordb.similarity_search_with_score(
                    query, k=retrieval_k)
                # Filter by score threshold
                filtered_docs = [
                    doc for doc, score in docs_with_scores
                    if score >= self.score_threshold
                ]
                docs = filtered_docs[:retrieval_k] if filtered_docs else []

                if not docs and docs_with_scores:
                    # If no docs meet threshold, take the best one anyway
                    docs = [docs_with_scores[0][0]]

            else:
                docs = self.vectordb.similarity_search(query, k=retrieval_k)

        except Exception as e:
            self.logger.error(f"Error during similarity search: {str(e)}")
            return f"Error retrieving documents: {str(e)}"

        # Handle no results
        if not docs:
            return f"No relevant documents found for query: '{query}'"

        # Format results
        return self._format_results(query, docs)

    def _format_results(self, query: str, docs) -> str:
        """Format the retrieved documents into a readable string."""
        result_parts = [
            f"Search Query: {query}",
            f"Retrieved {len(docs)} relevant document(s):", ""
        ]

        for i, doc in enumerate(docs, 1):
            # Add document header
            result_parts.append(f"=== Document {i} ===")

            # Add metadata if available
            if hasattr(doc, 'metadata') and doc.metadata:
                metadata_info = []
                if 'source' in doc.metadata:
                    metadata_info.append(f"Source: {doc.metadata['source']}")
                if 'title' in doc.metadata:
                    metadata_info.append(f"Title: {doc.metadata['title']}")
                if 'page' in doc.metadata:
                    metadata_info.append(f"Page: {doc.metadata['page']}")

                if metadata_info:
                    result_parts.append(" | ".join(metadata_info))

            # Add content (with truncation if needed)
            content = doc.page_content
            if len(content) > self.max_content_length:
                content = content[:self.max_content_length].rsplit(
                    ' ', 1)[0] + "... [truncated]"

            result_parts.append(content)
            result_parts.append("")  # Empty line between documents

        return "\n".join(result_parts).strip()

    def get_retrieval_stats(self) -> dict:
        """Get basic stats about the vector store if available."""
        try:
            # This depends on the vector store implementation
            if hasattr(self.vectordb, '__len__'):
                return {"total_documents": len(self.vectordb)}
            return {"status": "Vector store connected"}
        except Exception:
            return {"status": "Unable to retrieve stats"}

In [61]:
# old retriever tool
from smolagents import Tool
from langchain_core.vectorstores import VectorStore


class RetrieverTool(Tool):
    name = "retriever"
    description = "Using semantic similarity, retrieves some documents from the knowledge base that have the closest embeddings to the input query."
    inputs = {
        "query": {
            "type":
            "string",
            "description":
            "The query to perform. This should be semantically close to your target documents. Use the affirmative form rather than a question.",
        }
    }
    output_type = "string"

    def __init__(self, vectordb: VectorStore, **kwargs):
        super().__init__(**kwargs)
        self.vectordb = vectordb

    def forward(self, query: str) -> str:
        assert isinstance(query, str), "Your search query must be a string"

        docs = self.vectordb.similarity_search(
            query,
            k=7,
        )

        return "\nRetrieved documents:\n" + "".join([
            f"===== Document {str(i)} =====\n" + doc.page_content
            for i, doc in enumerate(docs)
        ])

In [ ]:
from smolagents import OpenAIServerModel, CodeAgent
from config.config import Blablador_API_KEY
from smolagents.monitoring import LogLevel
from utils.blablador import Models

# answer_llm = OpenAIServerModel(
#     # model_id="gemini-1.5-flash",
#     model_id="gemini-2.5-flash-preview-05-20",
#     # model_id="gemini-2.5-flash-preview-04-17",
#     api_base="https://generativelanguage.googleapis.com/v1beta/openai/",
#     api_key="AIzaSyCEf0KHWLTOq4P7aFfeNkoKAa3lHldydxk",
#     temperature=0.6)

# models = Models(api_key=Blablador_API_KEY).get_model_ids()

answer_llm = OpenAIServerModel(
    model_id=models[4],
    api_base="https://helmholtz-blablador.fz-juelich.de:8000/v1",
    api_key=Blablador_API_KEY,
    flatten_messages_as_text=True,
    temperature=0.6)

retriever_tool = RetrieverTool(vectordb)
# retriever_tool = RetrieverTool(vectordb, score_threshold=0.7)

agent = CodeAgent(tools=[retriever_tool],
                  model=answer_llm,
                  planning_interval=2,
                  verbosity_level=LogLevel.ERROR)

In [9]:
agent_output = agent.run("How can I push a model to the Hub?")

print("Final output:")
print(agent_output)

╭──────────────────────────────────────────────────── New run ────────────────────────────────────────────────────╮
│                                                                                                                 │
│ How can I push a model to the Hub?                                                                              │
│                                                                                                                 │
╰─ OpenAIServerModel - 2 - Qwen3 30B A3B - a reasoning model from Alibaba from April 2025 ────────────────────────╯

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 1 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

 ─ Executing parsed code: ────────────────────────────────────────────────────────────────────────────────────────
  documentation = retriever(query="How to push a model to the Hub", k=3)
  print(documentation)
 ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Execution logs:
Search Query: How to push a model to the Hub
Retrieved 3 relevant document(s):

=== Document 1 ===
Source: course
.push_to_hub(). So this is more of a once-off method - it's not called regularly during training. You can just call
this manually whenever you want to upload a model to the hub. So we recommend running this after the end of
training, just to make sure that you have a commit message just to guarantee that this was the final version of the
model at the end of training. And it just makes sure that you're working with the definitive end-of-training model
and not accidentally using a model that's from a checkpoint somewhere along the way

=== Document 2 ===
Source: transformers
```py
>>> trainer.push_to_hub()
```
</pt>
<tf>
Share a model to the Hub with [`PushToHubCallback`]. In the [`PushToHubCallback`] function, add:

- An output directory for your model.
- A tokenizer.
- The `hub_model_id`, which is your Hub username and model name.

```py
>>> from transformers import PushToHubCallback

>>> push_to_hub_callback = PushToHubCallback(
...     output_dir="./your_model_save_path", tokenizer=tokenizer, hub_model_id="your-username/my-awesome-model"
... )
```

=== Document 3 ===
Source: blog
Finally, if you want, you can push your model up to the hub. Here, we'll push it up if you specified
`push_to_hub=True` in the training configuration. Note that in order to push to hub, you'll have to have git-lfs
installed and be logged into your Hugging Face account (which can be done via `huggingface-cli login`).

```python
kwargs = {
    "finetuned_from": model.config._name_or_path,
    "tasks": "image-classification",
    "dataset": 'beans',
    "tags": ['image-classification'],
}

if training_args.push_to_hub:
    trainer.push_to_hub('🍻 cheers', **kwargs)
else:
    trainer.create_model_card(**kwargs)
```

Out: None

[Step 1: Duration 3.61 seconds| Input tokens: 2,198 | Output tokens: 70]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Step 2 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

 ─ Executing parsed code: ────────────────────────────────────────────────────────────────────────────────────────
  final_answer("To push a model to the Hub, you can use the `push_to_hub()` method or the `PushToHubCallback`
  function. This involves specifying an output directory, a tokenizer, and the `hub_model_id` (your Hub username
  and model name). Additionally, ensure you are logged into your Hugging Face account and have git-lfs
  installed.")
 ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Out - Final answer: To push a model to the Hub, you can use the `push_to_hub()` method or the `PushToHubCallback`
function. This involves specifying an output directory, a tokenizer, and the `hub_model_id` (your Hub username and
model name). Additionally, ensure you are logged into your Hugging Face account and have git-lfs installed.

[Step 2: Duration 4.29 seconds| Input tokens: 4,989 | Output tokens: 205]

Final output:
To push a model to the Hub, you can use the `push_to_hub()` method or the `PushToHubCallback` function. This involves specifying an output directory, a tokenizer, and the `hub_model_id` (your Hub username and model name). Additionally, ensure you are logged into your Hugging Face account and have git-lfs installed.

In [10]:
eval_dataset = datasets.load_dataset("m-ric/huggingface_doc_qa_eval",
                                     split="train")

In [55]:
##### using agentic RAG to answer questions
import time

outputs_agentic_rag = []

# inspect = eval_dataset.select([24, 28])

for example in tqdm(eval_dataset):
    question = example["question"]

    #     enhanced_question = f"""Using the information contained in your knowledge base, which you can access with the 'retriever' tool,
    # give a comprehensive answer to the question below.
    # Respond only to the question asked, response should be concise and relevant to the question.
    # If you cannot find information, do not give up and try calling your retriever again with different arguments!
    # Make sure to have covered the question completely by calling the retriever tool several times with semantically different queries.
    # Your queries should not be questions but affirmative form sentences: e.g. rather than "How do I load a model from the Hub in bf16?", query should be "load a model from the Hub bf16 weights".

    # Question:
    # {question}"""
    # enhanced_question = f"""You have access to a knowledge base via the 'retriever' tool. Use it strategically to gather relevant information and answer the question below.

    # **Retrieval Strategy:**
    # - Start with k=3 for standard questions needing some context
    # - Use k=5-7 for complex topics requiring multiple perspectives
    # - Use k=8-10 for comprehensive research or broad exploration

    # **Query Guidelines:**
    # - Use declarative phrases instead of questions (e.g., "load a model from the Hub bf16 weights" not "How do I load a model from the Hub in bf16")
    # - Try multiple semantically different queries to verify completeness
    # - If initial results lack key information, increase k and retry with alternative search terms

    # **Response Guidelines:**
    # - Answer only the specific question asked - be concise and focused
    # - Base responses strictly on retrieved information - do not speculate or add external knowledge
    # - If information seems incomplete after multiple retrieval attempts, state what's missing

    # **Verification Process:**
    # 1. Start with focused retrieval (k=3-5)
    # 2. If answer seems incomplete, expand retrieval (k>5)
    # 3. Cross-verify with alternative query phrasings
    # 4. Synthesize information from multiple retrievals if needed

    # Question: {question}
    # """

    enhanced_question = f"""Use the 'retriever' tool to find information and answer this question: {question}

    Instructions:
    - Search the knowledge base using relevant keywords
    - Start with 3-5 documents, increase if needed
    - Try different search terms if initial results don't answer the question
    - Provide a direct answer based on what you find

    Question: {question}
    """
    answer = agent.run(enhanced_question)
    print("=======================================================")
    print(f"Question: {question}")
    print(f"Answer: {answer}")
    print(f'True answer: {example["answer"]}')

    results_agentic = {
        "question": question,
        "true_answer": example["answer"],
        "source_doc": example["source_doc"],
        "generated_answer": answer,
    }
    outputs_agentic_rag.append(results_agentic)
    # time.sleep(10)

  2%|▏         | 1/65 [00:13<14:23, 13.50s/it]

=======================================================
Question: What architecture is the `tokenizers-linux-x64-musl` binary designed for?

Answer: x86_64-unknown-linux-musl
True answer: x86_64-unknown-linux-musl

  3%|▎         | 2/65 [00:44<25:14, 24.04s/it]

=======================================================
Question: What is the purpose of the BLIP-Diffusion model?

Answer: The BLIP-Diffusion model is likely designed for tasks that combine image generation with language understanding, such as generating images based on textual descriptions or aligning images with corresponding text.
True answer: The BLIP-Diffusion model is designed for controllable text-to-image generation and editing.

  5%|▍         | 3/65 [00:58<19:46, 19.13s/it]

=======================================================
Question: How can a user claim authorship of a paper on the Hugging Face Hub?

Answer: A user can claim authorship of a paper on the Hugging Face Hub by clicking on their name in the corresponding Paper page and selecting 'claim authorship.' This will redirect them to their paper settings where they can confirm the request. The admin team will validate the request and, once confirmed, the Paper page will show as verified.
True answer: By clicking their name on the corresponding Paper page and clicking "claim authorship", then confirming the request in paper settings for admin team validation.

  6%|▌         | 4/65 [01:11<16:57, 16.68s/it]

=======================================================
Question: What is the purpose of the /healthcheck endpoint in the Datasets server API?

Answer: The purpose of the /healthcheck endpoint in the Datasets server API is to ensure the app is running.
True answer: Ensure the app is running

  8%|▊         | 5/65 [01:42<22:04, 22.08s/it]

=======================================================
Question: What is the default context window size for Local Attention in the LongT5 model?

Answer: 512
True answer: 127 tokens

  9%|▉         | 6/65 [01:55<18:37, 18.95s/it]

=======================================================
Question: What method is used to load a checkpoint for a task using `AutoPipeline`?

Answer: from_pretrained
True answer: from_pretrained()

 11%|█         | 7/65 [02:09<16:42, 17.29s/it]

=======================================================
Question: What is the purpose of Diffusers library?

Answer: The purpose of the Diffusers library is to provide a modular toolbox for generating images, audio, and 3D structures of molecules using state-of-the-art pretrained diffusion models. It supports both simple inference and training of diffusion models, with a focus on usability, simplicity, and customizability.
True answer: To serve as a modular toolbox for both inference and training of state-of-the-art pretrained diffusion models across multiple modalities.

 12%|█▏        | 8/65 [02:24<15:48, 16.64s/it]

=======================================================
Question: What method does the EulerAncestralDiscreteScheduler use for sampling?

Answer: ancestral sampling with Euler method steps
True answer: Ancestral sampling with Euler method steps.

 14%|█▍        | 9/65 [02:36<14:09, 15.18s/it]

=======================================================
Question: What is the name of the large multimodal model that can solve image-text tasks and is based on Flamingo?

Answer: IDEFICS
True answer: IDEFICS

 15%|█▌        | 10/65 [02:50<13:29, 14.72s/it]

=======================================================
Question: What is the purpose of the `gradio.Blocks` API?

Answer: The purpose of the `gradio.Blocks` API is to create web applications with more flexible layouts and data flows, allowing for advanced features such as handling multiple data streams, controlling component placement on the page, and managing complex interactions.
True answer: The `gradio.Blocks` API allows you to have full control over the data flows and layout of your application, enabling the building of complex, multi-step applications.

 17%|█▋        | 11/65 [03:05<13:24, 14.90s/it]

=======================================================
Question: What is the purpose of the two-stage model proposed in the paper "Hierarchical Text-Conditional Image Generation with CLIP Latents"?

Answer: The purpose of the two-stage model is to generate image representations (CLIP image embeddings) from text captions, which are then used by a decoder to generate images. This approach improves image diversity while maintaining photorealism and caption similarity.
True answer: The purpose of the two-stage model is to generate a CLIP image embedding given a text caption and then generate an image conditioned on the image embedding.

 18%|█▊        | 12/65 [03:28<15:14, 17.26s/it]

=======================================================
Question: What command is used to install the requirements for a research project using 🤗 Transformers?

Answer: pip install -r requirements.txt
True answer: pip install -r requirements.txt

 20%|██        | 13/65 [03:54<17:18, 19.98s/it]

=======================================================
Question: What task does the `roberta-large-mnli` checkpoint perform?

Answer: The `roberta-large-mnli` checkpoint performs the Multi-Genre Natural Language Inference (MNLI) task, which involves determining the relationship between a premise and a hypothesis (e.g., entailment, contradiction, or neutral).
True answer: Text classification

 22%|██▏       | 14/65 [04:18<18:02, 21.22s/it]

=======================================================
Question: What service is replacing the Paid tier of the Inference API at Hugging Face?

Answer: Inference Endpoints
True answer: Inference Endpoints

 23%|██▎       | 15/65 [04:31<15:29, 18.59s/it]

=======================================================
Question: What architectural feature does SqueezeBERT use instead of fully-connected layers for the Q, K, V, and FFN layers?

Answer: grouped convolutions
True answer: Grouped convolutions

 25%|██▍       | 16/65 [04:42<13:24, 16.42s/it]

=======================================================
Question: What type of license is the HuggingFace Team's software distributed under?

Answer: Apache License, Version 2.0
True answer: Apache License, Version 2.0

 26%|██▌       | 17/65 [04:55<12:17, 15.37s/it]

=======================================================
Question: What are the two parameter-reduction techniques proposed in the ALBERT model to lower memory consumption and increase training speed?

Answer: The two parameter-reduction techniques proposed in the ALBERT model are: 1) Splitting the embedding matrix into two smaller matrices, and 2) Using repeating layers split among groups.
True answer: Splitting the embedding matrix into two smaller matrices and using repeating layers split among groups.

 28%|██▊       | 18/65 [05:28<16:08, 20.61s/it]

=======================================================
Question: What are the three main steps for fine-tuning a model with the 🤗 Datasets library?

Answer: The three main steps for fine-tuning a model with the 🤗 Datasets library are: (1) selecting a pretrained model, (2) preparing the dataset using the 🤗 Datasets library, and (3) training the model with fine-tuning.
True answer: 1. Load a dataset from the Hugging Face Hub. 2. Preprocess the data with `Dataset.map()`. 3. Load and compute metrics.

 29%|██▉       | 19/65 [05:42<14:16, 18.61s/it]

=======================================================
Question: What is the maximum improvement in throughput achieved by Hugging Face Infinity compared to vanilla transformers?

Answer: 800%
True answer: +800%

 31%|███       | 20/65 [05:55<12:40, 16.91s/it]

=======================================================
Question: What is the command to upload a spaCy pipeline to the Hugging Face Hub?

Answer: python -m spacy huggingface-hub
True answer: python -m spacy huggingface-hub push en_ner_fashion-0.0.0-py3-none-any.whl

 32%|███▏      | 21/65 [06:48<20:28, 27.91s/it]

=======================================================
Question: What is the time and memory complexity of the Nyströmformer's approximation of self-attention?

Answer: The time and memory complexity of the Nyströmformer's approximation of self-attention is $O(n)$.
True answer: O(n)

 34%|███▍      | 22/65 [07:02<16:51, 23.53s/it]

=======================================================
Question: What is the goal of the Named Entity Recognition task in token classification?

Answer: The goal of the Named Entity Recognition task in token classification is to identify and label entities in a piece of text, such as persons, locations, organizations, or other specific categories.
True answer: The goal of the Named Entity Recognition task is to find the entities in a piece of text, such as person, location, or organization.

 35%|███▌      | 23/65 [07:14<14:11, 20.26s/it]

=======================================================
Question: What is the resolution of images used by the CLIPSeg model?

Answer: 352 x 352 pixels
True answer: 352 x 352 pixels

 37%|███▋      | 24/65 [07:26<12:06, 17.72s/it]

=======================================================
Question: What can you use Gradio for?

Answer: Gradio is a Python library used for building interactive web interfaces for machine learning and AI models, enabling easy testing, sharing, and demonstration of these models.
True answer: Create a demo for your machine learning model, share your machine learning model with others, and debug your model.

 38%|███▊      | 25/65 [07:38<10:35, 15.89s/it]

=======================================================
Question: What TensorFlow API function is used to load a saved tensor file?

Answer: safetensors.tensorflow.load_file
True answer: safetensors.tensorflow.load_file

 40%|████      | 26/65 [07:50<09:41, 14.92s/it]

=======================================================
Question: Where can you access the logs of your Endpoints in Hugging Face Endpoints?

Answer: You can access the logs of your Endpoints in Hugging Face Endpoints through the 'Logs' tab of your Endpoint in the Hugging Face UI.
True answer: In the "Logs" tab of your Endpoint through the UI.

 42%|████▏     | 27/65 [08:10<10:24, 16.42s/it]

=======================================================
Question: What is the latest task added to Hugging Face AutoTrain for Computer Vision?

Answer: Image Classification
True answer: Image Classification

 43%|████▎     | 28/65 [08:23<09:24, 15.26s/it]

=======================================================
Question: What is the default repository type created by the `create_repo` function on Hugging Face Hub?

Answer: model
True answer: model

 45%|████▍     | 29/65 [08:34<08:29, 14.15s/it]

=======================================================
Question: How many splits does the "duorc" dataset have?

Answer: 6
True answer: Six

 46%|████▌     | 30/65 [08:48<08:13, 14.11s/it]

=======================================================
Question: What is the purpose of Fully Sharded Data Parallel (FSDP) in distributed training?

Answer: Fully Sharded Data Parallel (FSDP) is used in distributed training to shard a model's parameters, gradients, and optimizer states across multiple GPUs. This improves memory efficiency, enabling the training of larger models on fewer GPUs.
True answer: FSDP is developed for distributed training of large pretrained models up to 1T parameters by sharding the model parameters, gradients, and optimizer states across data parallel processes.

 48%|████▊     | 31/65 [09:01<07:42, 13.59s/it]

=======================================================
Question: What file format is used to save and store PyTorch model weights more securely than `.bin` files?

Answer: safetensors
True answer: `.safetensors`

 49%|████▉     | 32/65 [09:12<07:02, 12.82s/it]

=======================================================
Question: What type of security certification does Hugging Face have?

Answer: Hugging Face is SOC2 Type 2 certified.
True answer: SOC2 Type 2 certified

 51%|█████     | 33/65 [09:24<06:47, 12.73s/it]

=======================================================
Question: What do RAG models combine to generate outputs?

Answer: RAG models combine pretrained dense retrieval (DPR) and sequence-to-sequence models to generate outputs.
True answer: Pretrained dense retrieval (DPR) and sequence-to-sequence models.

 52%|█████▏    | 34/65 [09:37<06:34, 12.74s/it]

=======================================================
Question: What library does MarkupLMFeatureExtractor use to extract data from HTML and XML files?

Answer: Beautiful Soup
True answer: Beautiful Soup

 54%|█████▍    | 35/65 [09:49<06:15, 12.50s/it]

=======================================================
Question: What is the file size limit for syncing to HF Spaces without using Git-LFS?

Answer: 10MB
True answer: 10MB

 55%|█████▌    | 36/65 [10:01<05:59, 12.39s/it]

=======================================================
Question: What is the title of the paper introducing the ByT5 model?

Answer: ByT5: Towards a token-free future with pre-trained byte-to-byte models
True answer: ByT5: Towards a token-free future with pre-trained byte-to-byte models

 57%|█████▋    | 37/65 [10:13<05:43, 12.28s/it]

=======================================================
Question: What is the dimension of the feature vector for the base BERT model?

Answer: 768
True answer: 768

 58%|█████▊    | 38/65 [10:24<05:17, 11.74s/it]

=======================================================
Question: What special identifier does the WordPiece Model use for continuing subwords?

Answer: ##
True answer: ##

 60%|██████    | 39/65 [10:36<05:08, 11.87s/it]

=======================================================
Question: What is the purpose of the 🧨 Diffusers tutorials?

Answer: The purpose of the 🧨 Diffusers tutorials is to provide a beginner-friendly introduction to diffusion models and the Diffusers library, helping users understand the fundamentals, use pipelines for inference, and build their own diffusion systems.
True answer: To provide a gentle introduction to diffusion models and help understand the library fundamentals.

 62%|██████▏   | 40/65 [10:47<04:52, 11.69s/it]

=======================================================
Question: What is the default setting for the `allow_flagging` parameter in Gradio's `Interface`?

Answer: manual
True answer: "manual"

 63%|██████▎   | 41/65 [10:59<04:45, 11.91s/it]

=======================================================
Question: Where can the full code for the Stable Diffusion demo be found?

Answer: The full code for the Stable Diffusion demo can be found at https://github.com/CompVis/stable-diffusion.
True answer: https://hf.co/spaces/stabilityai/stable-diffusion/tree/main

 65%|██████▍   | 42/65 [11:13<04:41, 12.25s/it]

=======================================================
Question: What transformation does the FNet model use to replace the self-attention layer in a BERT model?

Answer: Fourier transform
True answer: Fourier transform

 66%|██████▌   | 43/65 [11:46<06:46, 18.49s/it]

=======================================================
Question: What type of test should typically accompany a bug fix in Gradio's testing strategy?

Answer: unit test
True answer: Dynamic code test

 68%|██████▊   | 44/65 [11:59<05:56, 16.98s/it]

=======================================================
Question: How can you force mixed precision training when initializing the Accelerator in 🤗 Accelerate?

Answer: To force mixed precision training when initializing the Accelerator in 🤗 Accelerate, set `bf16=True` in the `TrainingArguments`.
True answer: By passing `fp16=True` to the Accelerator init.

 69%|██████▉   | 45/65 [12:12<05:14, 15.72s/it]

=======================================================
Question: What is the purpose of tokenizers in the NLP pipeline?

Answer: Tokenizers in the NLP pipeline are used to convert raw text into numerical data that can be processed by models. They handle tasks like normalization, pre-tokenization, tokenization, and post-processing.
True answer: To translate text into data that can be processed by the model.

 71%|███████   | 46/65 [12:36<05:49, 18.38s/it]

=======================================================
Question: What is the purpose of the Safety Checker in the Diffusers library?

Answer: The Safety Checker in the Diffusers library is designed to screen generated content for harmful or inappropriate material, ensuring ethical and responsible use of generative models.
True answer: The Safety Checker checks and compares the class probability of a set of hard-coded harmful concepts in the embedding space against an image after it has been generated to mitigate the risk of generating harmful content.

 72%|███████▏  | 47/65 [12:49<04:58, 16.57s/it]

=======================================================
Question: What Python class allows you to retrieve Discussions and Pull Requests from a given repository on the Hugging Face Hub?

Answer: HfApi
True answer: HfApi

 74%|███████▍  | 48/65 [13:49<08:22, 29.53s/it]

=======================================================
Question: What is the name of the new library introduced by Hugging Face for hosting scikit-learn models?

Answer: huggingface_hub
True answer: Skops

 75%|███████▌  | 49/65 [14:02<06:37, 24.83s/it]

=======================================================
Question: What is the purpose of Textual Inversion?

Answer: Textual Inversion is a technique used to personalize image generation models by learning new text embeddings from a few example images. This allows the model to generate images based on specific concepts or styles provided by the user.
True answer: Textual Inversion is a training method for personalizing models by learning new text embeddings from a few example images.

 77%|███████▋  | 50/65 [14:47<07:42, 30.85s/it]

=======================================================
Question: What is the recommended multiple of batch size for fp16 data type on an A100 GPU?

Answer: 16
True answer: 64

 78%|███████▊  | 51/65 [15:02<06:03, 25.93s/it]

=======================================================
Question: How do you run a Gradio Blocks app in reload mode using a Python IDE?

Answer: To run a Gradio Blocks app in reload mode using a Python IDE, use the `gradio` command followed by the file name instead of the `python` command. For example, run `gradio app.py` in the terminal. This will start the app in reload mode, which automatically reloads the app when changes are made.
True answer: Run `gradio run.py` in the terminal.

 80%|████████  | 52/65 [15:16<04:50, 22.33s/it]

=======================================================
Question: How can you install the Hugging Face Unity API in your Unity project?

Answer: To install the Hugging Face Unity API in your Unity project, follow these steps:
1. Open your Unity project.
2. Go to `Window` -> `Package Manager`.
3. Click `+` and select `Add Package from git URL`.
4. Enter the URL: `https://github.com/huggingface/unity-api.git`.
5. Once installed, the Unity API wizard should pop up. If not, go to `Window` -> `Hugging Face API Wizard`.
True answer: To install the Hugging Face Unity API in your Unity project, go to `Window` -> `Package Manager`, click `+` and select `Add Package from git URL`, then enter `https://github.com/huggingface/unity-api.git`.

 82%|████████▏ | 53/65 [15:31<04:01, 20.13s/it]

=======================================================
Question: What is the pretraining objective of the Wav2Vec2 context network?

Answer: The pretraining objective of the Wav2Vec2 context network is a contrastive task, where the model predicts the true quantized speech representation of the masked prediction from a set of false ones.
True answer: The pretraining objective of the Wav2Vec2 context network is a contrastive task where the model has to predict the true quantized speech representation of the masked prediction from a set of false ones.

 83%|████████▎ | 54/65 [15:43<03:17, 17.92s/it]

=======================================================
Question: What is the default checkpoint used by the sentiment analysis pipeline in the Transformers library?

Answer: distilbert-base-uncased-finetuned-sst-2-english
True answer: distilbert base uncased finetuned sst2 english

 85%|████████▍ | 55/65 [15:57<02:46, 16.69s/it]

=======================================================
Question: What is the purpose of the notebook "How to use DeepSpeed to train models with billions of parameters on Habana Gaudi"?

Answer: The purpose of the notebook is to demonstrate how to use DeepSpeed to pre-train or fine-tune a 1.6B-parameter GPT2-XL model for causal language modeling on Habana Gaudi.
True answer: To show how to use DeepSpeed to pre-train/fine-tune the 1.6B-parameter GPT2-XL for causal language modeling on Habana Gaudi.

 86%|████████▌ | 56/65 [16:29<03:12, 21.34s/it]

=======================================================
Question: What command line module does PyTorch provide to run a script on multiple GPUs?

Answer: torchrun
True answer: torchrun

 88%|████████▊ | 57/65 [17:01<03:14, 24.30s/it]

=======================================================
Question: What is the most popular vision transformer model on the Hugging Face Model Hub for image classification?

Answer: google/vit-base-patch16-224
True answer: google/vit-base-patch16-224

 89%|████████▉ | 58/65 [17:14<02:27, 21.05s/it]

=======================================================
Question: What is the command to upload an ESPnet model to a Hugging Face repository?

Answer: ./run.sh --stage 15 --skip_upload_hf false --hf_repo username/model_repo
True answer: ./run.sh --stage 15 --skip_upload_hf false --hf_repo username/model_repo

 91%|█████████ | 59/65 [17:27<01:51, 18.60s/it]

=======================================================
Question: What file should be added to a model repository to install custom Python dependencies for Inference Endpoints?

Answer: requirements.txt
True answer: requirements.txt

 92%|█████████▏| 60/65 [17:40<01:24, 16.96s/it]

=======================================================
Question: How many images are needed to teach new concepts to Stable Diffusion using Textual Inversion?

Answer: 3-5
True answer: 3-5 images

 94%|█████████▍| 61/65 [17:54<01:04, 16.09s/it]

=======================================================
Question: What is the maximum size of a model checkpoint before it is automatically sharded in Transformers version 4.18.0?

Answer: 10GB
True answer: 10GB

 95%|█████████▌| 62/65 [19:00<01:33, 31.12s/it]

=======================================================
Question: What is the purpose of Weights and Biases (W&B) for data scientists and machine learning scientists?

Answer: Weights and Biases (W&B) is a platform for tracking and monitoring machine learning experiments. It helps data scientists and machine learning scientists log metrics, model topology, and gradients, which aids in analyzing and improving model performance. It is particularly useful for tracking training runs, comparing different models, and ensuring reproducibility.
True answer: To track their machine learning experiments at every stage, from training to production.

 97%|█████████▋| 63/65 [19:12<00:50, 25.31s/it]

=======================================================
Question: What is the name of the open-source library created by Hugging Face to simplify Transformer acceleration?

Answer: Optimum
True answer: Optimum

 98%|█████████▊| 64/65 [19:24<00:21, 21.36s/it]

=======================================================
Question: What parameter is used to ensure that elements in a row have the same height in Gradio?

Answer: equal_height
True answer: equal_height

100%|██████████| 65/65 [19:37<00:00, 18.11s/it]

=======================================================
Question: What is the command to install the latest version of Optimum with OpenVINO support?

Answer: pip install --upgrade-strategy eager optimum[openvino]
True answer: pip install --upgrade-strategy eager optimum["openvino"]

In [ ]:
## Set a checkpoint for query limitations (limited API)

import time
import json
import os
from tqdm import tqdm


def run_agentic_rag_with_checkpointing(
        eval_dataset,
        agent,
        checkpoint_file="checkpoints/rag_checkpoint.json"):
    """
    Run agentic RAG with checkpointing to allow resuming from interruptions.
    
    Args:
        eval_dataset: Dataset containing questions and answers
        agent: The agent to run queries with
        checkpoint_file: File to store checkpointing information
    
    Returns:
        List of results from agentic RAG
    """
    outputs_agentic_rag = []
    start_idx = 0

    # Load checkpoint if exists
    if os.path.exists(checkpoint_file):
        try:
            with open(checkpoint_file, 'r') as f:
                checkpoint_data = json.load(f)
                outputs_agentic_rag = checkpoint_data.get('results', [])
                start_idx = checkpoint_data.get('next_idx', 0)
                print(
                    f"Resuming from checkpoint at index {start_idx} with {len(outputs_agentic_rag)} results already processed"
                )
        except Exception as e:
            print(f"Error loading checkpoint: {e}")
            print("Starting from beginning")

    # Create progress bar starting from checkpoint
    total_examples = len(eval_dataset)
    pbar = tqdm(total=total_examples, initial=start_idx)

    try:
        for idx in range(start_idx, total_examples):
            example = eval_dataset[idx]
            question = example["question"]

            enhanced_question = f"""You have access to a knowledge base via the 'retriever' tool. Use it to gather relevant information and answer the question below.
Guidelines:
- Answer only the specific question asked. Be concise and avoid unrelated information.
- When possible, support your answer with retrieved evidence and cite the corresponding source document number(s).
- Base your response strictly on the retrieved information. Do not speculate.
- Once you have an initial answer, re-query the retriever using semantically different prompts to verify or refine your response.
If the retrieved information is insufficient:
- Retry the retriever with alternative, semantically distinct queries.
- Use declarative sentence fragments instead of questions.
  For example, instead of "How do I load a model from the Hub in bf16?", use "load model from Hugging Face Hub bf16 weights".
Question:
{question}
"""
            try:
                answer = agent.run(enhanced_question)

                print(
                    "=======================================================")
                print(f"Question: {question}")
                print(f"Answer: {answer}")
                print(f'True answer: {example["answer"]}')

                results_agentic = {
                    "question": question,
                    "true_answer": example["answer"],
                    "source_doc": example["source_doc"],
                    "generated_answer": answer,
                }

                outputs_agentic_rag.append(results_agentic)

                # Update checkpoint after each successful query
                save_checkpoint(checkpoint_file, outputs_agentic_rag, idx + 1)

                pbar.update(1)
                # time.sleep(10)  # Rate limiting

            except Exception as e:
                print(f"Error processing example {idx}: {e}")
                # Save checkpoint before exiting
                save_checkpoint(checkpoint_file, outputs_agentic_rag, idx)
                print(f"Checkpoint saved. Resume from index {idx}")
                raise

    except KeyboardInterrupt:
        print("\nProcess interrupted by user")
        # Save checkpoint before exiting
        save_checkpoint(checkpoint_file, outputs_agentic_rag, idx)
        print(f"Checkpoint saved. Resume from index {idx}")

    finally:
        pbar.close()

    return outputs_agentic_rag


def save_checkpoint(checkpoint_file, results, next_idx):
    """Save checkpoint data to file"""
    checkpoint_data = {
        "results": results,
        "next_idx": next_idx,
        "timestamp": time.time()
    }

    # Use a temporary file to avoid corruption if interrupted during writing
    temp_file = f"{checkpoint_file}.temp"
    with open(temp_file, 'w') as f:
        json.dump(checkpoint_data, f)

    # Safely replace the old checkpoint file
    if os.path.exists(checkpoint_file):
        os.replace(temp_file, checkpoint_file)
    else:
        os.rename(temp_file, checkpoint_file)


outputs_agentic_rag = run_agentic_rag_with_checkpointing(eval_dataset, agent)

Resuming from checkpoint at index 65 with 65 results already processed

100%|██████████| 65/65 [00:00<?, ?it/s]

In [ ]:
##### using only RAG to answer questions

# reader_llm = OpenAIServerModel(
#     model_id="gemini-2.0-flash",
#     api_base="https://generativelanguage.googleapis.com/v1beta/openai/",
#     api_key=Gemini_API_KEY,
#     temperature=0.2)

answer_llm = OpenAIServerModel(
    model_id=models[4],
    api_base="https://helmholtz-blablador.fz-juelich.de:8000/v1",
    api_key=Blablador_API_KEY,
    # flatten_messages_as_text=True,
    temperature=0.6)

outputs_standard_rag = []

for example in tqdm(eval_dataset):
    question = example["question"]
    context = RetrieverTool(question, k=5)

    prompt = f"""Given the question and supporting documents below, give a comprehensive answer to the question.
Respond only to the question asked, response should be concise and relevant to the question.
If the question is ambiguous or cannot be answered definitively, state so clearly.

Question:
{question}

{context}
"""
    messages = [{"role": "user", "content": prompt}]
    answer = answer_llm.generate(messages).content

    print("=======================================================")
    print(f"Question: {question}")
    print(f"Answer: {answer}")
    print(f'True answer: {example["answer"]}')

    results_agentic = {
        "question": question,
        "true_answer": example["answer"],
        "source_doc": example["source_doc"],
        "generated_answer": answer,
    }
    outputs_standard_rag.append(results_agentic)
    # time.sleep(5)

  2%|▏         | 1/65 [00:01<01:50,  1.73s/it]

=======================================================
Question: What architecture is the `tokenizers-linux-x64-musl` binary designed for?

Answer: <think>

</think>

The `tokenizers-linux-x64-musl` binary is designed for the x64 (also known as AMD64) architecture. The "musl" in the name indicates that it is built with the musl libc library, which is a lightweight C standard library implementation, but it does not affect the CPU architecture. Therefore, the binary is intended for 64-bit systems.
True answer: x86_64-unknown-linux-musl

  3%|▎         | 2/65 [00:02<01:23,  1.32s/it]

=======================================================
Question: What is the purpose of the BLIP-Diffusion model?

Answer: <think>

</think>

The purpose of the BLIP-Diffusion model is to generate images based on textual descriptions, combining the capabilities of the BLIP (Bootstrap Likelihood for Image-Text pre-training) model with diffusion techniques to improve image generation quality and alignment with text.
True answer: The BLIP-Diffusion model is designed for controllable text-to-image generation and editing.

  5%|▍         | 3/65 [00:04<01:35,  1.55s/it]

=======================================================
Question: How can a user claim authorship of a paper on the Hugging Face Hub?

Answer: <think>

</think>

To claim authorship of a paper on the Hugging Face Hub, a user should ensure their name is included in the paper's metadata or documentation. If the paper is associated with a model, the user can update the model's information to reflect their authorship. Additionally, if the paper is hosted as a dataset or a model, the user can contact the Hugging Face team or use the platform's features to request changes to the authorship details. For specific steps, refer to Hugging Face's documentation or support resources.
True answer: By clicking their name on the corresponding Paper page and clicking "claim authorship", then confirming the request in paper settings for admin team validation.

  6%|▌         | 4/65 [00:05<01:19,  1.31s/it]

=======================================================
Question: What is the purpose of the /healthcheck endpoint in the Datasets server API?

Answer: <think>

</think>

The purpose of the /healthcheck endpoint in the Datasets server API is to verify the health and availability of the server. It typically returns a status code indicating whether the server is running and responsive.
True answer: Ensure the app is running

  8%|▊         | 5/65 [00:06<01:08,  1.14s/it]

=======================================================
Question: What is the default context window size for Local Attention in the LongT5 model?

Answer: <think>

</think>

The provided information does not specify the default context window size for Local Attention in the LongT5 model. Therefore, the question cannot be answered definitively based on the given data.
True answer: 127 tokens

  9%|▉         | 6/65 [00:07<01:01,  1.05s/it]

=======================================================
Question: What method is used to load a checkpoint for a task using `AutoPipeline`?

Answer: <think>

</think>

The provided information does not specify the method used to load a checkpoint for a task using `AutoPipeline`. Additional context or documentation would be required to answer this question definitively.
True answer: from_pretrained()

 11%|█         | 7/65 [00:08<01:08,  1.17s/it]

=======================================================
Question: What is the purpose of Diffusers library?

Answer: <think>

</think>

The purpose of the Diffusers library is to provide a flexible and efficient framework for working with diffusion models, which are a type of generative model used for tasks such as image generation, text-to-image synthesis, and other creative applications. It offers tools for training, fine-tuning, and deploying diffusion models, along with pre-trained models and utilities to streamline the development process.
True answer: To serve as a modular toolbox for both inference and training of state-of-the-art pretrained diffusion models across multiple modalities.

 12%|█▏        | 8/65 [00:09<00:56,  1.00it/s]

=======================================================
Question: What method does the EulerAncestralDiscreteScheduler use for sampling?

Answer: <think>

</think>

The EulerAncestralDiscreteScheduler uses the Euler method for sampling.
True answer: Ancestral sampling with Euler method steps.

 14%|█▍        | 9/65 [00:10<00:52,  1.06it/s]

=======================================================
Question: What is the name of the large multimodal model that can solve image-text tasks and is based on Flamingo?

Answer: <think>

</think>

The name of the large multimodal model that can solve image-text tasks and is based on Flamingo is **Flamingo**.
True answer: IDEFICS

 15%|█▌        | 10/65 [00:11<00:56,  1.02s/it]

=======================================================
Question: What is the purpose of the `gradio.Blocks` API?

Answer: <think>

</think>

The purpose of the `gradio.Blocks` API is to provide a flexible and customizable way to build complex user interfaces for machine learning models and web applications. It allows developers to define layouts, components, and interactions using a more programmatic and structured approach compared to the simpler `gradio.Interface` API.
True answer: The `gradio.Blocks` API allows you to have full control over the data flows and layout of your application, enabling the building of complex, multi-step applications.

 17%|█▋        | 11/65 [00:12<00:56,  1.05s/it]

=======================================================
Question: What is the purpose of the two-stage model proposed in the paper "Hierarchical Text-Conditional Image Generation with CLIP Latents"?

Answer: <think>

</think>

The purpose of the two-stage model proposed in the paper "Hierarchical Text-Conditional Image Generation with CLIP Latents" is to generate high-quality images conditioned on text by first generating latent representations using CLIP and then refining these latents to produce the final image.
True answer: The purpose of the two-stage model is to generate a CLIP image embedding given a text caption and then generate an image conditioned on the image embedding.

 18%|█▊        | 12/65 [00:13<00:58,  1.10s/it]

=======================================================
Question: What command is used to install the requirements for a research project using 🤗 Transformers?

Answer: <think>

</think>

The command to install the requirements for a research project using 🤗 Transformers is typically:

```bash
pip install -r requirements.txt
```

This command installs all the dependencies listed in the `requirements.txt` file, which often includes the `transformers` library and other necessary packages.
True answer: pip install -r requirements.txt

 20%|██        | 13/65 [00:14<00:55,  1.06s/it]

=======================================================
Question: What task does the `roberta-large-mnli` checkpoint perform?

Answer: <think>

</think>

The `roberta-large-mnli` checkpoint is used for natural language inference tasks, specifically for determining the relationship between a premise and a hypothesis (e.g., entailment, contradiction, or neutral).
True answer: Text classification

 22%|██▏       | 14/65 [00:15<00:48,  1.05it/s]

=======================================================
Question: What service is replacing the Paid tier of the Inference API at Hugging Face?

Answer: <think>

</think>

The service replacing the Paid tier of the Inference API at Hugging Face is the Inference Endpoints service.
True answer: Inference Endpoints

 23%|██▎       | 15/65 [00:16<00:44,  1.12it/s]

=======================================================
Question: What architectural feature does SqueezeBERT use instead of fully-connected layers for the Q, K, V, and FFN layers?

Answer: <think>

</think>

SqueezeBERT uses convolutional layers instead of fully-connected layers for the Q, K, V, and FFN layers.
True answer: Grouped convolutions

 25%|██▍       | 16/65 [00:16<00:40,  1.21it/s]

=======================================================
Question: What type of license is the HuggingFace Team's software distributed under?

Answer: <think>

</think>

The question cannot be answered definitively based on the provided information.
True answer: Apache License, Version 2.0

 26%|██▌       | 17/65 [00:17<00:41,  1.14it/s]

=======================================================
Question: What are the two parameter-reduction techniques proposed in the ALBERT model to lower memory consumption and increase training speed?

Answer: <think>

</think>

The two parameter-reduction techniques proposed in the ALBERT model to lower memory consumption and increase training speed are:
1. Shared parameter across layers (also known as parameter sharing).
2. Factorized embedding parameterization.
True answer: Splitting the embedding matrix into two smaller matrices and using repeating layers split among groups.

 28%|██▊       | 18/65 [00:18<00:46,  1.01it/s]

=======================================================
Question: What are the three main steps for fine-tuning a model with the 🤗 Datasets library?

Answer: <think>

</think>

The three main steps for fine-tuning a model with the 🤗 Datasets library are:
1. Load and preprocess the dataset using the Datasets library.
2. Tokenize the dataset using a tokenizer from the Transformers library.
3. Train the model using the trained tokenizer and processed dataset with the Transformers training API.
True answer: 1. Load a dataset from the Hugging Face Hub. 2. Preprocess the data with `Dataset.map()`. 3. Load and compute metrics.

 29%|██▉       | 19/65 [00:19<00:44,  1.04it/s]

=======================================================
Question: What is the maximum improvement in throughput achieved by Hugging Face Infinity compared to vanilla transformers?

Answer: <think>

</think>

The provided information does not specify the maximum improvement in throughput achieved by Hugging Face Infinity compared to vanilla transformers. Therefore, the question cannot be answered definitively with the given data.
True answer: +800%

 31%|███       | 20/65 [00:21<00:49,  1.09s/it]

=======================================================
Question: What is the command to upload a spaCy pipeline to the Hugging Face Hub?

Answer: <think>

</think>

The command to upload a spaCy pipeline to the Hugging Face Hub is not explicitly provided in the given context. However, generally, you would use the `hf_hub_upload` command from the `transformers` library or the Hugging Face CLI. For specific spaCy pipeline uploads, you may need to follow the guidelines provided by Hugging Face and spaCy.
True answer: python -m spacy huggingface-hub push en_ner_fashion-0.0.0-py3-none-any.whl

 32%|███▏      | 21/65 [00:22<00:49,  1.13s/it]

=======================================================
Question: What is the time and memory complexity of the Nyströmformer's approximation of self-attention?

Answer: <think>

</think>

The Nyströmformer approximates self-attention by reducing the computational complexity. Its time complexity is O(n√k + n²), where n is the sequence length and k is the number of selected landmarks. The memory complexity is O(n√k), as it stores the selected landmarks and their interactions.
True answer: O(n)

 34%|███▍      | 22/65 [00:23<00:46,  1.08s/it]

=======================================================
Question: What is the goal of the Named Entity Recognition task in token classification?

Answer: <think>

</think>

The goal of the Named Entity Recognition (NER) task in token classification is to identify and classify named entities in text into predefined categories such as person, organization, location, date, or other relevant types.
True answer: The goal of the Named Entity Recognition task is to find the entities in a piece of text, such as person, location, or organization.

 35%|███▌      | 23/65 [00:24<00:40,  1.05it/s]

=======================================================
Question: What is the resolution of images used by the CLIPSeg model?

Answer: <think>

</think>

The provided information does not specify the resolution of images used by the CLIPSeg model.
True answer: 352 x 352 pixels

 37%|███▋      | 24/65 [00:25<00:41,  1.01s/it]

=======================================================
Question: What can you use Gradio for?

Answer: <think>

</think>

Gradio is a Python library used for quickly creating web interfaces for machine learning models, natural language processing tasks, and other types of data processing functions. It allows developers to create interactive demos and user interfaces with minimal code, making it easy to share and test models.
True answer: Create a demo for your machine learning model, share your machine learning model with others, and debug your model.

 38%|███▊      | 25/65 [00:26<00:47,  1.19s/it]

=======================================================
Question: What TensorFlow API function is used to load a saved tensor file?

Answer: <think>

</think>

The TensorFlow API function used to load a saved tensor file is `tf.load`. However, it's important to note that `tf.load` is not a standard TensorFlow function. If you are referring to loading a saved model, the function `tf.saved_model.load` is commonly used. If you are referring to loading a tensor from a file, you might be using `tf.io.read_file` combined with appropriate parsing functions. Please provide more context for a precise answer.
True answer: safetensors.tensorflow.load_file

 40%|████      | 26/65 [00:28<00:54,  1.40s/it]

=======================================================
Question: Where can you access the logs of your Endpoints in Hugging Face Endpoints?

Answer: <think>

</think>

The logs of your Endpoints in Hugging Face Endpoints can be accessed through the Hugging Face platform, specifically within the Endpoints section of your account. The exact location may vary slightly depending on the type of endpoint and the interface you are using, but generally, you can find logs by navigating to the specific endpoint and looking for a "Logs" or "Monitoring" tab. If you are using the Hugging Face Inference API, logs might be available via the API response or through the Hugging Face dashboard. For more detailed information, refer to the Hugging Face documentation or support resources.
True answer: In the "Logs" tab of your Endpoint through the UI.

 42%|████▏     | 27/65 [00:29<00:45,  1.20s/it]

=======================================================
Question: What is the latest task added to Hugging Face AutoTrain for Computer Vision?

Answer: <think>

</think>

The provided information does not specify the latest task added to Hugging Face AutoTrain for Computer Vision.
True answer: Image Classification

 43%|████▎     | 28/65 [00:30<00:39,  1.06s/it]

=======================================================
Question: What is the default repository type created by the `create_repo` function on Hugging Face Hub?

Answer: <think>

</think>

The default repository type created by the `create_repo` function on Hugging Face Hub is a "model" repository.
True answer: model

 45%|████▍     | 29/65 [00:30<00:33,  1.09it/s]

=======================================================
Question: How many splits does the "duorc" dataset have?

Answer: <think>

</think>

The question cannot be answered definitively based on the provided information.
True answer: Six

 46%|████▌     | 30/65 [00:32<00:35,  1.01s/it]

=======================================================
Question: What is the purpose of Fully Sharded Data Parallel (FSDP) in distributed training?

Answer: <think>

</think>

The purpose of Fully Sharded Data Parallel (FSDP) in distributed training is to enable efficient and scalable training of large machine learning models by sharding both the model parameters and gradients across multiple devices, thereby reducing memory usage and improving computational efficiency.
True answer: FSDP is developed for distributed training of large pretrained models up to 1T parameters by sharding the model parameters, gradients, and optimizer states across data parallel processes.

 48%|████▊     | 31/65 [00:32<00:32,  1.06it/s]

=======================================================
Question: What file format is used to save and store PyTorch model weights more securely than `.bin` files?

Answer: <think>

</think>

The file format used to save and store PyTorch model weights more securely than `.bin` files is `.pt` or `.pth`.
True answer: `.safetensors`

 49%|████▉     | 32/65 [00:33<00:28,  1.18it/s]

=======================================================
Question: What type of security certification does Hugging Face have?

Answer: <think>

</think>

Hugging Face does not have a specific security certification mentioned in the provided documents.
True answer: SOC2 Type 2 certified

 51%|█████     | 33/65 [00:34<00:24,  1.31it/s]

=======================================================
Question: What do RAG models combine to generate outputs?

Answer: <think>

</think>

RAG models combine retrieval and generation to generate outputs.
True answer: Pretrained dense retrieval (DPR) and sequence-to-sequence models.

 52%|█████▏    | 34/65 [00:34<00:23,  1.34it/s]

=======================================================
Question: What library does MarkupLMFeatureExtractor use to extract data from HTML and XML files?

Answer: <think>

</think>

The provided information does not specify which library MarkupLMFeatureExtractor uses to extract data from HTML and XML files.
True answer: Beautiful Soup

 54%|█████▍    | 35/65 [00:35<00:21,  1.38it/s]

=======================================================
Question: What is the file size limit for syncing to HF Spaces without using Git-LFS?

Answer: <think>

</think>

The file size limit for syncing to HF Spaces without using Git-LFS is 5 GB.
True answer: 10MB

 55%|█████▌    | 36/65 [00:36<00:21,  1.37it/s]

=======================================================
Question: What is the title of the paper introducing the ByT5 model?

Answer: <think>

</think>

The title of the paper introducing the ByT5 model is "ByT5: Towards a Universal Neural Machine Translation System".
True answer: ByT5: Towards a token-free future with pre-trained byte-to-byte models

 57%|█████▋    | 37/65 [00:36<00:19,  1.41it/s]

=======================================================
Question: What is the dimension of the feature vector for the base BERT model?

Answer: <think>

</think>

The dimension of the feature vector for the base BERT model is 768.
True answer: 768

 58%|█████▊    | 38/65 [00:37<00:18,  1.43it/s]

=======================================================
Question: What special identifier does the WordPiece Model use for continuing subwords?

Answer: <think>

</think>

The WordPiece model uses the special identifier "##" for continuing subwords.
True answer: ##

 60%|██████    | 39/65 [00:38<00:23,  1.10it/s]

=======================================================
Question: What is the purpose of the 🧨 Diffusers tutorials?

Answer: <think>

</think>

The purpose of the 🧨 Diffusers tutorials is to provide guidance and instructions on using the Hugging Face Diffusers library, which is designed for working with diffusion models in machine learning. These tutorials likely cover topics such as model loading, training, inference, and customization, helping users to effectively utilize diffusion models for various tasks like image generation, text-to-image synthesis, and more.
True answer: To provide a gentle introduction to diffusion models and help understand the library fundamentals.

 62%|██████▏   | 40/65 [00:39<00:21,  1.18it/s]

=======================================================
Question: What is the default setting for the `allow_flagging` parameter in Gradio's `Interface`?

Answer: <think>

</think>

The default setting for the `allow_flagging` parameter in Gradio's `Interface` is `False`.
True answer: "manual"

 63%|██████▎   | 41/65 [00:40<00:19,  1.26it/s]

=======================================================
Question: Where can the full code for the Stable Diffusion demo be found?

Answer: <think>

</think>

The full code for the Stable Diffusion demo can be found on the official GitHub repository.
True answer: https://hf.co/spaces/stabilityai/stable-diffusion/tree/main

 65%|██████▍   | 42/65 [00:40<00:17,  1.31it/s]

=======================================================
Question: What transformation does the FNet model use to replace the self-attention layer in a BERT model?

Answer: <think>

</think>

The FNet model replaces the self-attention layer in a BERT model with a Fourier transform.
True answer: Fourier transform

 66%|██████▌   | 43/65 [00:41<00:15,  1.39it/s]

=======================================================
Question: What type of test should typically accompany a bug fix in Gradio's testing strategy?

Answer: <think>

</think>

The question cannot be answered definitively based on the provided information.
True answer: Dynamic code test

 68%|██████▊   | 44/65 [00:42<00:18,  1.12it/s]

=======================================================
Question: How can you force mixed precision training when initializing the Accelerator in 🤗 Accelerate?

Answer: <think>

</think>

To force mixed precision training when initializing the Accelerator in 🤗 Accelerate, set the `mixed_precision` argument to `"fp16"` or `"bf16"` when creating the Accelerator instance. For example:

```python
from accelerate import Accelerator

accelerator = Accelerator(mixed_precision="fp16")
```
True answer: By passing `fp16=True` to the Accelerator init.

 69%|██████▉   | 45/65 [00:44<00:19,  1.02it/s]

=======================================================
Question: What is the purpose of tokenizers in the NLP pipeline?

Answer: <think>

</think>

The purpose of tokenizers in the NLP pipeline is to split text into smaller units called tokens, which can be words, subwords, or characters. This process facilitates further processing such as stemming, lemmatization, and feature extraction, making it easier for models to understand and analyze the text.
True answer: To translate text into data that can be processed by the model.

 71%|███████   | 46/65 [00:44<00:17,  1.06it/s]

=======================================================
Question: What is the purpose of the Safety Checker in the Diffusers library?

Answer: <think>

</think>

The purpose of the Safety Checker in the Diffusers library is to ensure that generated outputs adhere to safety and ethical guidelines by filtering out potentially harmful or inappropriate content.
True answer: The Safety Checker checks and compares the class probability of a set of hard-coded harmful concepts in the embedding space against an image after it has been generated to mitigate the risk of generating harmful content.

 72%|███████▏  | 47/65 [00:45<00:16,  1.10it/s]

=======================================================
Question: What Python class allows you to retrieve Discussions and Pull Requests from a given repository on the Hugging Face Hub?

Answer: <think>

</think>

The Python class that allows you to retrieve Discussions and Pull Requests from a given repository on the Hugging Face Hub is `RetrieverTool`.
True answer: HfApi

 74%|███████▍  | 48/65 [00:46<00:13,  1.22it/s]

=======================================================
Question: What is the name of the new library introduced by Hugging Face for hosting scikit-learn models?

Answer: <think>

</think>

The question cannot be answered definitively based on the provided information.
True answer: Skops

 75%|███████▌  | 49/65 [00:47<00:14,  1.11it/s]

=======================================================
Question: What is the purpose of Textual Inversion?

Answer: <think>

</think>

The purpose of Textual Inversion is to enable the generation of custom images based on specific text prompts by learning and encoding the semantic meaning of a text phrase into a neural network. This allows the model to generate images that are consistent with the given text description.
True answer: Textual Inversion is a training method for personalizing models by learning new text embeddings from a few example images.

 77%|███████▋  | 50/65 [00:48<00:16,  1.08s/it]

=======================================================
Question: What is the recommended multiple of batch size for fp16 data type on an A100 GPU?

Answer: <think>

</think>

The recommended multiple of batch size for fp16 data type on an A100 GPU is typically 2x to 4x the batch size used for fp32, depending on the specific model and workload. This is due to the reduced memory footprint and increased throughput of fp16 precision. However, the exact recommended multiple may vary and should be determined through experimentation and profiling.
True answer: 64

 78%|███████▊  | 51/65 [00:50<00:18,  1.35s/it]

=======================================================
Question: How do you run a Gradio Blocks app in reload mode using a Python IDE?

Answer: <think>

</think>

To run a Gradio Blocks app in reload mode using a Python IDE, you can use the `launch` method with the `reload` parameter set to `True`. For example:

```python
import gradio as gr

def greet(name):
    return "Hello " + name

demo = gr.Blocks()
with demo:
    gr.Textbox(label="Name")
    gr.Button("Greet").click(fn=greet, inputs="Name", outputs="Text")

demo.launch(reload=True)
```

This will enable the app to automatically reload when changes are made to the code.
True answer: Run `gradio run.py` in the terminal.

 80%|████████  | 52/65 [00:51<00:15,  1.22s/it]

=======================================================
Question: How can you install the Hugging Face Unity API in your Unity project?

Answer: <think>

</think>

The question cannot be answered definitively based on the provided information. The supporting documents or context necessary to explain how to install the Hugging Face Unity API in a Unity project are not available.
True answer: To install the Hugging Face Unity API in your Unity project, go to `Window` -> `Package Manager`, click `+` and select `Add Package from git URL`, then enter `https://github.com/huggingface/unity-api.git`.

 82%|████████▏ | 53/65 [00:52<00:14,  1.19s/it]

=======================================================
Question: What is the pretraining objective of the Wav2Vec2 context network?

Answer: <think>

</think>

The pretraining objective of the Wav2Vec2 context network is to predict the masked audio segments from the surrounding context. This is achieved through a contrastive learning approach, where the model learns to distinguish between the correct audio segment and a set of negative samples.
True answer: The pretraining objective of the Wav2Vec2 context network is a contrastive task where the model has to predict the true quantized speech representation of the masked prediction from a set of false ones.

 83%|████████▎ | 54/65 [00:53<00:11,  1.01s/it]

=======================================================
Question: What is the default checkpoint used by the sentiment analysis pipeline in the Transformers library?

Answer: <think>

</think>

The question cannot be answered definitively based on the provided information.
True answer: distilbert base uncased finetuned sst2 english

 85%|████████▍ | 55/65 [00:54<00:10,  1.02s/it]

=======================================================
Question: What is the purpose of the notebook "How to use DeepSpeed to train models with billions of parameters on Habana Gaudi"?

Answer: <think>

</think>

The purpose of the notebook "How to use DeepSpeed to train models with billions of parameters on Habana Gaudi" is to provide guidance and code examples for leveraging DeepSpeed to train large-scale models on the Habana Gaudi platform.
True answer: To show how to use DeepSpeed to pre-train/fine-tune the 1.6B-parameter GPT2-XL for causal language modeling on Habana Gaudi.

 86%|████████▌ | 56/65 [00:55<00:08,  1.09it/s]

=======================================================
Question: What command line module does PyTorch provide to run a script on multiple GPUs?

Answer: <think>

</think>

PyTorch provides the `torch.distributed` module to run a script on multiple GPUs.
True answer: torchrun

 88%|████████▊ | 57/65 [00:56<00:07,  1.05it/s]

=======================================================
Question: What is the most popular vision transformer model on the Hugging Face Model Hub for image classification?

Answer: <think>

</think>

The most popular vision transformer model on the Hugging Face Model Hub for image classification is not explicitly stated in the provided documents. Additional information or a direct query to the Hugging Face Model Hub would be required to determine the most popular model.
True answer: google/vit-base-patch16-224

 89%|████████▉ | 58/65 [00:57<00:06,  1.07it/s]

=======================================================
Question: What is the command to upload an ESPnet model to a Hugging Face repository?

Answer: <think>

</think>

The command to upload an ESPnet model to a Hugging Face repository is not explicitly provided in the given documents. Therefore, it cannot be answered definitively based on the available information.
True answer: ./run.sh --stage 15 --skip_upload_hf false --hf_repo username/model_repo

 91%|█████████ | 59/65 [00:57<00:05,  1.12it/s]

=======================================================
Question: What file should be added to a model repository to install custom Python dependencies for Inference Endpoints?

Answer: <think>

</think>

The file that should be added to a model repository to install custom Python dependencies for Inference Endpoints is `requirements.txt`.
True answer: requirements.txt

 92%|█████████▏| 60/65 [00:59<00:05,  1.02s/it]

=======================================================
Question: How many images are needed to teach new concepts to Stable Diffusion using Textual Inversion?

Answer: <think>

</think>

The number of images needed to teach new concepts to Stable Diffusion using Textual Inversion can vary depending on the complexity of the concept and the desired quality of the generated images. However, it is generally recommended to use at least 100 images to effectively train the model and capture the nuances of the new concept.
True answer: 3-5 images

 94%|█████████▍| 61/65 [01:00<00:03,  1.03it/s]

=======================================================
Question: What is the maximum size of a model checkpoint before it is automatically sharded in Transformers version 4.18.0?

Answer: <think>

</think>

The maximum size of a model checkpoint before it is automatically sharded in Transformers version 4.18.0 is 10 GB.
True answer: 10GB

 95%|█████████▌| 62/65 [01:01<00:03,  1.04s/it]

=======================================================
Question: What is the purpose of Weights and Biases (W&B) for data scientists and machine learning scientists?

Answer: <think>

</think>

The purpose of Weights and Biases (W&B) for data scientists and machine learning scientists is to track, visualize, and manage experiments, models, and data. It helps in monitoring training processes, comparing different model versions, and collaborating effectively by providing a centralized platform for logging and analyzing machine learning workflows.
True answer: To track their machine learning experiments at every stage, from training to production.

 97%|█████████▋| 63/65 [01:02<00:01,  1.07it/s]

=======================================================
Question: What is the name of the open-source library created by Hugging Face to simplify Transformer acceleration?

Answer: <think>

</think>

The open-source library created by Hugging Face to simplify Transformer acceleration is called "Accelerate."
True answer: Optimum

 98%|█████████▊| 64/65 [01:02<00:00,  1.15it/s]

=======================================================
Question: What parameter is used to ensure that elements in a row have the same height in Gradio?

Answer: <think>

</think>

The parameter used to ensure that elements in a row have the same height in Gradio is `equal_height`.
True answer: equal_height

100%|██████████| 65/65 [01:03<00:00,  1.02it/s]

=======================================================
Question: What is the command to install the latest version of Optimum with OpenVINO support?

Answer: <think>

</think>

The command to install the latest version of Optimum with OpenVINO support is:

```bash
pip install optimum[openvino]
```
True answer: pip install --upgrade-strategy eager optimum["openvino"]

In [58]:
##### using vanilla LLM to answer questions

answer_llm = OpenAIServerModel(
    model_id=models[4],
    api_base="https://helmholtz-blablador.fz-juelich.de:8000/v1",
    api_key=Blablador_API_KEY,
    # flatten_messages_as_text=True,
    temperature=0.6)

outputs_standard = []

for example in tqdm(eval_dataset):
    question = example["question"]

    prompt = f"""Answer the following question as clearly and concisely as possible.
Use your own knowledge to respond.
If the question is ambiguous or cannot be answered definitively, state so clearly.

Question:
{question}

"""
    messages = [{"role": "user", "content": prompt}]
    answer = answer_llm.generate(messages).content

    print("=======================================================")
    print(f"Question: {question}")
    print(f"Answer: {answer}")
    print(f'True answer: {example["answer"]}')

    results_llm = {
        "question": question,
        "true_answer": example["answer"],
        "source_doc": example["source_doc"],
        "generated_answer": answer,
    }
    outputs_standard.append(results_llm)
    # time.sleep(5)

  2%|▏         | 1/65 [00:01<01:31,  1.42s/it]

=======================================================
Question: What architecture is the `tokenizers-linux-x64-musl` binary designed for?

Answer: <think>

</think>

The `tokenizers-linux-x64-musl` binary is designed for the x86-64 (also called AMD64) architecture. The "x64" in the name indicates this architecture, and "musl" refers to the C library used, not the CPU architecture.
True answer: x86_64-unknown-linux-musl

  3%|▎         | 2/65 [00:02<01:19,  1.26s/it]

=======================================================
Question: What is the purpose of the BLIP-Diffusion model?

Answer: <think>

</think>

The purpose of the BLIP-Diffusion model is to generate high-quality images based on textual descriptions by combining the capabilities of the BLIP (Bootstrapping Language-Image Pretraining) model with diffusion models. It enables more accurate and context-aware image generation from text.
True answer: The BLIP-Diffusion model is designed for controllable text-to-image generation and editing.

  5%|▍         | 3/65 [00:03<01:20,  1.29s/it]

=======================================================
Question: How can a user claim authorship of a paper on the Hugging Face Hub?

Answer: <think>

</think>

A user can claim authorship of a paper on the Hugging Face Hub by adding themselves as an author in the paper's metadata. This can be done through the Hugging Face Hub interface when creating or editing a paper. The user must have the necessary permissions to edit the paper, and they can update the author list in the paper's details section.
True answer: By clicking their name on the corresponding Paper page and clicking "claim authorship", then confirming the request in paper settings for admin team validation.

  6%|▌         | 4/65 [00:04<01:12,  1.19s/it]

=======================================================
Question: What is the purpose of the /healthcheck endpoint in the Datasets server API?

Answer: <think>

</think>

The purpose of the /healthcheck endpoint in the Datasets server API is to verify that the server is running and responsive. It typically returns a simple status code (like 200 OK) to indicate that the service is healthy and available for use.
True answer: Ensure the app is running

  8%|▊         | 5/65 [00:05<00:59,  1.00it/s]

=======================================================
Question: What is the default context window size for Local Attention in the LongT5 model?

Answer: <think>

</think>

The default context window size for Local Attention in the LongT5 model is 1024 tokens.
True answer: 127 tokens

  9%|▉         | 6/65 [00:06<00:58,  1.01it/s]

=======================================================
Question: What method is used to load a checkpoint for a task using `AutoPipeline`?

Answer: <think>

</think>

The method used to load a checkpoint for a task using `AutoPipeline` is typically `from_pretrained()`. This method loads the pre-trained model and its associated configuration, allowing the pipeline to perform the specified task.
True answer: from_pretrained()

 11%|█         | 7/65 [00:07<01:02,  1.08s/it]

=======================================================
Question: What is the purpose of Diffusers library?

Answer: <think>

</think>

The purpose of the Diffusers library is to provide a flexible and efficient framework for working with diffusion models, which are a type of generative AI model used for tasks like image generation, text-to-image synthesis, and other creative applications. It offers tools for training, fine-tuning, and deploying diffusion models, as well as pre-trained models for immediate use.
True answer: To serve as a modular toolbox for both inference and training of state-of-the-art pretrained diffusion models across multiple modalities.

 12%|█▏        | 8/65 [00:08<00:57,  1.01s/it]

=======================================================
Question: What method does the EulerAncestralDiscreteScheduler use for sampling?

Answer: <think>

</think>

The EulerAncestralDiscreteScheduler uses the Euler method for sampling, which is a numerical method for solving differential equations. It is adapted for use in diffusion models to generate samples efficiently.
True answer: Ancestral sampling with Euler method steps.

 14%|█▍        | 9/65 [00:09<00:55,  1.00it/s]

=======================================================
Question: What is the name of the large multimodal model that can solve image-text tasks and is based on Flamingo?

Answer: <think>

</think>

The large multimodal model based on Flamingo that can solve image-text tasks is called **Flamingo**. It was developed by Google Research and is designed to handle a variety of image-text understanding and generation tasks.
True answer: IDEFICS

 15%|█▌        | 10/65 [00:11<01:03,  1.15s/it]

=======================================================
Question: What is the purpose of the `gradio.Blocks` API?

Answer: <think>

</think>

The purpose of the `gradio.Blocks` API is to provide a flexible and customizable way to build complex, interactive web interfaces for machine learning models and other applications. It allows developers to define the layout and behavior of UI components (like buttons, text inputs, and image displays) using a more programmatic and structured approach compared to the simpler `gradio.Interface` API.
True answer: The `gradio.Blocks` API allows you to have full control over the data flows and layout of your application, enabling the building of complex, multi-step applications.

 17%|█▋        | 11/65 [00:12<01:09,  1.28s/it]

=======================================================
Question: What is the purpose of the two-stage model proposed in the paper "Hierarchical Text-Conditional Image Generation with CLIP Latents"?

Answer: <think>

</think>

The purpose of the two-stage model in the paper "Hierarchical Text-Conditional Image Generation with CLIP Latents" is to generate high-quality images conditioned on text by first generating a latent representation of the image using a pre-trained CLIP model, and then refining this representation to produce the final image. This approach leverages the semantic understanding of CLIP to improve the alignment between the generated images and the input text.
True answer: The purpose of the two-stage model is to generate a CLIP image embedding given a text caption and then generate an image conditioned on the image embedding.

 18%|█▊        | 12/65 [00:13<01:03,  1.19s/it]

=======================================================
Question: What command is used to install the requirements for a research project using 🤗 Transformers?

Answer: <think>

</think>

The command used to install the requirements for a research project using 🤗 Transformers is:

```bash
pip install -r requirements.txt
```

This assumes that the project's dependencies are listed in a file named `requirements.txt`.
True answer: pip install -r requirements.txt

 20%|██        | 13/65 [00:14<01:02,  1.20s/it]

=======================================================
Question: What task does the `roberta-large-mnli` checkpoint perform?

Answer: <think>

</think>

The `roberta-large-mnli` checkpoint is used for natural language inference (NLI) tasks. It is trained on the Multi-Genre Natural Language Inference (MNLI) dataset and can determine the relationship between two sentences, such as whether one entails, contradicts, or is neutral with respect to the other.
True answer: Text classification

 22%|██▏       | 14/65 [00:15<00:53,  1.05s/it]

=======================================================
Question: What service is replacing the Paid tier of the Inference API at Hugging Face?

Answer: <think>

</think>

The service replacing the Paid tier of the Inference API at Hugging Face is **Hugging Face Inference Endpoints**.
True answer: Inference Endpoints

 23%|██▎       | 15/65 [00:16<00:47,  1.05it/s]

=======================================================
Question: What architectural feature does SqueezeBERT use instead of fully-connected layers for the Q, K, V, and FFN layers?

Answer: <think>

</think>

SqueezeBERT uses convolutional layers instead of fully-connected layers for the Q, K, V, and FFN layers.
True answer: Grouped convolutions

 25%|██▍       | 16/65 [00:17<00:43,  1.13it/s]

=======================================================
Question: What type of license is the HuggingFace Team's software distributed under?

Answer: <think>

</think>

The HuggingFace Team's software, including the Hugging Face Transformers library, is distributed under the Apache 2.0 license.
True answer: Apache License, Version 2.0

 26%|██▌       | 17/65 [00:18<00:47,  1.02it/s]

=======================================================
Question: What are the two parameter-reduction techniques proposed in the ALBERT model to lower memory consumption and increase training speed?

Answer: <think>

</think>

The two parameter-reduction techniques proposed in the ALBERT model are:

1. **Shared Parameter Embedding** – Sharing the same parameter matrix between the input and output layers of the model.
2. **Factorized Embedding Parameterization** – Separating the vocabulary size and embedding dimension to reduce the number of parameters.
True answer: Splitting the embedding matrix into two smaller matrices and using repeating layers split among groups.

 28%|██▊       | 18/65 [00:20<00:56,  1.21s/it]

=======================================================
Question: What are the three main steps for fine-tuning a model with the 🤗 Datasets library?

Answer: <think>

</think>

The three main steps for fine-tuning a model with the 🤗 Datasets library are:

1. **Load and preprocess the dataset**: Use the `load_dataset` function to load your data and apply any necessary transformations or tokenization.

2. **Tokenize the data**: Convert the text data into input tensors that the model can process using a tokenizer from the Transformers library.

3. **Train the model**: Use the `Trainer` class from the Transformers library to fine-tune the model on your dataset.
True answer: 1. Load a dataset from the Hugging Face Hub. 2. Preprocess the data with `Dataset.map()`. 3. Load and compute metrics.

 29%|██▉       | 19/65 [00:21<00:58,  1.27s/it]

=======================================================
Question: What is the maximum improvement in throughput achieved by Hugging Face Infinity compared to vanilla transformers?

Answer: <think>

</think>

The maximum improvement in throughput achieved by Hugging Face Infinity compared to vanilla transformers is not publicly specified with a definitive numerical value. Hugging Face Infinity is designed to optimize inference throughput, but the exact percentage or factor of improvement can vary depending on the model, hardware, and workload. Therefore, a precise figure cannot be provided without specific benchmarking data.
True answer: +800%

 31%|███       | 20/65 [00:23<01:09,  1.55s/it]

=======================================================
Question: What is the command to upload a spaCy pipeline to the Hugging Face Hub?

Answer: <think>

</think>

The command to upload a spaCy pipeline to the Hugging Face Hub is not a built-in command in spaCy itself. However, you can save the pipeline locally and then use the Hugging Face CLI or API to upload it. Here's a general approach:

1. Save the spaCy model locally:
```python
import spacy
nlp = spacy.load("en_core_web_sm")
nlp.to_disk("path/to/model")
```

2. Use the Hugging Face CLI to upload:
```bash
huggingface-cli login
huggingface-cli upload <repo-name> path/to/model
```

You need to create a repository on the Hugging Face Hub first and ensure the model is properly formatted.
True answer: python -m spacy huggingface-hub push en_ner_fashion-0.0.0-py3-none-any.whl

 32%|███▏      | 21/65 [00:24<01:04,  1.48s/it]

=======================================================
Question: What is the time and memory complexity of the Nyströmformer's approximation of self-attention?

Answer: <think>

</think>

The Nyströmformer approximates self-attention by sampling a subset of the keys and queries, leading to a time complexity of **O(n√n)** and a memory complexity of **O(n√n)**, where **n** is the sequence length. This is more efficient than the standard self-attention's **O(n²)** time and memory complexity.
True answer: O(n)

 34%|███▍      | 22/65 [00:25<00:55,  1.29s/it]

=======================================================
Question: What is the goal of the Named Entity Recognition task in token classification?

Answer: <think>

</think>

The goal of the Named Entity Recognition (NER) task in token classification is to identify and classify named entities in text into predefined categories such as person, organization, location, date, or quantity.
True answer: The goal of the Named Entity Recognition task is to find the entities in a piece of text, such as person, location, or organization.

 35%|███▌      | 23/65 [00:26<00:52,  1.24s/it]

=======================================================
Question: What is the resolution of images used by the CLIPSeg model?

Answer: <think>

</think>

The CLIPSeg model does not have a fixed image resolution requirement, but it is typically used with images resized to 512x512 pixels. This resolution is common for many vision models, but the exact input size may vary depending on the implementation and specific use case.
True answer: 352 x 352 pixels

 37%|███▋      | 24/65 [00:27<00:47,  1.15s/it]

=======================================================
Question: What can you use Gradio for?

Answer: <think>

</think>

Gradio is a Python library used to quickly create web interfaces for machine learning models, APIs, and other functions. It allows users to build interactive demos where users can input data and see model outputs in a simple, browser-based interface.
True answer: Create a demo for your machine learning model, share your machine learning model with others, and debug your model.

 38%|███▊      | 25/65 [00:29<00:57,  1.43s/it]

=======================================================
Question: What TensorFlow API function is used to load a saved tensor file?

Answer: <think>

</think>

The TensorFlow API function used to load a saved tensor file is `tf.io.load_op_library` or `tf.saved_model.load`, depending on the context. However, if referring to loading a file saved with `tf.saved_model.save`, the correct function is `tf.saved_model.load`. For loading a tensor file (e.g., a `.npy` file), TensorFlow does not have a specific built-in function, but you can use `np.load` from NumPy.

If you are referring to loading a TensorFlow checkpoint file, the function is `tf.train.load_checkpoint`.

Please clarify the type of file you are trying to load for a more precise answer.
True answer: safetensors.tensorflow.load_file

 40%|████      | 26/65 [00:30<00:49,  1.28s/it]

=======================================================
Question: Where can you access the logs of your Endpoints in Hugging Face Endpoints?

Answer: <think>

</think>

You can access the logs of your Endpoints in Hugging Face via the Hugging Face Hub website. Navigate to the specific endpoint, and then go to the "Logs" tab to view the logs.
True answer: In the "Logs" tab of your Endpoint through the UI.

 42%|████▏     | 27/65 [00:32<00:47,  1.26s/it]

=======================================================
Question: What is the latest task added to Hugging Face AutoTrain for Computer Vision?

Answer: <think>

</think>

The latest task added to Hugging Face AutoTrain for Computer Vision is **Image Classification**. However, it's important to note that Hugging Face continuously updates its platform, and new tasks may have been added after this information was last updated. For the most current details, please check the official Hugging Face AutoTrain documentation or release notes.
True answer: Image Classification

 43%|████▎     | 28/65 [00:33<00:45,  1.24s/it]

=======================================================
Question: What is the default repository type created by the `create_repo` function on Hugging Face Hub?

Answer: <think>

</think>

The `create_repo` function on Hugging Face Hub creates a repository with a default type of "model" if no type is specified. However, the exact default can depend on the context and the API being used. For the Hugging Face Hub's official API, the default repository type is "model".
True answer: model

 45%|████▍     | 29/65 [00:33<00:37,  1.05s/it]

=======================================================
Question: How many splits does the "duorc" dataset have?

Answer: <think>

</think>

The "duorc" dataset has two splits: "train" and "test".
True answer: Six

 46%|████▌     | 30/65 [00:34<00:36,  1.05s/it]

=======================================================
Question: What is the purpose of Fully Sharded Data Parallel (FSDP) in distributed training?

Answer: <think>

</think>

The purpose of Fully Sharded Data Parallel (FSDP) in distributed training is to enable efficient training of large machine learning models across multiple devices by sharding the model's parameters, gradients, and optimizer states across devices, thereby reducing memory usage and improving scalability.
True answer: FSDP is developed for distributed training of large pretrained models up to 1T parameters by sharding the model parameters, gradients, and optimizer states across data parallel processes.

 48%|████▊     | 31/65 [00:35<00:35,  1.05s/it]

=======================================================
Question: What file format is used to save and store PyTorch model weights more securely than `.bin` files?

Answer: <think>

</think>

PyTorch model weights are more securely stored using the `.pt` or `.pth` file formats. These formats can include additional metadata and are typically used with PyTorch's `torch.save()` function, offering more flexibility and security compared to plain `.bin` files.
True answer: `.safetensors`

 49%|████▉     | 32/65 [00:37<00:39,  1.21s/it]

=======================================================
Question: What type of security certification does Hugging Face have?

Answer: <think>

</think>

Hugging Face, as a company, does not publicly disclose a specific type of security certification (such as ISO 27001, SOC 2, or GDPR compliance) in a standardized way. However, they emphasize security and compliance in their practices, particularly for their platforms like Hugging Face Hub and Inference API.

For the most accurate and up-to-date information, it is best to consult Hugging Face's official documentation or contact their support team directly.
True answer: SOC2 Type 2 certified

 51%|█████     | 33/65 [00:38<00:37,  1.19s/it]

=======================================================
Question: What do RAG models combine to generate outputs?

Answer: <think>

</think>

RAG (Retrieval-Augmented Generation) models combine **information retrieval** and **language generation** to generate outputs. They retrieve relevant information from a external knowledge source and use it to enhance the accuracy and relevance of the generated text.
True answer: Pretrained dense retrieval (DPR) and sequence-to-sequence models.

 52%|█████▏    | 34/65 [00:39<00:31,  1.02s/it]

=======================================================
Question: What library does MarkupLMFeatureExtractor use to extract data from HTML and XML files?

Answer: <think>

</think>

MarkupLMFeatureExtractor uses the **BeautifulSoup** library to extract data from HTML and XML files.
True answer: Beautiful Soup

 54%|█████▍    | 35/65 [00:39<00:27,  1.10it/s]

=======================================================
Question: What is the file size limit for syncing to HF Spaces without using Git-LFS?

Answer: <think>

</think>

The file size limit for syncing to HF Spaces without using Git-LFS is 5 GB.
True answer: 10MB

 55%|█████▌    | 36/65 [00:40<00:24,  1.18it/s]

=======================================================
Question: What is the title of the paper introducing the ByT5 model?

Answer: <think>

</think>

The title of the paper introducing the ByT5 model is "ByT5: Towards a Universal Text-to-Text Transformer."
True answer: ByT5: Towards a token-free future with pre-trained byte-to-byte models

 57%|█████▋    | 37/65 [00:41<00:21,  1.28it/s]

=======================================================
Question: What is the dimension of the feature vector for the base BERT model?

Answer: <think>

</think>

The dimension of the feature vector for the base BERT model is 768.
True answer: 768

 58%|█████▊    | 38/65 [00:42<00:24,  1.11it/s]

=======================================================
Question: What special identifier does the WordPiece Model use for continuing subwords?

Answer: <think>

</think>

The WordPiece model uses the special identifier `##` to denote continuing subwords. For example, the word "playing" might be split into "play" and "##ing", where "##ing" indicates that it is a continuation of the previous subword.
True answer: ##

 60%|██████    | 39/65 [00:43<00:24,  1.06it/s]

=======================================================
Question: What is the purpose of the 🧨 Diffusers tutorials?

Answer: <think>

</think>

The purpose of the 🧨 Diffusers tutorials is to guide users in understanding and using the Hugging Face Diffusers library, which provides tools for working with diffusion models, particularly for tasks like image generation, text-to-image synthesis, and other generative AI applications.
True answer: To provide a gentle introduction to diffusion models and help understand the library fundamentals.

 62%|██████▏   | 40/65 [00:44<00:21,  1.16it/s]

=======================================================
Question: What is the default setting for the `allow_flagging` parameter in Gradio's `Interface`?

Answer: <think>

</think>

The default setting for the `allow_flagging` parameter in Gradio's `Interface` is `False`.
True answer: "manual"

 63%|██████▎   | 41/65 [00:45<00:21,  1.11it/s]

=======================================================
Question: Where can the full code for the Stable Diffusion demo be found?

Answer: <think>

</think>

The full code for the Stable Diffusion demo can be found on GitHub. The official repository is hosted at: [https://github.com/CompVis/stable-diffusion](https://github.com/CompVis/stable-diffusion).
True answer: https://hf.co/spaces/stabilityai/stable-diffusion/tree/main

 65%|██████▍   | 42/65 [00:45<00:18,  1.22it/s]

=======================================================
Question: What transformation does the FNet model use to replace the self-attention layer in a BERT model?

Answer: <think>

</think>

The FNet model replaces the self-attention layer in a BERT model with a Fourier transform.
True answer: Fourier transform

 66%|██████▌   | 43/65 [00:46<00:19,  1.11it/s]

=======================================================
Question: What type of test should typically accompany a bug fix in Gradio's testing strategy?

Answer: <think>

</think>

In Gradio's testing strategy, a bug fix should typically be accompanied by a regression test. This ensures that the fix does not introduce new issues and that the specific problem is prevented from recurring. Unit tests or integration tests may also be used depending on the nature of the bug.
True answer: Dynamic code test

 68%|██████▊   | 44/65 [00:48<00:23,  1.10s/it]

=======================================================
Question: How can you force mixed precision training when initializing the Accelerator in 🤗 Accelerate?

Answer: <think>

</think>

You can force mixed precision training when initializing the Accelerator by setting the `mixed_precision` argument to `"fp16"` or `"bf16"`, depending on your hardware and requirements. For example:

```python
from accelerate import Accelerator

accelerator = Accelerator(mixed_precision="fp16")
```

This enables mixed precision training, using half-precision (FP16) or brain floating point (BF16) where possible.
True answer: By passing `fp16=True` to the Accelerator init.

 69%|██████▉   | 45/65 [00:49<00:22,  1.14s/it]

=======================================================
Question: What is the purpose of tokenizers in the NLP pipeline?

Answer: <think>

</think>

The purpose of tokenizers in the NLP pipeline is to split text into smaller units called tokens, such as words, subwords, or characters, which can then be processed by other NLP models or algorithms. This step is essential for converting raw text into a format that can be analyzed or understood by machine learning systems.
True answer: To translate text into data that can be processed by the model.

 71%|███████   | 46/65 [00:50<00:20,  1.09s/it]

=======================================================
Question: What is the purpose of the Safety Checker in the Diffusers library?

Answer: <think>

</think>

The purpose of the Safety Checker in the Diffusers library is to filter out potentially harmful or inappropriate content generated by machine learning models, such as text-to-image generators. It helps ensure that the outputs comply with safety and content policies.
True answer: The Safety Checker checks and compares the class probability of a set of hard-coded harmful concepts in the embedding space against an image after it has been generated to mitigate the risk of generating harmful content.

 72%|███████▏  | 47/65 [00:51<00:20,  1.12s/it]

=======================================================
Question: What Python class allows you to retrieve Discussions and Pull Requests from a given repository on the Hugging Face Hub?

Answer: <think>

</think>

The Python class that allows you to retrieve Discussions and Pull Requests from a given repository on the Hugging Face Hub is `HfApi` from the `huggingface_hub` library. You can use methods like `list_repo_discussions` and `list_repo_pull_requests` on an instance of this class.
True answer: HfApi

 74%|███████▍  | 48/65 [00:53<00:21,  1.25s/it]

=======================================================
Question: What is the name of the new library introduced by Hugging Face for hosting scikit-learn models?

Answer: <think>

</think>

The new library introduced by Hugging Face for hosting scikit-learn models is called **Hugging Face Transformers**. However, it's worth noting that the Transformers library primarily focuses on deep learning models, not scikit-learn models. Hugging Face does not have a specific library solely for hosting scikit-learn models.
True answer: Skops

 75%|███████▌  | 49/65 [00:54<00:20,  1.25s/it]

=======================================================
Question: What is the purpose of Textual Inversion?

Answer: <think>

</think>

The purpose of Textual Inversion is to encode specific visual concepts (such as an object, style, or person) into a textual embedding, allowing them to be generated or modified in text-to-image synthesis models. It enables users to customize and control the generation process by incorporating new or specific concepts into the model's understanding.
True answer: Textual Inversion is a training method for personalizing models by learning new text embeddings from a few example images.

 77%|███████▋  | 50/65 [00:56<00:19,  1.31s/it]

=======================================================
Question: What is the recommended multiple of batch size for fp16 data type on an A100 GPU?

Answer: <think>

</think>

The recommended multiple of batch size for fp16 data type on an A100 GPU is typically 2x or 4x the batch size used with fp32, depending on the specific model and memory constraints. This is because fp16 uses half the memory of fp32, allowing for larger batches. However, the exact multiple can vary based on the application and framework being used.
True answer: 64

 78%|███████▊  | 51/65 [00:58<00:22,  1.59s/it]

=======================================================
Question: How do you run a Gradio Blocks app in reload mode using a Python IDE?

Answer: <think>

</think>

To run a Gradio Blocks app in reload mode using a Python IDE, you can use the `launch()` method with the `reload` parameter set to `True`. For example:

```python
import gradio as gr

def greet(name):
    return f"Hello {name}!"

demo = gr.Blocks()
with demo:
    gr.Textbox(label="Name")
    gr.Button("Greet").click(fn=greet, inputs="name", outputs="text")

demo.launch(reload=True)
```

In most Python IDEs (like PyCharm, VS Code, etc.), this will enable auto-reloading of the app when code changes are detected. Note that reload mode may not work in all environments, especially in some notebook interfaces.
True answer: Run `gradio run.py` in the terminal.

 80%|████████  | 52/65 [01:01<00:25,  1.97s/it]

=======================================================
Question: How can you install the Hugging Face Unity API in your Unity project?

Answer: <think>

</think>

The Hugging Face Unity API is not a standard or officially recognized package, and there is no official "Hugging Face Unity API" that can be installed in a Unity project. However, you can integrate Hugging Face models into Unity by using HTTP requests to Hugging Face's Inference API or by using third-party tools and plugins that facilitate this integration.

To use Hugging Face models in Unity, you can:

1. **Use Hugging Face Inference API**: Send requests to Hugging Face's hosted models via HTTP (e.g., using `UnityWebRequest` or `HttpClient` in C#).
2. **Use a Third-Party Plugin**: Some community-developed plugins or packages may simplify the integration of Hugging Face models into Unity.
3. **Export Models Locally**: Use tools like ONNX or TensorFlow to export models and run them in Unity with appropriate inference engines.

If you have a specific plugin or tool in mind, please provide more details for a more accurate answer.
True answer: To install the Hugging Face Unity API in your Unity project, go to `Window` -> `Package Manager`, click `+` and select `Add Package from git URL`, then enter `https://github.com/huggingface/unity-api.git`.

 82%|████████▏ | 53/65 [01:02<00:21,  1.76s/it]

=======================================================
Question: What is the pretraining objective of the Wav2Vec2 context network?

Answer: <think>

</think>

The pretraining objective of the Wav2Vec2 context network is to predict the masked speech units (similar to words or subwords) from the surrounding context. This is done by training the model to reconstruct the masked parts of the input based on the unmasked parts, using a self-supervised approach. This helps the model learn meaningful representations of speech.
True answer: The pretraining objective of the Wav2Vec2 context network is a contrastive task where the model has to predict the true quantized speech representation of the masked prediction from a set of false ones.

 83%|████████▎ | 54/65 [01:03<00:17,  1.63s/it]

=======================================================
Question: What is the default checkpoint used by the sentiment analysis pipeline in the Transformers library?

Answer: <think>

</think>

The Transformers library does not specify a single "default" checkpoint for the sentiment analysis pipeline. However, by default, it uses the `distilbert-base-uncased-finetuned-sst-2-english` model, which is fine-tuned for sentiment analysis on the SST-2 dataset. This model is the standard default for the pipeline when no specific model is specified.
True answer: distilbert base uncased finetuned sst2 english

 85%|████████▍ | 55/65 [01:05<00:15,  1.55s/it]

=======================================================
Question: What is the purpose of the notebook "How to use DeepSpeed to train models with billions of parameters on Habana Gaudi"?

Answer: <think>

</think>

The purpose of the notebook "How to use DeepSpeed to train models with billions of parameters on Habana Gaudi" is to provide guidance and code examples for efficiently training large-scale machine learning models on Habana Gaudi accelerators using the DeepSpeed library. It aims to demonstrate optimization techniques for handling billion-parameter models, leveraging both DeepSpeed's features and the capabilities of Gaudi hardware.
True answer: To show how to use DeepSpeed to pre-train/fine-tune the 1.6B-parameter GPT2-XL for causal language modeling on Habana Gaudi.

 86%|████████▌ | 56/65 [01:06<00:13,  1.47s/it]

=======================================================
Question: What command line module does PyTorch provide to run a script on multiple GPUs?

Answer: <think>

</think>

PyTorch provides the `torch.distributed` module to run a script on multiple GPUs. Additionally, the `torch.nn.DataParallel` or `torch.nn.parallel.DistributedDataParallel` classes can be used to utilize multiple GPUs for training. However, for more advanced and efficient multi-GPU training, `torch.distributed` is the recommended approach.
True answer: torchrun

 88%|████████▊ | 57/65 [01:07<00:11,  1.44s/it]

=======================================================
Question: What is the most popular vision transformer model on the Hugging Face Model Hub for image classification?

Answer: <think>

</think>

The most popular vision transformer model on the Hugging Face Model Hub for image classification is **"google/vit-base-patch16-224"**. It is widely used and has the highest number of downloads and stars for image classification tasks. However, popularity can vary over time, so it's a good idea to check the Hugging Face Model Hub directly for the latest information.
True answer: google/vit-base-patch16-224

 89%|████████▉ | 58/65 [01:10<00:12,  1.74s/it]

=======================================================
Question: What is the command to upload an ESPnet model to a Hugging Face repository?

Answer: <think>

</think>

The command to upload an ESPnet model to a Hugging Face repository is not directly provided by ESPnet, but you can use the `huggingface_hub` library. Typically, you would first save your model in a format compatible with Hugging Face (e.g., using `transformers` or `peft`), then use the following command:

```bash
huggingface-cli login
```

Then, after preparing your model and tokenizer in a directory, run:

```bash
huggingface-cli upload <repo-name> <local-folder>
```

Replace `<repo-name>` with your Hugging Face repository name and `<local-folder>` with the path to your model files. Note that ESPnet models may need to be converted or adapted for use with Hugging Face.
True answer: ./run.sh --stage 15 --skip_upload_hf false --hf_repo username/model_repo

 91%|█████████ | 59/65 [01:11<00:09,  1.53s/it]

=======================================================
Question: What file should be added to a model repository to install custom Python dependencies for Inference Endpoints?

Answer: <think>

</think>

The file that should be added to a model repository to install custom Python dependencies for Inference Endpoints is `requirements.txt`. This file lists all the Python packages required for the model to run, and it is used during the deployment process to install the dependencies.
True answer: requirements.txt

 92%|█████████▏| 60/65 [01:12<00:07,  1.42s/it]

=======================================================
Question: How many images are needed to teach new concepts to Stable Diffusion using Textual Inversion?

Answer: <think>

</think>

Textual Inversion in Stable Diffusion typically requires a relatively small number of images—often between 50 to 100—to effectively learn and represent new concepts. The exact number can vary depending on the complexity of the concept and the desired quality of the generated images.
True answer: 3-5 images

 94%|█████████▍| 61/65 [01:13<00:04,  1.22s/it]

=======================================================
Question: What is the maximum size of a model checkpoint before it is automatically sharded in Transformers version 4.18.0?

Answer: <think>

</think>

The maximum size of a model checkpoint before it is automatically sharded in Transformers version 4.18.0 is **5GB**.
True answer: 10GB

 95%|█████████▌| 62/65 [01:14<00:03,  1.20s/it]

=======================================================
Question: What is the purpose of Weights and Biases (W&B) for data scientists and machine learning scientists?

Answer: <think>

</think>

The purpose of Weights and Biases (W&B) is to help data scientists and machine learning scientists track, visualize, and manage experiments, models, and datasets throughout the machine learning lifecycle. It enables better collaboration, reproducibility, and optimization of machine learning projects.
True answer: To track their machine learning experiments at every stage, from training to production.

 97%|█████████▋| 63/65 [01:15<00:02,  1.05s/it]

=======================================================
Question: What is the name of the open-source library created by Hugging Face to simplify Transformer acceleration?

Answer: <think>

</think>

The open-source library created by Hugging Face to simplify Transformer acceleration is called **Transformers**.
True answer: Optimum

 98%|█████████▊| 64/65 [01:15<00:00,  1.06it/s]

=======================================================
Question: What parameter is used to ensure that elements in a row have the same height in Gradio?

Answer: <think>

</think>

The parameter used to ensure that elements in a row have the same height in Gradio is `equal_height`.
True answer: equal_height

100%|██████████| 65/65 [01:16<00:00,  1.18s/it]

=======================================================
Question: What is the command to install the latest version of Optimum with OpenVINO support?

Answer: <think>

</think>

The command to install the latest version of Optimum with OpenVINO support is:

```bash
pip install optimum[openvino]
```
True answer: pip install --upgrade-strategy eager optimum["openvino"]

In [59]:
EVALUATION_PROMPT = """You are a fair evaluator language model.

You will be given an instruction, a response to evaluate, a reference answer that gets a score of 3, and a score rubric representing a evaluation criteria are given.
1. Write a detailed feedback that assess the quality of the response strictly based on the given score rubric, not evaluating in general.
2. After writing a feedback, write a score that is an integer between 1 and 3. You should refer to the score rubric.
3. The output format should look as follows: \"Feedback: {{write a feedback for criteria}} [RESULT] {{an integer number between 1 and 3}}\"
4. Please do not generate any other opening, closing, and explanations. Be sure to include [RESULT] in your output.
5. Do not score conciseness: a correct answer that covers the question should receive max score, even if it contains additional useless information.

The instruction to evaluate:
{instruction}

Response to evaluate:
{response}

Reference Answer (Score 3):
{reference_answer}

Score Rubrics:
[Is the response complete, accurate, and factual based on the reference answer?]
Score 1: The response is completely incomplete, inaccurate, and/or not factual.
Score 2: The response is somewhat complete, accurate, and/or factual.
Score 3: The response is completely complete, accurate, and/or factual.

Feedback:"""

In [74]:
import pandas as pd

evaluation_llm = OpenAIServerModel(
    # model_id="gemini-2.5-flash-preview-04-17",
    model_id="gemini-2.0-flash",
    api_base="https://generativelanguage.googleapis.com/v1beta/openai/",
    api_key="AIzaSyBWnnT_Vj030zlQxUD4_b50l5UTZlXjOXQ",
    temperature=0)

results = {}
for system_type, outputs in [
    ("agentic_rag", outputs_agentic_rag),
    ("standard_rag", outputs_standard_rag),
    ("standard", outputs_standard),
]:
    print("evaluating {}".format(system_type))

    for experiment in tqdm(outputs):
        eval_prompt = EVALUATION_PROMPT.format(
            instruction=experiment["question"],
            response=experiment["generated_answer"],
            reference_answer=experiment["true_answer"],
        )
        messages = [
            {
                "role": "system",
                "content": "You are a fair evaluator language model."
            },
            {
                "role": "user",
                "content": eval_prompt
            },
        ]

        eval_result = evaluation_llm.generate(messages).content

        try:
            feedback, score = [
                item.strip() for item in eval_result.split("[RESULT]")
            ]
            experiment["eval_score_LLM_judge"] = score
            experiment["eval_feedback_LLM_judge"] = feedback
        except:
            print(f"Parsing failed - output was: {eval_result}")

        time.sleep(5)

    results[system_type] = pd.DataFrame.from_dict(outputs)
    results[system_type] = results[
        system_type].loc[~results[system_type]["generated_answer"].str.
                         contains("Error", na=False)]

evaluating agentic_rag

  0%|          | 0/65 [00:00<?, ?it/s]

100%|██████████| 65/65 [06:12<00:00,  5.73s/it]

evaluating standard_rag

100%|██████████| 65/65 [06:15<00:00,  5.77s/it]

evaluating standard

100%|██████████| 65/65 [06:19<00:00,  5.83s/it]

In [77]:
DEFAULT_SCORE = 2  # Give average score whenever scoring fails


def fill_score(x):
    try:
        return int(x)
    except:
        return DEFAULT_SCORE


for system_type, outputs in [
    ("agentic_rag", outputs_agentic_rag),
    ("standard_rag", outputs_standard_rag),
    ("standard", outputs_standard),
]:

    results[system_type]["eval_score_LLM_judge_int"] = (
        results[system_type]["eval_score_LLM_judge"].fillna(
            DEFAULT_SCORE).apply(fill_score))
    results[system_type]["eval_score_LLM_judge_int"] = (
        results[system_type]["eval_score_LLM_judge_int"] - 1) / 2

    print(
        f"Average score for {system_type} : {results[system_type]['eval_score_LLM_judge_int'].mean()*100:.1f}%"
    )

Average score for agentic_rag : 86.9%
Average score for standard_rag : 47.7%
Average score for standard : 57.7%

In [64]:
results["agentic_rag"]

,question,true_answer,source_doc,generated_answer,eval_score_LLM_judge,eval_feedback_LLM_judge,eval_score_LLM_judge_int
0,What architecture is the `tokenizers-linux-x64...,x86_64-unknown-linux-musl,huggingface/tokenizers/blob/main/bindings/node...,x86_64-unknown-linux-musl,3,"The response is completely complete, accurate,...",1.0
1,What is the purpose of the BLIP-Diffusion mode...,The BLIP-Diffusion model is designed for contr...,huggingface/diffusers/blob/main/docs/source/en...,The BLIP-Diffusion model is likely designed fo...,2,The response provides a reasonable inference a...,0.5
2,How can a user claim authorship of a paper on ...,By clicking their name on the corresponding Pa...,huggingface/hub-docs/blob/main/docs/hub/paper-...,A user can claim authorship of a paper on the ...,3,The response accurately describes the process ...,1.0
3,What is the purpose of the /healthcheck endpoi...,Ensure the app is running,huggingface/datasets-server/blob/main/services...,The purpose of the /healthcheck endpoint in th...,3,The response accurately and completely describ...,1.0
4,What is the default context window size for Lo...,127 tokens,huggingface/transformers/blob/main/docs/source...,512,1,"The response provides a numerical value, but i...",0.0
...,...,...,...,...,...,...,...
60,What is the maximum size of a model checkpoint...,10GB,huggingface/transformers/blob/main/docs/source...,10GB,3,The response accurately and completely answers...,1.0
61,What is the purpose of Weights and Biases (W&B...,To track their machine learning experiments at...,gradio-app/gradio/blob/main/guides/06_integrat...,Weights and Biases (W&B) is a platform for tra...,3,The response accurately describes the purpose ...,1.0
62,What is the name of the open-source library cr...,Optimum,huggingface/blog/blob/main/intel.md,Optimum,3,"The response ""Optimum"" is a complete and accur...",1.0
63,What parameter is used to ensure that elements...,equal_height,gradio-app/gradio/blob/main/guides/cn/03_build...,equal_height,3,The response accurately identifies the paramet...,1.0
64,What is the command to install the latest vers...,"pip install --upgrade-strategy eager optimum[""...",huggingface/diffusers/blob/main/docs/source/en...,pip install --upgrade-strategy eager optimum[o...,2,The response is almost identical to the refere...,0.5

In [73]:
prob = pd.DataFrame.from_dict(outputs_standard_rag)
prob

,question,true_answer,source_doc,generated_answer
0,What architecture is the `tokenizers-linux-x64...,x86_64-unknown-linux-musl,huggingface/tokenizers/blob/main/bindings/node...,<think>\n\n</think>\n\nThe `tokenizers-linux-x...
1,What is the purpose of the BLIP-Diffusion mode...,The BLIP-Diffusion model is designed for contr...,huggingface/diffusers/blob/main/docs/source/en...,<think>\n\n</think>\n\nThe purpose of the BLIP...
2,How can a user claim authorship of a paper on ...,By clicking their name on the corresponding Pa...,huggingface/hub-docs/blob/main/docs/hub/paper-...,<think>\n\n</think>\n\nTo claim authorship of ...
3,What is the purpose of the /healthcheck endpoi...,Ensure the app is running,huggingface/datasets-server/blob/main/services...,<think>\n\n</think>\n\nThe purpose of the /hea...
4,What is the default context window size for Lo...,127 tokens,huggingface/transformers/blob/main/docs/source...,<think>\n\n</think>\n\nThe provided informatio...
...,...,...,...,...
60,What is the maximum size of a model checkpoint...,10GB,huggingface/transformers/blob/main/docs/source...,<think>\n\n</think>\n\nThe maximum size of a m...
61,What is the purpose of Weights and Biases (W&B...,To track their machine learning experiments at...,gradio-app/gradio/blob/main/guides/06_integrat...,<think>\n\n</think>\n\nThe purpose of Weights ...
62,What is the name of the open-source library cr...,Optimum,huggingface/blog/blob/main/intel.md,<think>\n\n</think>\n\nThe open-source library...
63,What parameter is used to ensure that elements...,equal_height,gradio-app/gradio/blob/main/guides/cn/03_build...,<think>\n\n</think>\n\nThe parameter used to e...
64,What is the command to install the latest vers...,"pip install --upgrade-strategy eager optimum[""...",huggingface/diffusers/blob/main/docs/source/en...,<think>\n\n</think>\n\nThe command to install ...

In [65]:
results["standard_rag"]

KeyError: 'standard_rag'

In [23]:
# save all results
import json

# Create a dictionary of JSON strings
json_results = {}

for system_type, df in results.items():
    json_results[system_type] = json.loads(df.to_json(orient='records'))

# Save to a file
with open('.//results//Qwen3-30B-A3B.json', 'w') as f:
    json.dump(json_results, f, indent=4)

In [ ]:
# load results
import json
import pandas as pd

# Read the JSON file
with open('.//results//gemini-2.5-flash-preview-04-17.json', 'r') as f:
    loaded_json = json.load(f)

# Convert back to a dictionary of DataFrames
loaded_results = {}
for system_type, records in loaded_json.items():
    loaded_results[system_type] = pd.DataFrame.from_records(records)

results = loaded_results