In [ ]:
from huggingface_hub import notebook_login

notebook_login()

In [46]:
import os
import datasets
import logging
import json
import threading
import time
import pandas as pd
from concurrent.futures import ThreadPoolExecutor
from dotenv import load_dotenv
from langchain.docstore.document import Document
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_community.vectorstores.utils import DistanceStrategy
from langchain_core.vectorstores import VectorStore
from smolagents import OpenAIServerModel, CodeAgent, Tool
from smolagents.monitoring import LogLevel
from transformers import AutoTokenizer
from tqdm import tqdm
from typing import List, Optional
from utils.blablador import Models

In [ ]:
## old vector creator
def sanitize_filename(dataset_name):
    """Convert dataset name to a valid filename by replacing '/' with '_'"""
    return dataset_name.replace("/", "_")


def load_or_create_vectordb(dataset_name):
    """Load existing vectordb or create new one if it doesn't exist"""

    # Create sanitized filename
    safe_filename = sanitize_filename(dataset_name)
    vectordb_path = os.path.join("vectordb", safe_filename)

    # Check if vectordb already exists
    if os.path.exists(vectordb_path):
        print(f"Found existing vector database at {vectordb_path}")
        print("Loading existing vector database...")

        # Load the embedding model (needed for loading)
        embedding_model = HuggingFaceEmbeddings(
            model_name="thenlper/gte-small")

        # Load the existing vectordb
        vectordb = FAISS.load_local(vectordb_path,
                                    embedding_model,
                                    allow_dangerous_deserialization=True)
        print("Vector database loaded successfully!")
        return vectordb

    else:
        print(f"No existing vector database found at {vectordb_path}")
        print("Creating new vector database...")

        # Load and process the dataset
        knowledge_base = datasets.load_dataset(dataset_name, split="train")
        source_docs = [
            Document(page_content=doc["text"],
                     metadata={"source": doc["source"].split("/")[1]})
            for doc in knowledge_base
        ]

        # Initialize text splitter
        text_splitter = RecursiveCharacterTextSplitter.from_huggingface_tokenizer(
            AutoTokenizer.from_pretrained("thenlper/gte-small"),
            chunk_size=200,
            chunk_overlap=20,
            add_start_index=True,
            strip_whitespace=True,
            separators=["\n\n", "\n", ".", " ", ""],
        )

        # Split docs and keep only unique ones
        print("Splitting documents...")
        docs_processed = []
        unique_texts = {}
        for doc in tqdm(source_docs):
            new_docs = text_splitter.split_documents([doc])
            for new_doc in new_docs:
                if new_doc.page_content not in unique_texts:
                    unique_texts[new_doc.page_content] = True
                    docs_processed.append(new_doc)

        print("Embedding documents...")
        embedding_model = HuggingFaceEmbeddings(
            model_name="thenlper/gte-small")
        vectordb = FAISS.from_documents(
            documents=docs_processed,
            embedding=embedding_model,
            distance_strategy=DistanceStrategy.COSINE,
        )

        # Save the vectordb
        print(f"Saving vector database to {vectordb_path}...")
        vectordb.save_local(vectordb_path)
        print("Vector database saved successfully!")

        return vectordb


# Usage
dataset_name = "m-ric/huggingface_doc"
vectordb = load_or_create_vectordb(dataset_name)

print(f"Vector database ready with {vectordb.index.ntotal} vectors!")

In [2]:
## Load or create vector database parallelly


def sanitize_filename(dataset_name: str) -> str:
    """Convert dataset name to a valid filename by replacing '/' with '_'"""
    return dataset_name.replace("/", "_")


class DocumentProcessor:
    """Thread-safe document processor to avoid pickling issues"""

    def __init__(self, chunk_size: int = 200, chunk_overlap: int = 20):
        self.text_splitter = None
        self.chunk_size = chunk_size
        self.chunk_overlap = chunk_overlap
        self._lock = threading.Lock()

    def _get_text_splitter(self):
        """Initialize text splitter in thread-local manner"""
        if self.text_splitter is None:
            with self._lock:
                if self.text_splitter is None:
                    self.text_splitter = RecursiveCharacterTextSplitter.from_huggingface_tokenizer(
                        AutoTokenizer.from_pretrained("thenlper/gte-small"),
                        chunk_size=self.chunk_size,
                        chunk_overlap=self.chunk_overlap,
                        add_start_index=True,
                        strip_whitespace=True,
                        separators=["\n\n", "\n", ".", " ", ""],
                    )
        return self.text_splitter

    def split_documents_chunk(self,
                              docs_chunk: List[Document]) -> List[Document]:
        """Split a chunk of documents using the text splitter"""
        text_splitter = self._get_text_splitter()
        processed_docs = []
        for doc in docs_chunk:
            new_docs = text_splitter.split_documents([doc])
            processed_docs.extend(new_docs)
        return processed_docs


def parallel_document_splitting(
        source_docs: List[Document],
        max_workers: int = None,
        chunk_size: int = 100,
        text_chunk_size: int = 200,
        text_chunk_overlap: int = 20) -> List[Document]:
    """Split documents in parallel using ThreadPoolExecutor"""
    if max_workers is None:
        max_workers = min(8, len(source_docs) // chunk_size + 1)

    print(f"Splitting documents in parallel using {max_workers} threads...")

    # Split source_docs into chunks for parallel processing
    doc_chunks = [
        source_docs[i:i + chunk_size]
        for i in range(0, len(source_docs), chunk_size)
    ]

    # Create a shared processor instance with configurable chunk size
    processor = DocumentProcessor(text_chunk_size, text_chunk_overlap)

    # Use ThreadPoolExecutor instead of ProcessPoolExecutor
    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        # Process chunks in parallel with progress bar
        results = list(
            tqdm(executor.map(processor.split_documents_chunk, doc_chunks),
                 total=len(doc_chunks),
                 desc="Processing document chunks"))

    # Flatten results
    all_processed_docs = []
    for chunk_result in results:
        all_processed_docs.extend(chunk_result)

    return all_processed_docs


def remove_duplicates(docs: List[Document]) -> List[Document]:
    """Remove duplicate documents based on page_content"""
    print("Removing duplicate documents...")
    unique_texts = set()
    unique_docs = []

    for doc in tqdm(docs, desc="Checking for duplicates"):
        if doc.page_content not in unique_texts:
            unique_texts.add(doc.page_content)
            unique_docs.append(doc)

    print(f"Removed {len(docs) - len(unique_docs)} duplicate documents")
    return unique_docs


def batch_embed_documents(docs: List[Document],
                          embedding_model,
                          batch_size: int = 100) -> FAISS:
    """Create FAISS vectorstore with batch processing for embeddings"""
    print(f"Embedding documents in batches of {batch_size}...")

    if not docs:
        raise ValueError("No documents to embed")

    # Create initial vectorstore with first batch
    first_batch = docs[:batch_size]
    print(f"Creating initial vectorstore with {len(first_batch)} documents...")

    vectordb = FAISS.from_documents(
        documents=first_batch,
        embedding=embedding_model,
        distance_strategy=DistanceStrategy.COSINE,
    )

    # Process remaining documents in batches
    remaining_docs = docs[batch_size:]
    if remaining_docs:
        total_batches = (len(remaining_docs) + batch_size - 1) // batch_size

        for i in tqdm(range(0, len(remaining_docs), batch_size),
                      desc="Adding document batches",
                      total=total_batches):
            batch = remaining_docs[i:i + batch_size]

            # Create temporary vectorstore for this batch
            batch_vectordb = FAISS.from_documents(
                documents=batch,
                embedding=embedding_model,
                distance_strategy=DistanceStrategy.COSINE,
            )

            # Merge with main vectorstore
            vectordb.merge_from(batch_vectordb)

    return vectordb


def sequential_document_splitting(
        source_docs: List[Document],
        text_chunk_size: int = 200,  # Add this parameter
        text_chunk_overlap: int = 20) -> List[Document]:
    """Fallback sequential document splitting if parallel processing fails"""
    print("Using sequential document splitting...")

    text_splitter = RecursiveCharacterTextSplitter.from_huggingface_tokenizer(
        AutoTokenizer.from_pretrained("thenlper/gte-small"),
        chunk_size=text_chunk_size,
        chunk_overlap=text_chunk_overlap,
        add_start_index=True,
        strip_whitespace=True,
        separators=["\n\n", "\n", ".", " ", ""],
    )

    docs_processed = []
    for doc in tqdm(source_docs, desc="Splitting documents"):
        new_docs = text_splitter.split_documents([doc])
        docs_processed.extend(new_docs)

    return docs_processed


def load_or_create_vectordb(dataset_name: str,
                            batch_size: int = 100,
                            max_workers: int = None,
                            doc_chunk_size: int = 100,
                            text_chunk_size: int = 200,
                            text_chunk_overlap: int = 20,
                            force_rebuild: bool = False,
                            use_parallel: bool = True) -> FAISS:
    """Load existing vectordb or create new one with optimized processing"""

    # Create sanitized filename
    safe_filename = sanitize_filename(dataset_name)
    vectordb_path = os.path.join(
        "vectordb",
        f"{safe_filename}_{text_chunk_size}")  # Include chunk size in filename

    # Check if vectordb already exists and not forcing rebuild
    if os.path.exists(vectordb_path) and not force_rebuild:
        print(f"Found existing vector database at {vectordb_path}")
        print("Loading existing vector database...")

        try:
            # Load the embedding model (needed for loading)
            embedding_model = HuggingFaceEmbeddings(
                model_name="thenlper/gte-small")

            # Load the existing vectordb
            vectordb = FAISS.load_local(vectordb_path,
                                        embedding_model,
                                        allow_dangerous_deserialization=True)
            print("Vector database loaded successfully!")
            return vectordb

        except Exception as e:
            print(f"Error loading existing vectordb: {e}")
            print("Creating new vector database...")

    else:
        if force_rebuild:
            print("Force rebuild requested. Creating new vector database...")
        else:
            print(f"No existing vector database found at {vectordb_path}")
            print("Creating new vector database...")

    # Load and process the dataset
    print("Loading dataset...")
    knowledge_base = datasets.load_dataset(dataset_name, split="train")
    source_docs = [
        Document(page_content=doc["text"],
                 metadata={"source": doc["source"].split("/")[1]})
        for doc in tqdm(knowledge_base, desc="Processing dataset")
    ]

    print(f"Loaded {len(source_docs)} documents from dataset")

    # Split documents (with fallback to sequential processing)
    try:
        if use_parallel and len(source_docs) > 50:
            docs_processed = parallel_document_splitting(
                source_docs, max_workers, doc_chunk_size, text_chunk_size,
                text_chunk_overlap)
        else:
            docs_processed = sequential_document_splitting(
                source_docs, text_chunk_size, text_chunk_overlap)

    except Exception as e:
        print(f"Parallel processing failed: {e}")
        print("Falling back to sequential processing...")
        docs_processed = sequential_document_splitting(
            source_docs, text_chunk_size,
            text_chunk_overlap)  # Pass new parameters

    print(f"Split into {len(docs_processed)} document chunks")

    # Remove duplicates
    docs_processed = remove_duplicates(docs_processed)

    print(f"Final document count after deduplication: {len(docs_processed)}")

    # Create embedding model
    print("Loading embedding model...")
    embedding_model = HuggingFaceEmbeddings(model_name="thenlper/gte-small")

    # Create vectordb with batch processing
    vectordb = batch_embed_documents(docs_processed, embedding_model,
                                     batch_size)

    # Save the vectordb
    print(f"Saving vector database to {vectordb_path}...")
    try:
        vectordb.save_local(vectordb_path)
        print("Vector database saved successfully!")
    except Exception as e:
        print(f"Error saving vectordb: {e}")
        print("Continuing without saving...")

    return vectordb


# Usage example with configurable parameters
dataset_name = "m-ric/huggingface_doc"

# Usage example with configurable chunk sizes
config = {
    "batch_size": 50,
    "max_workers": 4,
    "doc_chunk_size": 100,  # Parallel processing batch size
    "text_chunk_size": 400,  # Document content chunk size (tokens) 
    "text_chunk_overlap": 40,  # Overlap between chunks
    "force_rebuild": False,
    "use_parallel": True
}

vectordb = load_or_create_vectordb(dataset_name, **config)

Found existing vector database at vectordb\m-ric_huggingface_doc_400
Loading existing vector database...

C:\Users\Philippe\AppData\Local\Temp\ipykernel_21164\866353223.py:185: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-huggingface package and should be used instead. To use it run `pip install -U :class:`~langchain-huggingface` and import as `from :class:`~langchain_huggingface import HuggingFaceEmbeddings``.
  embedding_model = HuggingFaceEmbeddings(

Vector database loaded successfully!

In [9]:
# Example of using the vectordb for similarity search
query = "How to use transformers?"
results = vectordb.similarity_search(query, k=5)
for i, result in enumerate(results):
    print(f"Result {i+1}: {result.page_content}")

Result 1: . We can use this model as we would any other Transformers model, for instance by loading it in a pipeline. Try the push_to_hub API on your next training to easily share your model with the rest of the world!
Result 2: How do Transformers work?[[how-do-transformers-work]]

<CourseFloatingBanner
    chapter={1}
    classNames="absolute z-10 right-0 top-0"
/>

In this section, we will take a high-level look at the architecture of Transformer models.

## A bit of Transformer history[[a-bit-of-transformer-history]]

Here are some reference points in the (short) history of Transformer models:

<div class="flex justify-center">
<img class="block dark:hidden" src="https://huggingface.co/datasets/huggingface-course/documentation-images/resolve/main/en/chapter1/transformers_chrono.svg" alt="A brief chronology of Transformers models.">
<img class="hidden dark:block" src="https://huggingface.co/datasets/huggingface-course/documentation-images/resolve/main/en/chapter1/transformers_chrono-dark.svg" alt="A brief chronology of Transformers models.">
</div>

The [Transformer architecture](https://arxiv.org/abs/1706.03762) was introduced in June 2017. The focus of the original research was on translation tasks. This was followed by the introduction of several influential models, including:

- **June 2018**: [GPT](https://cdn.openai.com/research-covers/language-unsupervised/language_understanding_paper.pdf), the first pretrained Transformer model, used for fine-tuning on various NLP tasks and obtained state-of-the-art results
Result 3: Transformers, what can they do?[[transformers-what-can-they-do]]

<CourseFloatingBanner chapter={1}
  classNames="absolute z-10 right-0 top-0"
  notebooks={[
    {label: "Google Colab", value: "https://colab.research.google.com/github/huggingface/notebooks/blob/master/course/en/chapter1/section3.ipynb"},
    {label: "Aws Studio", value: "https://studiolab.sagemaker.aws/import/github/huggingface/notebooks/blob/master/course/en/chapter1/section3.ipynb"},
]} />

In this section, we will look at what Transformer models can do and use our first tool from the 🤗 Transformers library: the `pipeline()` function.

<Tip>
👀 See that <em>Open in Colab</em> button on the top right? Click on it to open a Google Colab notebook with all the code samples of this section. This button will be present in any section containing code examples.

If you want to run the examples locally, we recommend taking a look at the <a href="/course/chapter0">setup</a>.
</Tip>

## Transformers are everywhere![[transformers-are-everywhere]]

Transformer models are used to solve all kinds of NLP tasks, like the ones mentioned in the previous section. Here are some of the companies and organizations using Hugging Face and Transformer models, who also contribute back to the community by sharing their models:
Result 4: In the following, we try to give you a general recipe that we found most
useful when porting a model to 🤗 Transformers.

The following list is a summary of everything that has to be done to add
a model and can be used by you as a To-Do List:

1.  [ ] (Optional) Understood theoretical aspects

2.  [ ] Prepared transformers dev environment

3.  [ ] Set up debugging environment of the original repository

4.  [ ] Created script that successfully runs forward pass using
    original repository and checkpoint

5.  [ ] Successfully opened a PR and added the model skeleton to Transformers

6.  [ ] Successfully converted original checkpoint to Transformers
    checkpoint

7.  [ ] Successfully ran forward pass in Transformers that gives
    identical output to original checkpoint

8.  [ ] Finished model tests in Transformers

9.  [ ] Successfully added Tokenizer in Transformers

10. [ ] Run end-to-end integration tests

11. [ ] Finished docs

12. [ ] Uploaded model weights to the hub

13. [ ] Submitted the pull request for review

14. [ ] (Optional) Added a demo notebook

To begin with, we usually recommend to start by getting a good
theoretical understanding of `[camelcase name of model]`. However, if you prefer to
understand the theoretical aspects of the model *on-the-job*, then it is
totally fine to directly dive into the `[camelcase name of model]`'s code-base. This
option might suit you better, if your engineering skills are better than
your theoretical skill, if you have trouble understanding
`[camelcase name of model]`'s paper, or if you just enjoy programming much more than
reading scientific papers.

### 1. (Optional) Theoretical aspects of [camelcase name of model]
Result 5: 1. 필요한 대로 모델이나 예시를 커스터마이즈하세요:
    - 우리는 저자가 공개한 결과를 재현하기 위해 각 모델 구조의 예시를 제공합니다.
    - 모델 내부 구조는 가능한 일관적으로 공개되어 있습니다.
    - 빠른 실험을 위해 모델 파일은 라이브러리와 독립적으로 사용될 수 있습니다.

## 왜 transformers를 사용하지 말아야 할까요?

In [3]:
class RetrieverTool(Tool):
    name = "retriever"
    description = """
    Retrieves relevant documents from the knowledge base using semantic similarity search.
    Choose k based on query complexity:
    - k=5-7: For standard questions needing some context  
    - k=8-10: For complex topics requiring multiple perspectives
    - k=10-13: For comprehensive research or broad exploration
    """

    # inputs = {
    #     "query": {
    #         "type":
    #         "string",
    #         "description":
    #         "The search query. Use descriptive keywords and phrases rather than questions. Example: 'machine learning algorithms' instead of 'what are ML algorithms?'",
    #     },
    #     "k": {
    #         "type": "integer",
    #         "description":
    #         "Number of documents to retrieve (3-10). Choose based on query complexity: 3 for standard questions, 5-7 for complex topics, 8-10 for comprehensive research. Default: 3 if not specified.",
    #         "nullable": True
    #     }
    # }
    inputs = {
        "query": {
            "type":
            "string",
            "description":
            "The search query. Use descriptive keywords and phrases rather than questions. Example: 'machine learning algorithms' instead of 'what are ML algorithms?'",
        },
        "k": {
            "type": "integer",
            "description":
            "Number of documents to retrieve (7-20). Start with 7, increase if no relevant information is found. Default: 7 if not specified.",
            "nullable": True
        }
    }
    output_type = "string"

    def __init__(self,
                 vectordb: VectorStore,
                 k: int = 7,
                 score_threshold: Optional[float] = None,
                 max_content_length: int = 10000,
                 **kwargs):
        super().__init__(**kwargs)
        self.vectordb = vectordb
        self.k = k
        self.score_threshold = score_threshold
        self.max_content_length = max_content_length
        self.logger = logging.getLogger(self.__class__.__name__)

    def forward(self, query: str, k: Optional[int] = None) -> str:
        # Input validation
        if not query or not isinstance(query, str) or not query.strip():
            return "Error: Query must be a non-empty string"

        # Parameter validation
        retrieval_k = k if k is not None else self.k
        if retrieval_k is not None and (not isinstance(retrieval_k, int) or
                                        retrieval_k < 3 or retrieval_k > 20):
            retrieval_k = self.k

        query = query.strip()

        try:
            # Try to get documents with scores if available
            if hasattr(self.vectordb, 'similarity_search_with_score'
                       ) and self.score_threshold is not None:
                docs_with_scores = self.vectordb.similarity_search_with_score(
                    query, k=retrieval_k)
                # Filter by score threshold
                filtered_docs = [
                    doc for doc, score in docs_with_scores
                    if score >= self.score_threshold
                ]
                docs = filtered_docs[:retrieval_k] if filtered_docs else []

                if not docs and docs_with_scores:
                    # If no docs meet threshold, take the best one anyway
                    docs = [docs_with_scores[0][0]]

            else:
                docs = self.vectordb.similarity_search(query, k=retrieval_k)

        except Exception as e:
            self.logger.error(f"Error during similarity search: {str(e)}")
            return f"Error retrieving documents: {str(e)}"

        # Handle no results
        if not docs:
            return f"No relevant documents found for query: '{query}'"

        # Format results
        return self._format_results(query, docs)

    def _format_results(self, query: str, docs) -> str:
        """Format the retrieved documents into a readable string."""
        result_parts = [
            f"Search Query: {query}",
            f"Retrieved {len(docs)} relevant document(s):", ""
        ]

        for i, doc in enumerate(docs, 1):
            # Add document header
            result_parts.append(f"=== Document {i} ===")

            # Add metadata if available
            if hasattr(doc, 'metadata') and doc.metadata:
                metadata_info = []
                if 'source' in doc.metadata:
                    metadata_info.append(f"Source: {doc.metadata['source']}")
                if 'title' in doc.metadata:
                    metadata_info.append(f"Title: {doc.metadata['title']}")
                if 'page' in doc.metadata:
                    metadata_info.append(f"Page: {doc.metadata['page']}")

                if metadata_info:
                    result_parts.append(" | ".join(metadata_info))

            # Add content (with truncation if needed)
            content = doc.page_content
            if len(content) > self.max_content_length:
                content = content[:self.max_content_length].rsplit(
                    ' ', 1)[0] + "... [truncated]"

            result_parts.append(content)
            result_parts.append("")  # Empty line between documents

        return "\n".join(result_parts).strip()

    def get_retrieval_stats(self) -> dict:
        """Get basic stats about the vector store if available."""
        try:
            # This depends on the vector store implementation
            if hasattr(self.vectordb, '__len__'):
                return {"total_documents": len(self.vectordb)}
            return {"status": "Vector store connected"}
        except Exception:
            return {"status": "Unable to retrieve stats"}

In [6]:
# old retriever tool
from smolagents import Tool
from langchain_core.vectorstores import VectorStore


class RetrieverTool(Tool):
    name = "retriever"
    description = "Using semantic similarity, retrieves some documents from the knowledge base that have the closest embeddings to the input query."
    inputs = {
        "query": {
            "type":
            "string",
            "description":
            "The query to perform. This should be semantically close to your target documents. Use the affirmative form rather than a question.",
        }
    }
    output_type = "string"

    def __init__(self, vectordb: VectorStore, **kwargs):
        super().__init__(**kwargs)
        self.vectordb = vectordb

    def forward(self, query: str) -> str:
        assert isinstance(query, str), "Your search query must be a string"

        docs = self.vectordb.similarity_search(
            query,
            k=7,
        )

        return "\nRetrieved documents:\n" + "".join([
            f"===== Document {str(i)} =====\n" + doc.page_content
            for i, doc in enumerate(docs)
        ])

In [56]:
# answer LLM model initialization

load_dotenv()
# model_name = "gemini-2.5-flash-preview-05-20"
model_name = "gemini-1.5-flash"

answer_llm = OpenAIServerModel(
    model_id=model_name,
    api_base="https://generativelanguage.googleapis.com/v1beta/openai/",
    api_key=os.getenv("Gemini_API_KEY2"),
    temperature=0.2)

# models = Models(api_key=Blablador_API_KEY).get_model_ids()

# answer_llm = OpenAIServerModel(
#     model_id=models[4],
#     api_base="https://helmholtz-blablador.fz-juelich.de:8000/v1",
#     api_key=Blablador_API_KEY,
#     flatten_messages_as_text=True,
#     temperature=0.2)

retriever_tool = RetrieverTool(vectordb)
# retriever_tool = RetrieverTool(vectordb, score_threshold=0.7)

agent = CodeAgent(
    tools=[retriever_tool],
    model=answer_llm,
    planning_interval=2,
    max_steps=30,
    verbosity_level=LogLevel.ERROR,
)

In [ ]:
agent_output = agent.run("How can I push a model to the Hub?")

print("Final output:")
print(agent_output)

In [6]:
eval_dataset = datasets.load_dataset("m-ric/huggingface_doc_qa_eval",
                                     split="train")

In [ ]:
inspect = eval_dataset.select([4])

print(inspect[0]["context"])

!--Copyright 2022 The HuggingFace Team. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
the License. You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.

⚠️ Note that this file is in Markdown but contain specific syntax for our doc-builder (similar to MDX) that may not be
rendered properly in your Markdown viewer.

-->

# LongT5

## Overview

The LongT5 model was proposed in [LongT5: Efficient Text-To-Text Transformer for Long Sequences](https://arxiv.org/abs/2112.07916)
by Mandy Guo, Joshua Ainslie, David Uthus, Santiago Ontanon, Jianmo Ni, Yun-Hsuan Sung and Yinfei Yang. It's an
encoder-decoder transformer pre-trained in a text-to-text denoising generative setting. LongT5 model is an extension of
T5 model, and it enables using one of the two different efficient attention mechanisms - (1) Local attention, or (2)
Transient-Global attention.


The abstract from the paper is the following:

*Recent work has shown that either (1) increasing the input length or (2) increasing model size can improve the
performance of Transformer-based neural models. In this paper, we present a new model, called LongT5, with which we
explore the effects of scaling both the input length and model size at the same time. Specifically, we integrated
attention ideas from long-input transformers (ETC), and adopted pre-training strategies from summarization pre-training
(PEGASUS) into the scalable T5 architecture. The result is a new attention mechanism we call {\em Transient Global}
(TGlobal), which mimics ETC's local/global attention mechanism, but without requiring additional side-inputs. We are
able to achieve state-of-the-art results on several summarization tasks and outperform the original T5 models on
question answering tasks.*

This model was contributed by [stancld](https://huggingface.co/stancld).
The original code can be found [here](https://github.com/google-research/longt5).

## Usage tips

- [`LongT5ForConditionalGeneration`] is an extension of [`T5ForConditionalGeneration`] exchanging the traditional
encoder *self-attention* layer with efficient either *local* attention or *transient-global* (*tglobal*) attention.
- Unlike the T5 model, LongT5 does not use a task prefix. Furthermore, it uses a different pre-training objective
inspired by the pre-training of [`PegasusForConditionalGeneration`].
- LongT5 model is designed to work efficiently and very well on long-range *sequence-to-sequence* tasks where the
input sequence exceeds commonly used 512 tokens. It is capable of handling input sequences of a length up to 16,384 tokens.
- For *Local Attention*, the sparse sliding-window local attention operation allows a given token to attend only `r`
tokens to the left and right of it (with `r=127` by default). *Local Attention* does not introduce any new parameters
to the model. The complexity of the mechanism is linear in input sequence length `l`: `O(l*r)`.
- *Transient Global Attention* is an extension of the *Local Attention*. It, furthermore, allows each input token to
interact with all other tokens in the layer. This is achieved via splitting an input sequence into blocks of a fixed
length `k` (with a default `k=16`). Then, a global token for such a block is obtained via summing and normalizing the embeddings of every token
in the block. Thanks to this, the attention allows each token to attend to both nearby tokens like in Local attention, and
also every global token like in the case of standard global attention (*transient* represents the fact the global tokens
are constructed dynamically within each attention operation).  As a consequence, *TGlobal* attention introduces
a few new parameters -- global relative position biases and a layer normalization for global token's embedding.
The complexity of this mechanism is `O(l(r + l/k))`.
- An example showing how to evaluate a fine-tuned LongT5 model on the [pubmed dataset](https://huggingface.co/datasets/scientific_papers) is below.

```python
>>> import evaluate
>>> from datasets import load_dataset
>>> from transformers import AutoTokenizer, LongT5ForConditionalGeneration

>>> dataset = load_dataset("scientific_papers", "pubmed", split="validation")
>>> model = (
...     LongT5ForConditionalGeneration.from_pretrained("Stancld/longt5-tglobal-large-16384-pubmed-3k_steps")
...     .to("cuda")
...     .half()
... )
>>> tokenizer = AutoTokenizer.from_pretrained("Stancld/longt5-tglobal-large-16384-pubmed-3k_steps")


>>> def generate_answers(batch):
...     inputs_dict = tokenizer(
...         batch["article"], max_length=16384, padding="max_length", truncation=True, return_tensors="pt"
...     )
...     input_ids = inputs_dict.input_ids.to("cuda")
...     attention_mask = inputs_dict.attention_mask.to("cuda")
...     output_ids = model.generate(input_ids, attention_mask=attention_mask, max_length=512, num_beams=2)
...     batch["predicted_abstract"] = tokenizer.batch_decode(output_ids, skip_special_tokens=True)
...     return batch


>>> result = dataset.map(generate_answer, batched=True, batch_size=2)
>>> rouge = evaluate.load("rouge")
>>> rouge.compute(predictions=result["predicted_abstract"], references=result["abstract"])
```


## Resources

- [Translation task guide](../tasks/translation)
- [Summarization task guide](../tasks/summarization)

## LongT5Config

[[autodoc]] LongT5Config

<frameworkcontent>
<pt>

## LongT5Model

[[autodoc]] LongT5Model
    - forward

## LongT5ForConditionalGeneration

[[autodoc]] LongT5ForConditionalGeneration
    - forward

## LongT5EncoderModel

[[autodoc]] LongT5EncoderModel
    - forward

</pt>
<jax>

## FlaxLongT5Model

[[autodoc]] FlaxLongT5Model
    - __call__
    - encode
    - decode

## FlaxLongT5ForConditionalGeneration

[[autodoc]] FlaxLongT5ForConditionalGeneration
    - __call__
    - encode
    - decode

</jax>
</frameworkcontent>

In [13]:
retriever_tool = RetrieverTool(vectordb, max_content_length=float('inf'))
print(
    retriever_tool(
        "The LongT5 model was proposed in [LongT5: Efficient Text-To-Text Transformer for Long Sequences]",
        k=3))

Search Query: The LongT5 model was proposed in [LongT5: Efficient Text-To-Text Transformer for Long Sequences]
Retrieved 3 relevant document(s):

=== Document 1 ===
Source: transformers
!--Copyright 2022 The HuggingFace Team. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
the License. You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.

⚠️ Note that this file is in Markdown but contain specific syntax for our doc-builder (similar to MDX) that may not be
rendered properly in your Markdown viewer.

-->

# LongT5

## Overview

The LongT5 model was proposed in [LongT5: Efficient Text-To-Text Transformer for Long Sequences](https://arxiv.org/abs/2112.07916)
by Mandy Guo, Joshua Ainslie, David Uthus, Santiago Ontanon, Jianmo Ni, Yun-Hsuan Sung and Yinfei Yang. It's an
encoder-decoder transformer pre-trained in a text-to-text denoising generative setting. LongT5 model is an extension of
T5 model, and it enables using one of the two different efficient attention mechanisms - (1) Local attention, or (2)
Transient-Global attention.


The abstract from the paper is the following:

=== Document 2 ===
Source: transformers
## Overview

The Longformer model was presented in [Longformer: The Long-Document Transformer](https://arxiv.org/pdf/2004.05150.pdf) by Iz Beltagy, Matthew E. Peters, Arman Cohan.

The abstract from the paper is the following:

*Transformer-based models are unable to process long sequences due to their self-attention operation, which scales
quadratically with the sequence length. To address this limitation, we introduce the Longformer with an attention
mechanism that scales linearly with sequence length, making it easy to process documents of thousands of tokens or
longer. Longformer's attention mechanism is a drop-in replacement for the standard self-attention and combines a local
windowed attention with a task motivated global attention. Following prior work on long-sequence transformers, we
evaluate Longformer on character-level language modeling and achieve state-of-the-art results on text8 and enwik8. In
contrast to most prior work, we also pretrain Longformer and finetune it on a variety of downstream tasks. Our
pretrained Longformer consistently outperforms RoBERTa on long document tasks and sets new state-of-the-art results on
WikiHop and TriviaQA.*

This model was contributed by [beltagy](https://huggingface.co/beltagy). The Authors' code can be found [here](https://github.com/allenai/longformer).

## Usage tips

=== Document 3 ===
Source: blog
Recently, long sequence modeling has experienced a surge of interest as can be seen by the many submissions from this year alone - [Beltagy et al. (2020)](https://arxiv.org/abs/2004.05150), [Roy et al. (2020)](https://arxiv.org/abs/2003.05997), [Tay et al.](https://arxiv.org/abs/2002.11296), [Wang et al.](https://arxiv.org/abs/2006.04768) to name  a few.
The motivation behind long sequence modeling is that many tasks in NLP, *e.g.* summarization, question answering, require the model to process longer input sequences than models, such as BERT, are able to handle. In tasks that require the model to process a large input sequence, long sequence models do not have to cut the input sequence to avoid memory overflow and thus have been shown to outperform standard "BERT"-like models *cf.* [Beltagy et al. (2020)](https://arxiv.org/abs/2004.05150).

The Reformer pushes the limit of longe sequence modeling by its ability to process up to half a million tokens at once as shown in this [demo](https://github.com/patrickvonplaten/notebooks/blob/master/PyTorch_Reformer.ipynb). As a comparison, a conventional `bert-base-uncased` model limits the input length to only 512 tokens. In Reformer, each part of the standard transformer architecture is re-engineered to optimize for minimal memory requirement without a significant drop in performance.

In [ ]:
##### Using agentic RAG to answer questions

outputs_agentic_rag = []

inspect = eval_dataset.select([20])
# inspect = eval_dataset.select([42, 43, 47, 49])
# inspect = eval_dataset.select([20])

for example in tqdm(inspect):
    question = example["question"]

    #     enhanced_question = f"""Using the information contained in your knowledge base, which you can access with the 'retriever' tool,
    # give a comprehensive answer to the question below.
    # Respond only to the question asked, response should be concise and relevant to the question.
    # If you cannot find information, do not give up and try calling your retriever again with different arguments!
    # Make sure to have covered the question completely by calling the retriever tool several times with semantically different queries.
    # Your queries should not be questions but affirmative form sentences: e.g. rather than "How do I load a model from the Hub in bf16?", query should be "load a model from the Hub bf16 weights".

    # Question:
    # {question}"""
    # enhanced_question = f"""Use the 'retriever' tool to find information and answer this question: {question}

    # Instructions:
    # - Search the knowledge base using relevant keywords (avoid using "hugging face" in search terms)
    # - Start with k=7, then try k=12, k=15, or k=20 if no relevant information is found
    # - Keep increasing the number of documents until you find the answer
    # - Try different search terms if initial results don't answer the question
    # - Don't stop until you have enough information to answer the question

    # """

    # enhanced_question = f"""Use the 'retriever' tool to find information and answer this question: {question}

    # REQUIRED SEARCH PATTERN:
    # 1. Search with k=7 using your best keywords
    # 2. If no relevant info found, search same keywords with k=10
    # 3. If still no relevant info, search same keywords with k=13
    # 4. If still no relevant info, try different keywords and repeat steps 1-3

    # SEARCH RULES:
    # - Use specific technical keywords
    # - Do NOT use "Hugging Face" in query
    # - Focus on the core concept/function/method being asked about
    # - Try different keyword combinations if first set doesn't work
    # - Don't stop until you find relevant information or exhaust keyword options

    # Start searching now with k=7.
    # """

    enhanced_question = f"""Use the 'retriever' tool to find information and answer this question: {question}

    SEARCH STRATEGY:
    1. Start with k=7 using your best keywords from the question
    2. If information is incomplete or irrelevant, retry with k=10 (same keywords)
    3. If the same documents are retrieved and information is still insufficient, try different keywords:
    - Use synonym words from the question to find different documents
    - Reduce keywords to search for broader documents
    - Use related concepts from previously retrieved documents
    4. Repeat steps 1-3 with new keyword combinations until you find the answer

    SEARCH RULES:
    - Do NOT include "Hugging Face" in queries (all questions relate to Hugging Face ecosystem)
    - The answer exists in the database - keep searching with different approaches
    - Try both specific and broad keyword strategies

    RESPONSE RULES:
    - Answer strictly based on retrieved documents, not prior knowledge
    - If answer is found: provide clear, direct response with relevant details
    - If answer not found: summarize the most relevant information retrieved

    Begin your search systematically.
    """

    answer = agent.run(enhanced_question)
    print("=======================================================")
    print(f"Question: {question}")
    print(f"Answer: {answer}")
    print(f'True answer: {example["answer"]}')

    results_agentic = {
        "question": question,
        "true_answer": example["answer"],
        "source_doc": example["source_doc"],
        "generated_answer": answer,
    }
    outputs_agentic_rag.append(results_agentic)
    # time.sleep(5)

In [121]:
with open("checkpoints/rag_checkpoint.json", 'r') as f:
    loaded_json = json.load(f)

# Convert back to a dictionary of DataFrames
# loaded_results = {}
# for system_type, records in loaded_json.items():
#     loaded_results[system_type] = pd.DataFrame.from_records(records)

In [57]:
## Set a checkpoint for query limitations (limited API) to use agentic RAG to answer questions


def run_agentic_rag_with_checkpointing(
        eval_dataset,
        agent,
        checkpoint_file="checkpoints/rag_checkpoint.json"):
    """
    Run agentic RAG with checkpointing to allow resuming from interruptions.
    
    Args:
        eval_dataset: Dataset containing questions and answers
        agent: The agent to run queries with
        checkpoint_file: File to store checkpointing information
    
    Returns:
        List of results from agentic RAG
    """
    outputs_agentic_rag = []
    start_idx = 0

    # Load checkpoint if exists
    if os.path.exists(checkpoint_file):
        try:
            with open(checkpoint_file, 'r') as f:
                checkpoint_data = json.load(f)
                outputs_agentic_rag = checkpoint_data.get('results', [])
                start_idx = checkpoint_data.get('next_idx', 0)
                print(
                    f"Resuming from checkpoint at index {start_idx} with {len(outputs_agentic_rag)} results already processed"
                )
        except Exception as e:
            print(f"Error loading checkpoint: {e}")
            print("Starting from beginning")

    # Create progress bar starting from checkpoint
    total_examples = len(eval_dataset)
    pbar = tqdm(total=total_examples, initial=start_idx)

    try:
        for idx in range(start_idx, total_examples):
            example = eval_dataset[idx]
            question = example["question"]

            enhanced_question = f"""Use the 'retriever' tool to find information and answer this question: {question}

            SEARCH STRATEGY:
            1. Start with k=7 using your best keywords from the question
            2. If information is incomplete or irrelevant, retry with k=10 (same keywords)
            3. If the same documents are retrieved and information is still insufficient, try different keywords:
            - Use synonym words from the question to find different documents
            - Reduce keywords to search for broader documents
            - Use related concepts from previously retrieved documents
            4. Repeat steps 1-3 with new keyword combinations until you find the answer

            SEARCH RULES:
            - Do NOT include "Hugging Face" in queries (all questions relate to Hugging Face ecosystem)
            - The answer exists in the database - keep searching with different approaches
            - Try both specific and broad keyword strategies

            RESPONSE RULES:
            - Answer strictly based on retrieved documents, not prior knowledge
            - If answer is found: provide clear, direct response with relevant details
            - If answer not found: summarize the most relevant information retrieved

            Begin your search systematically.
            """

            try:
                answer = agent.run(enhanced_question)

                print(
                    "=======================================================")
                print(f"Question: {question}")
                print(f"Answer: {answer}")
                print(f'True answer: {example["answer"]}')

                results_agentic = {
                    "question": question,
                    "true_answer": example["answer"],
                    "source_doc": example["source_doc"],
                    "generated_answer": answer,
                }

                outputs_agentic_rag.append(results_agentic)

                # Update checkpoint after each successful query
                save_checkpoint(checkpoint_file, outputs_agentic_rag, idx + 1)

                pbar.update(1)
                time.sleep(10)  # Rate limiting

            except Exception as e:
                print(f"Error processing example {idx}: {e}")
                # Save checkpoint before exiting
                save_checkpoint(checkpoint_file, outputs_agentic_rag, idx)
                print(f"Checkpoint saved. Resume from index {idx}")
                raise

    except KeyboardInterrupt:
        print("\nProcess interrupted by user")
        # Save checkpoint before exiting
        save_checkpoint(checkpoint_file, outputs_agentic_rag, idx)
        print(f"Checkpoint saved. Resume from index {idx}")

    finally:
        pbar.close()

    return outputs_agentic_rag


def save_checkpoint(checkpoint_file, results, next_idx):
    """Save checkpoint data to file"""
    checkpoint_data = {
        "results": results,
        "next_idx": next_idx,
        "timestamp": time.time()
    }

    # Use a temporary file to avoid corruption if interrupted during writing
    temp_file = f"{checkpoint_file}.temp"
    with open(temp_file, 'w') as f:
        json.dump(checkpoint_data, f)

    # Safely replace the old checkpoint file
    if os.path.exists(checkpoint_file):
        os.replace(temp_file, checkpoint_file)
    else:
        os.rename(temp_file, checkpoint_file)


outputs_agentic_rag = run_agentic_rag_with_checkpointing(eval_dataset, agent)

  2%|▏         | 1/65 [00:26<28:45, 26.96s/it]

=======================================================
Question: What architecture is the `tokenizers-linux-x64-musl` binary designed for?

Answer: x86_64-unknown-linux-musl
True answer: x86_64-unknown-linux-musl

  3%|▎         | 2/65 [00:48<24:39, 23.49s/it]

=======================================================
Question: What is the purpose of the BLIP-Diffusion model?

Answer: BLIP-Diffusion enables zero-shot subject-driven generation and control-guided zero-shot generation.
True answer: The BLIP-Diffusion model is designed for controllable text-to-image generation and editing.

  5%|▍         | 3/65 [01:04<21:07, 20.44s/it]

=======================================================
Question: How can a user claim authorship of a paper on the Hugging Face Hub?

Answer: To claim authorship of a paper on the Hub, if it's not already linked to your account, click your name on the paper page and select 'claim authorship'.  This will redirect you to the paper settings where you confirm the request. The admin team will then validate your request, and once confirmed, the paper page will show as verified.
True answer: By clicking their name on the corresponding Paper page and clicking "claim authorship", then confirming the request in paper settings for admin team validation.

  6%|▌         | 4/65 [01:22<19:30, 19.19s/it]

=======================================================
Question: What is the purpose of the /healthcheck endpoint in the Datasets server API?

Answer: The `/healthcheck` endpoint in the Datasets server API is used to verify that the application is running.
True answer: Ensure the app is running

  8%|▊         | 5/65 [01:39<18:22, 18.37s/it]

=======================================================
Question: What is the default context window size for Local Attention in the LongT5 model?

Answer: 127
True answer: 127 tokens

  9%|▉         | 6/65 [01:55<17:25, 17.73s/it]

=======================================================
Question: What method is used to load a checkpoint for a task using `AutoPipeline`?

Answer: The `from_pretrained()` method is used to load a checkpoint for a task using `AutoPipeline`.
True answer: from_pretrained()

 11%|█         | 7/65 [02:13<17:07, 17.72s/it]

=======================================================
Question: What is the purpose of Diffusers library?

Answer: The Diffusers library is a modular toolbox for working with state-of-the-art pretrained diffusion models.  It facilitates both inference (using pre-trained models for tasks like image generation) and training of custom diffusion models.  The library prioritizes usability, simplicity, and customizability.
True answer: To serve as a modular toolbox for both inference and training of state-of-the-art pretrained diffusion models across multiple modalities.

 12%|█▏        | 8/65 [02:29<16:31, 17.39s/it]

=======================================================
Question: What method does the EulerAncestralDiscreteScheduler use for sampling?

Answer: ancestral sampling with Euler method steps
True answer: Ancestral sampling with Euler method steps.

 14%|█▍        | 9/65 [02:46<16:01, 17.17s/it]

=======================================================
Question: What is the name of the large multimodal model that can solve image-text tasks and is based on Flamingo?

Answer: IDEFICS
True answer: IDEFICS

 15%|█▌        | 10/65 [03:04<15:54, 17.36s/it]

=======================================================
Question: What is the purpose of the `gradio.Blocks` API?

Answer: The `gradio.Blocks` API is a low-level API that provides fine-grained control over the data flow and layout of Gradio applications.  It enables the creation of complex, multi-step applications with features such as grouping demos into tabs, customizing layouts beyond the default left-input/right-output structure, managing multi-step interfaces where outputs become inputs, and dynamically updating component properties or visibility based on user interactions. This contrasts with the higher-level `gradio.Interface` API, which offers simpler creation of demos but less flexibility.
True answer: The `gradio.Blocks` API allows you to have full control over the data flows and layout of your application, enabling the building of complex, multi-step applications.

 17%|█▋        | 11/65 [03:22<15:57, 17.74s/it]

=======================================================
Question: What is the purpose of the two-stage model proposed in the paper "Hierarchical Text-Conditional Image Generation with CLIP Latents"?

Answer: The two-stage model leverages CLIP's robust image representations for image generation.  It consists of a prior that generates a CLIP image embedding from a text caption, and a decoder that generates an image based on this embedding. This approach improves image diversity while maintaining photorealism and caption similarity, allowing for variations that preserve semantics and style while changing non-essential details.  The joint CLIP embedding space also enables zero-shot language-guided image manipulation.
True answer: The purpose of the two-stage model is to generate a CLIP image embedding given a text caption and then generate an image conditioned on the image embedding.

 18%|█▊        | 12/65 [03:39<15:28, 17.52s/it]

=======================================================
Question: What command is used to install the requirements for a research project using 🤗 Transformers?

Answer: pip install -r requirements.txt
True answer: pip install -r requirements.txt

Error in code parsing:
expected string or bytes-like object, got 'NoneType'
Make sure to provide correct code blobs.

 20%|██        | 13/65 [04:00<15:52, 18.31s/it]

=======================================================
Question: What task does the `roberta-large-mnli` checkpoint perform?

Answer: The roberta-large-mnli checkpoint performs text classification, specifically natural language inference (classifying if two sentences are logically linked across three labels: contradiction, neutral, entailment).
True answer: Text classification

 22%|██▏       | 14/65 [04:16<15:06, 17.78s/it]

=======================================================
Question: What service is replacing the Paid tier of the Inference API at Hugging Face?

Answer: Inference Endpoints is the replacement service for the Paid tier of the Hugging Face Inference API.
True answer: Inference Endpoints

 23%|██▎       | 15/65 [04:33<14:36, 17.54s/it]

=======================================================
Question: What architectural feature does SqueezeBERT use instead of fully-connected layers for the Q, K, V, and FFN layers?

Answer: Grouped convolutions
True answer: Grouped convolutions

 25%|██▍       | 16/65 [04:50<14:07, 17.30s/it]

=======================================================
Question: What type of license is the HuggingFace Team's software distributed under?

Answer: Apache License, Version 2.0
True answer: Apache License, Version 2.0

 26%|██▌       | 17/65 [05:07<13:43, 17.15s/it]

=======================================================
Question: What are the two parameter-reduction techniques proposed in the ALBERT model to lower memory consumption and increase training speed?

Answer: ['Splitting the embedding matrix into two smaller matrices.', 'Using repeating layers split among groups.']
True answer: Splitting the embedding matrix into two smaller matrices and using repeating layers split among groups.

 28%|██▊       | 18/65 [05:28<14:22, 18.34s/it]

=======================================================
Question: What are the three main steps for fine-tuning a model with the 🤗 Datasets library?

Answer: The three main steps for fine-tuning a model with the 🤗 Datasets library are: 1. Load a dataset from the Hugging Face Hub; 2. Preprocess the data with `Dataset.map()`; 3. Load and compute metrics.
True answer: 1. Load a dataset from the Hugging Face Hub. 2. Preprocess the data with `Dataset.map()`. 3. Load and compute metrics.

 29%|██▉       | 19/65 [05:44<13:32, 17.67s/it]

=======================================================
Question: What is the maximum improvement in throughput achieved by Hugging Face Infinity compared to vanilla transformers?

Answer: 800%
True answer: +800%

 31%|███       | 20/65 [06:02<13:19, 17.76s/it]

=======================================================
Question: What is the command to upload a spaCy pipeline to the Hugging Face Hub?

Answer: python -m spacy huggingface-hub push [whl_path] [--org] [--msg] [--local-repo] [--verbose]
True answer: python -m spacy huggingface-hub push en_ner_fashion-0.0.0-py3-none-any.whl

 32%|███▏      | 21/65 [06:27<14:36, 19.92s/it]

=======================================================
Question: What is the time and memory complexity of the Nyströmformer's approximation of self-attention?

Answer: Based on the provided text, the Nyströmformer's approximation of self-attention has a time and memory complexity of O(n), where n is the sequence length.  However, precise formulas and dependencies on other factors are not explicitly stated in the retrieved documents.
True answer: O(n)

Error in code parsing:
expected string or bytes-like object, got 'NoneType'
Make sure to provide correct code blobs.

 34%|███▍      | 22/65 [06:47<14:18, 19.96s/it]

=======================================================
Question: What is the goal of the Named Entity Recognition task in token classification?

Answer: The goal of Named Entity Recognition (NER) in token classification is to identify and classify named entities (such as persons, locations, organizations) within a text by assigning a label to each token, indicating whether it belongs to a named entity and, if so, which type of entity.
True answer: The goal of the Named Entity Recognition task is to find the entities in a piece of text, such as person, location, or organization.

 35%|███▌      | 23/65 [07:03<13:15, 18.94s/it]

=======================================================
Question: What is the resolution of images used by the CLIPSeg model?

Answer: 352 x 352 pixels
True answer: 352 x 352 pixels

 37%|███▋      | 24/65 [07:34<15:17, 22.37s/it]

=======================================================
Question: What can you use Gradio for?

Answer: Gradio is a Python library used to create user interfaces (UIs) for machine learning models and other Python functions.  It allows you to quickly build interactive demos, web applications, and chatbots.  Gradio offers a range of pre-built components for handling various data types (images, text, audio, video, etc.) and supports features like queuing, streaming, styling, and progress bars.  It provides both high-level APIs (e.g., `gr.Interface`, `gr.ChatInterface`) for rapid prototyping and a low-level API (`gr.Blocks`) for more complex, customized applications.  Gradio simplifies the process of sharing your creations via publicly accessible URLs.
True answer: Create a demo for your machine learning model, share your machine learning model with others, and debug your model.

 38%|███▊      | 25/65 [08:08<17:16, 25.91s/it]

=======================================================
Question: What TensorFlow API function is used to load a saved tensor file?

Answer: TensorFlow doesn't have a single function to load all tensor file types. The approach depends on the file format. Common methods include using NumPy's `load()` function to load formats like `.npy` and then converting to TensorFlow tensors using `tf.convert_to_tensor()`. For other formats, specialized loading functions might be needed (e.g., functions within libraries like `safetensors`), or TensorFlow's `tf.io` module might be used for more general I/O operations.
True answer: safetensors.tensorflow.load_file

 40%|████      | 26/65 [08:25<15:06, 23.26s/it]

=======================================================
Question: Where can you access the logs of your Endpoints in Hugging Face Endpoints?

Answer: The logs of your Hugging Face Endpoints are accessible through the UI in the 'Logs' tab of your Endpoint.
True answer: In the "Logs" tab of your Endpoint through the UI.

 42%|████▏     | 27/65 [08:42<13:32, 21.37s/it]

=======================================================
Question: What is the latest task added to Hugging Face AutoTrain for Computer Vision?

Answer: Image Classification is the latest computer vision task added to Hugging Face AutoTrain.
True answer: Image Classification

 43%|████▎     | 28/65 [08:58<12:15, 19.88s/it]

=======================================================
Question: What is the default repository type created by the `create_repo` function on Hugging Face Hub?

Answer: model
True answer: model

 45%|████▍     | 29/65 [09:15<11:18, 18.86s/it]

=======================================================
Question: How many splits does the "duorc" dataset have?

Answer: 3
True answer: Six

 46%|████▌     | 30/65 [09:34<11:00, 18.89s/it]

=======================================================
Question: What is the purpose of Fully Sharded Data Parallel (FSDP) in distributed training?

Answer: Fully Sharded Data Parallel (FSDP) is a data parallel method that shards a model's parameters, gradients, and optimizer states across available GPUs.  This reduces memory usage compared to methods like DistributedDataParallel (DDP), improving GPU memory efficiency and enabling training of much larger models on fewer GPUs. FSDP is designed for distributed training of large pretrained models, scaling training to larger batch or model sizes by sharding model parameters, gradients, and optimizer states across data parallel processes.  It can also offload sharded model parameters to a CPU.
True answer: FSDP is developed for distributed training of large pretrained models up to 1T parameters by sharding the model parameters, gradients, and optimizer states across data parallel processes.

Error in code parsing:
expected string or bytes-like object, got 'NoneType'
Make sure to provide correct code blobs.

 48%|████▊     | 31/65 [09:55<11:06, 19.61s/it]

=======================================================
Question: What file format is used to save and store PyTorch model weights more securely than `.bin` files?

Answer: .safetensors
True answer: `.safetensors`

Error in code parsing:
expected string or bytes-like object, got 'NoneType'
Make sure to provide correct code blobs.

 49%|████▉     | 32/65 [10:15<10:48, 19.67s/it]

=======================================================
Question: What type of security certification does Hugging Face have?

Answer: Hugging Face is SOC 2 Type 2 certified.
True answer: SOC2 Type 2 certified

 51%|█████     | 33/65 [10:31<09:59, 18.73s/it]

=======================================================
Question: What do RAG models combine to generate outputs?

Answer: RAG models combine pretrained dense retrieval (DPR) and sequence-to-sequence models.
True answer: Pretrained dense retrieval (DPR) and sequence-to-sequence models.

 52%|█████▏    | 34/65 [10:48<09:21, 18.10s/it]

=======================================================
Question: What library does MarkupLMFeatureExtractor use to extract data from HTML and XML files?

Answer: Beautiful Soup
True answer: Beautiful Soup

 54%|█████▍    | 35/65 [11:14<10:11, 20.37s/it]

=======================================================
Question: What is the file size limit for syncing to HF Spaces without using Git-LFS?

Answer: Based on the documentation, the file size limit for syncing to HF Spaces without using Git-LFS is likely 10MB or less, as Git-LFS is explicitly required for files larger than 10MB.
True answer: 10MB

 55%|█████▌    | 36/65 [11:30<09:14, 19.14s/it]

=======================================================
Question: What is the title of the paper introducing the ByT5 model?

Answer: ByT5: Towards a token-free future with pre-trained byte-to-byte models
True answer: ByT5: Towards a token-free future with pre-trained byte-to-byte models

 57%|█████▋    | 37/65 [11:47<08:34, 18.38s/it]

=======================================================
Question: What is the dimension of the feature vector for the base BERT model?

Answer: 768
True answer: 768

 58%|█████▊    | 38/65 [12:08<08:42, 19.37s/it]

=======================================================
Question: What special identifier does the WordPiece Model use for continuing subwords?

Answer: ##
True answer: ##

 60%|██████    | 39/65 [12:40<09:57, 22.98s/it]

=======================================================
Question: What is the purpose of the 🧨 Diffusers tutorials?

Answer: The purpose of the 🧨 Diffusers tutorials is to provide a gentle introduction to diffusion models and the library fundamentals, enabling users to perform inference and training to generate images and build their own diffusion systems.
True answer: To provide a gentle introduction to diffusion models and help understand the library fundamentals.

 62%|██████▏   | 40/65 [12:57<08:48, 21.13s/it]

=======================================================
Question: What is the default setting for the `allow_flagging` parameter in Gradio's `Interface`?

Answer: manual
True answer: "manual"

 63%|██████▎   | 41/65 [13:14<07:57, 19.88s/it]

=======================================================
Question: Where can the full code for the Stable Diffusion demo be found?

Answer: https://hf.co/spaces/stabilityai/stable-diffusion/tree/main
True answer: https://hf.co/spaces/stabilityai/stable-diffusion/tree/main

 65%|██████▍   | 42/65 [13:31<07:21, 19.19s/it]

=======================================================
Question: What transformation does the FNet model use to replace the self-attention layer in a BERT model?

Answer: FNet replaces the self-attention layer in a BERT model with a Fourier transform, retaining only the real parts of the transform.
True answer: Fourier transform

 66%|██████▌   | 43/65 [13:48<06:46, 18.49s/it]

=======================================================
Question: What type of test should typically accompany a bug fix in Gradio's testing strategy?

Answer: A dynamic code test
True answer: Dynamic code test

 68%|██████▊   | 44/65 [14:10<06:51, 19.60s/it]

=======================================================
Question: How can you force mixed precision training when initializing the Accelerator in 🤗 Accelerate?

Answer: To force mixed precision training when initializing the Accelerator in 🤗 Accelerate, pass `fp16=True` to the `Accelerator()` constructor.  For example: `accelerator = Accelerator(fp16=True)`
True answer: By passing `fp16=True` to the Accelerator init.

 69%|██████▉   | 45/65 [14:28<06:21, 19.06s/it]

=======================================================
Question: What is the purpose of tokenizers in the NLP pipeline?

Answer: Tokenizers are fundamental components in NLP pipelines. Their primary purpose is to convert raw text input into numerical representations that machine learning models can process. This involves a series of steps, including normalization, pre-tokenization, applying a tokenization model (like BPE or WordPiece), and post-processing.  The final output is numerical data suitable for model input.
True answer: To translate text into data that can be processed by the model.

Error in code parsing:
expected string or bytes-like object, got 'NoneType'
Make sure to provide correct code blobs.

 71%|███████   | 46/65 [14:52<06:30, 20.55s/it]

=======================================================
Question: What is the purpose of the Safety Checker in the Diffusers library?

Answer: The safety checker in the Diffusers library screens generated outputs against known NSFW (Not Safe For Work) content to prevent the generation and dissemination of harmful material.
True answer: The Safety Checker checks and compares the class probability of a set of hard-coded harmful concepts in the embedding space against an image after it has been generated to mitigate the risk of generating harmful content.

 72%|███████▏  | 47/65 [15:09<05:51, 19.51s/it]

=======================================================
Question: What Python class allows you to retrieve Discussions and Pull Requests from a given repository on the Hugging Face Hub?

Answer: HfApi
True answer: HfApi

 74%|███████▍  | 48/65 [15:26<05:20, 18.86s/it]

=======================================================
Question: What is the name of the new library introduced by Hugging Face for hosting scikit-learn models?

Answer: Skops
True answer: Skops

 75%|███████▌  | 49/65 [15:44<04:53, 18.33s/it]

=======================================================
Question: What is the purpose of Textual Inversion?

Answer: Textual Inversion is a training method used to personalize image generation models, such as Stable Diffusion.  It learns new text embeddings from a small number of example images (typically 3-5), allowing the model to generate images based on those specific examples by associating them with a new token in the prompt.
True answer: Textual Inversion is a training method for personalizing models by learning new text embeddings from a few example images.

 77%|███████▋  | 50/65 [16:10<05:11, 20.77s/it]

=======================================================
Question: What is the recommended multiple of batch size for fp16 data type on an A100 GPU?

Answer: Based on the retrieved documents, there is no single recommended multiple for the batch size when using fp16 on an A100 GPU. The optimal batch size depends heavily on factors such as model size, available GPU memory, and the use of optimization techniques like gradient accumulation, CPU offloading, and mixed precision.  Observed examples show batch sizes ranging from 1 to 64, with the choice often driven by a trade-off between throughput and memory usage.  A systematic approach involving experimentation and performance monitoring is necessary to determine the optimal batch size for a specific use case.
True answer: 64

 78%|███████▊  | 51/65 [16:28<04:40, 20.06s/it]

=======================================================
Question: How do you run a Gradio Blocks app in reload mode using a Python IDE?

Answer: To run a Gradio Blocks app in reload mode using a Python IDE, run the command `gradio run.py` from your terminal, where `run.py` is the name of your Python file containing the Gradio Blocks app.  This will launch the app in reload mode, automatically refreshing the app whenever changes are saved to the `run.py` file.
True answer: Run `gradio run.py` in the terminal.

 80%|████████  | 52/65 [16:46<04:10, 19.24s/it]

=======================================================
Question: How can you install the Hugging Face Unity API in your Unity project?

Answer: To install the Hugging Face Unity API:

1. Open your Unity project.
2. Go to Window -> Package Manager.
3. Click '+' and select 'Add package from git URL'.
4. Enter `https://github.com/huggingface/unity-api.git`.
5. Once installed, the Unity API wizard should pop up. If not, go to Window -> Hugging Face API Wizard.
True answer: To install the Hugging Face Unity API in your Unity project, go to `Window` -> `Package Manager`, click `+` and select `Add Package from git URL`, then enter `https://github.com/huggingface/unity-api.git`.

 82%|████████▏ | 53/65 [17:03<03:42, 18.57s/it]

=======================================================
Question: What is the pretraining objective of the Wav2Vec2 context network?

Answer: Wav2Vec2's pretraining uses a contrastive loss objective.
True answer: The pretraining objective of the Wav2Vec2 context network is a contrastive task where the model has to predict the true quantized speech representation of the masked prediction from a set of false ones.

 83%|████████▎ | 54/65 [17:20<03:18, 18.06s/it]

=======================================================
Question: What is the default checkpoint used by the sentiment analysis pipeline in the Transformers library?

Answer: distilbert-base-uncased-finetuned-sst-2-english
True answer: distilbert base uncased finetuned sst2 english

 85%|████████▍ | 55/65 [17:37<02:59, 17.99s/it]

=======================================================
Question: What is the purpose of the notebook "How to use DeepSpeed to train models with billions of parameters on Habana Gaudi"?

Answer: The purpose of the notebook 'How to use DeepSpeed to train models with billions of parameters on Habana Gaudi' is to demonstrate how to use DeepSpeed to pre-train or fine-tune the 1.6B-parameter GPT2-XL model for causal language modeling on Habana Gaudi hardware.
True answer: To show how to use DeepSpeed to pre-train/fine-tune the 1.6B-parameter GPT2-XL for causal language modeling on Habana Gaudi.

 86%|████████▌ | 56/65 [17:58<02:48, 18.75s/it]

=======================================================
Question: What command line module does PyTorch provide to run a script on multiple GPUs?

Answer: The PyTorch command-line module for running a script on multiple GPUs is `torchrun`.  It's used with the `--nproc_per_node` argument to specify the number of GPUs per node.
True answer: torchrun

 88%|████████▊ | 57/65 [18:15<02:25, 18.25s/it]

=======================================================
Question: What is the most popular vision transformer model on the Hugging Face Model Hub for image classification?

Answer: google/vit-base-patch16-224
True answer: google/vit-base-patch16-224

 89%|████████▉ | 58/65 [18:33<02:06, 18.10s/it]

=======================================================
Question: What is the command to upload an ESPnet model to a Hugging Face repository?

Answer: ./run.sh --stage 15 --skip_upload_hf false --hf_repo username/model_repo
True answer: ./run.sh --stage 15 --skip_upload_hf false --hf_repo username/model_repo

 91%|█████████ | 59/65 [18:49<01:45, 17.62s/it]

=======================================================
Question: What file should be added to a model repository to install custom Python dependencies for Inference Endpoints?

Answer: requirements.txt
True answer: requirements.txt

 92%|█████████▏| 60/65 [19:07<01:27, 17.53s/it]

=======================================================
Question: How many images are needed to teach new concepts to Stable Diffusion using Textual Inversion?

Answer: 3-5 images are typically needed to train new concepts in Stable Diffusion using Textual Inversion.
True answer: 3-5 images

 94%|█████████▍| 61/65 [19:37<01:25, 21.36s/it]

=======================================================
Question: What is the maximum size of a model checkpoint before it is automatically sharded in Transformers version 4.18.0?

Answer: 10GB
True answer: 10GB

 95%|█████████▌| 62/65 [20:02<01:07, 22.63s/it]

=======================================================
Question: What is the purpose of Weights and Biases (W&B) for data scientists and machine learning scientists?

Answer: Weights & Biases (W&B) is a tool used for logging and monitoring machine learning experiments.  It allows data scientists and machine learning engineers to track metrics, visualize results, and manage experiments efficiently.
True answer: To track their machine learning experiments at every stage, from training to production.

 97%|█████████▋| 63/65 [20:20<00:42, 21.11s/it]

=======================================================
Question: What is the name of the open-source library created by Hugging Face to simplify Transformer acceleration?

Answer: Optimum
True answer: Optimum

 98%|█████████▊| 64/65 [20:37<00:19, 19.82s/it]

=======================================================
Question: What parameter is used to ensure that elements in a row have the same height in Gradio?

Answer: The `equal_height` parameter, passed to the `.style()` method of `gr.Row()`, ensures that elements within a Gradio row have the same height.
True answer: equal_height

100%|██████████| 65/65 [20:54<00:00, 18.96s/it]

=======================================================
Question: What is the command to install the latest version of Optimum with OpenVINO support?

Answer: pip install --upgrade-strategy eager optimum[openvino,nncf]
True answer: pip install --upgrade-strategy eager optimum["openvino"]

100%|██████████| 65/65 [21:04<00:00, 19.45s/it]

In [58]:
##### using only RAG to answer questions

answer_llm = OpenAIServerModel(
    model_id=model_name,
    api_base="https://generativelanguage.googleapis.com/v1beta/openai/",
    api_key=os.getenv("Gemini_API_KEY2"),
    # flatten_messages_as_text=True,
    temperature=0.2)

# answer_llm = OpenAIServerModel(
#     model_id=models[4],
#     api_base="https://helmholtz-blablador.fz-juelich.de:8000/v1",
#     api_key=Blablador_API_KEY,
#     # flatten_messages_as_text=True,
#     temperature=0.2)

# inspect = eval_dataset.select(list(range(20)))

outputs_standard_rag = []

for example in tqdm(eval_dataset):
    question = example["question"]
    context = retriever_tool(question, k=7)

    prompt = f"""Given the question and supporting documents below, give a comprehensive answer to the question.
Respond only to the question asked, response should be concise and relevant to the question.
If the question is ambiguous or cannot be answered definitively, state so clearly.

Question:
{question}

{context}
"""
    messages = [{"role": "user", "content": prompt}]
    answer = answer_llm.generate(messages).content

    print("=======================================================")
    print(f"Question: {question}")
    # print(f"Context: {context}")
    print(f"Answer: {answer}")
    print(f'True answer: {example["answer"]}')

    results_agentic = {
        "question": question,
        "true_answer": example["answer"],
        "source_doc": example["source_doc"],
        "generated_answer": answer,
    }
    outputs_standard_rag.append(results_agentic)
    time.sleep(5)

  0%|          | 0/65 [00:00<?, ?it/s]

=======================================================
Question: What architecture is the `tokenizers-linux-x64-musl` binary designed for?

Answer: The `tokenizers-linux-x64-musl` binary is designed for the **x86_64-unknown-linux-musl** architecture.

True answer: x86_64-unknown-linux-musl

  2%|▏         | 1/65 [00:20<22:05, 20.71s/it]

=======================================================
Question: What is the purpose of the BLIP-Diffusion model?

Answer: The purpose of the BLIP-Diffusion model is to enable zero-shot subject-driven generation and control-guided zero-shot generation of images from text.

True answer: The BLIP-Diffusion model is designed for controllable text-to-image generation and editing.

  3%|▎         | 2/65 [00:41<21:49, 20.79s/it]

=======================================================
Question: How can a user claim authorship of a paper on the Hugging Face Hub?

Answer: If the paper is not automatically linked to your account, go to the paper's page on Hugging Face Hub, click your name, and then click "claim authorship."  This will redirect you to your paper settings to confirm; the admin team will then validate your request.

True answer: By clicking their name on the corresponding Paper page and clicking "claim authorship", then confirming the request in paper settings for admin team validation.

  5%|▍         | 3/65 [01:02<21:34, 20.89s/it]

=======================================================
Question: What is the purpose of the /healthcheck endpoint in the Datasets server API?

Answer: The `/healthcheck` endpoint ensures the Datasets server application is running.

True answer: Ensure the app is running

  6%|▌         | 4/65 [01:18<19:08, 18.83s/it]

=======================================================
Question: What is the default context window size for Local Attention in the LongT5 model?

Answer: The default context window size for Local Attention in the LongT5 model is 127 tokens (r=127).

True answer: 127 tokens

  8%|▊         | 5/65 [01:44<21:21, 21.36s/it]

=======================================================
Question: What method is used to load a checkpoint for a task using `AutoPipeline`?

Answer: The `AutoPipeline` uses the `from_pretrained()` method to load a checkpoint for a task.  For more memory efficiency when switching between tasks with the same checkpoint, the `from_pipe()` method can be used to transfer components from a previously loaded pipeline.

True answer: from_pretrained()

  9%|▉         | 6/65 [02:00<19:14, 19.57s/it]

=======================================================
Question: What is the purpose of Diffusers library?

Answer: The Diffusers library is a toolbox for working with state-of-the-art pretrained diffusion models.  Its purpose is to provide a user-friendly way to perform inference (generating images, audio, and 3D molecular structures) and to train custom diffusion models.  It prioritizes usability and ease of use over raw performance.

True answer: To serve as a modular toolbox for both inference and training of state-of-the-art pretrained diffusion models across multiple modalities.

 11%|█         | 7/65 [02:06<14:38, 15.14s/it]

=======================================================
Question: What method does the EulerAncestralDiscreteScheduler use for sampling?

Answer: The EulerAncestralDiscreteScheduler uses ancestral sampling with Euler method steps.

True answer: Ancestral sampling with Euler method steps.

 12%|█▏        | 8/65 [02:11<11:30, 12.12s/it]

=======================================================
Question: What is the name of the large multimodal model that can solve image-text tasks and is based on Flamingo?

Answer: IDEFICS is a large multimodal model based on Flamingo that solves image-text tasks.

True answer: IDEFICS

 14%|█▍        | 9/65 [02:17<09:27, 10.13s/it]

=======================================================
Question: What is the purpose of the `gradio.Blocks` API?

Answer: The `gradio.Blocks` API is a low-level API providing full control over data flow and layout in Gradio applications.  It enables the creation of complex, multi-step applications with features like custom layouts, multi-step interfaces where outputs become inputs, and dynamic updates to component properties based on user interaction.  This contrasts with the higher-level `gradio.Interface` API, which offers simpler creation of demos but less control.

True answer: The `gradio.Blocks` API allows you to have full control over the data flows and layout of your application, enabling the building of complex, multi-step applications.

 15%|█▌        | 10/65 [02:23<08:09,  8.90s/it]

=======================================================
Question: What is the purpose of the two-stage model proposed in the paper "Hierarchical Text-Conditional Image Generation with CLIP Latents"?

Answer: The two-stage model in "Hierarchical Text-Conditional Image Generation with CLIP Latents" aims to improve text-conditional image generation.  It uses a hierarchical approach, first predicting CLIP image embeddings from text embeddings (using a diffusion process), and then refining the generated image using a second stage.  This allows for better control and higher-quality image generation compared to single-stage methods.

True answer: The purpose of the two-stage model is to generate a CLIP image embedding given a text caption and then generate an image conditioned on the image embedding.

 17%|█▋        | 11/65 [02:29<07:14,  8.05s/it]

=======================================================
Question: What command is used to install the requirements for a research project using 🤗 Transformers?

Answer: `pip install -r requirements.txt`

True answer: pip install -r requirements.txt

 18%|█▊        | 12/65 [02:35<06:28,  7.33s/it]

=======================================================
Question: What task does the `roberta-large-mnli` checkpoint perform?

Answer: The `roberta-large-mnli` checkpoint performs natural language inference, classifying if two sentences are logically linked across three labels (contradiction, neutral, entailment).

True answer: Text classification

 20%|██        | 13/65 [02:41<05:57,  6.87s/it]

=======================================================
Question: What service is replacing the Paid tier of the Inference API at Hugging Face?

Answer: Hugging Face Inference Endpoints is replacing the Paid tier of the Inference API.

True answer: Inference Endpoints

 22%|██▏       | 14/65 [02:47<05:32,  6.51s/it]

=======================================================
Question: What architectural feature does SqueezeBERT use instead of fully-connected layers for the Q, K, V, and FFN layers?

Answer: SqueezeBERT uses grouped convolutions.

True answer: Grouped convolutions

 23%|██▎       | 15/65 [02:52<05:12,  6.25s/it]

=======================================================
Question: What type of license is the HuggingFace Team's software distributed under?

Answer: The Hugging Face Team's software is distributed under the Apache License, Version 2.0.

True answer: Apache License, Version 2.0

 25%|██▍       | 16/65 [02:58<04:57,  6.08s/it]

=======================================================
Question: What are the two parameter-reduction techniques proposed in the ALBERT model to lower memory consumption and increase training speed?

Answer: The ALBERT model proposes two parameter-reduction techniques:  splitting the embedding matrix into two smaller matrices, and using repeating layers split among groups.

True answer: Splitting the embedding matrix into two smaller matrices and using repeating layers split among groups.

 26%|██▌       | 17/65 [03:04<04:47,  5.99s/it]

=======================================================
Question: What are the three main steps for fine-tuning a model with the 🤗 Datasets library?

Answer: The three main steps for fine-tuning a model with the 🤗 Datasets library are: 1) loading a dataset from the Hugging Face Hub; 2) preprocessing the data with `Dataset.map()`; and 3) loading and computing metrics.

True answer: 1. Load a dataset from the Hugging Face Hub. 2. Preprocess the data with `Dataset.map()`. 3. Load and compute metrics.

 28%|██▊       | 18/65 [03:10<04:40,  5.97s/it]

=======================================================
Question: What is the maximum improvement in throughput achieved by Hugging Face Infinity compared to vanilla transformers?

Answer: Hugging Face Infinity achieves up to 800% higher throughput compared to vanilla transformers.

True answer: +800%

 29%|██▉       | 19/65 [03:15<04:31,  5.89s/it]

=======================================================
Question: What is the command to upload a spaCy pipeline to the Hugging Face Hub?

Answer: `python -m spacy huggingface-hub push [whl_path] [--org] [--msg] [--local-repo] [--verbose]`  where `[whl_path]` is the path to the wheel file created using `python -m spacy package`.

True answer: python -m spacy huggingface-hub push en_ner_fashion-0.0.0-py3-none-any.whl

 31%|███       | 20/65 [03:21<04:25,  5.91s/it]

=======================================================
Question: What is the time and memory complexity of the Nyströmformer's approximation of self-attention?

Answer: The Nyströmformer's approximation of self-attention has a time and memory complexity of O(n), where n is the length of the input sequence.

True answer: O(n)

 32%|███▏      | 21/65 [03:27<04:18,  5.89s/it]

=======================================================
Question: What is the goal of the Named Entity Recognition task in token classification?

Answer: The goal of Named Entity Recognition (NER) in token classification is to identify and classify named entities in text, such as persons, locations, or organizations, by assigning a label to each token in a sentence.  One label is assigned per entity, with an additional label for tokens not belonging to any entity.

True answer: The goal of the Named Entity Recognition task is to find the entities in a piece of text, such as person, location, or organization.

 34%|███▍      | 22/65 [03:33<04:15,  5.93s/it]

=======================================================
Question: What is the resolution of images used by the CLIPSeg model?

Answer: The CLIPSeg model uses images of 352 x 352 pixels.

True answer: 352 x 352 pixels

 35%|███▌      | 23/65 [03:39<04:06,  5.87s/it]

=======================================================
Question: What can you use Gradio for?

Answer: Gradio is a Python library used to quickly create customizable web apps for machine learning models and data processing pipelines.  These apps can be deployed on Hugging Face Spaces or a custom web server (e.g., using Nginx).  Gradio allows for customization of app appearance and behavior.

True answer: Create a demo for your machine learning model, share your machine learning model with others, and debug your model.

 37%|███▋      | 24/65 [03:45<04:00,  5.86s/it]

=======================================================
Question: What TensorFlow API function is used to load a saved tensor file?

Answer: The provided text mentions `safetensors.tensorflow.load_file` and `safetensors.tensorflow.load` for loading safetensors files, but doesn't specify a TensorFlow function for loading general saved tensor files.  The documents focus on SavedModel for model deployment, not loading arbitrary tensor files.

True answer: safetensors.tensorflow.load_file

 38%|███▊      | 25/65 [03:51<03:56,  5.90s/it]

=======================================================
Question: Where can you access the logs of your Endpoints in Hugging Face Endpoints?

Answer: You can access your Hugging Face Endpoint logs through the UI, in the "Logs" tab of your Endpoint.  Build logs are available even if the Endpoint creation failed. Container logs are only available when the Endpoint is running.

True answer: In the "Logs" tab of your Endpoint through the UI.

 40%|████      | 26/65 [03:56<03:47,  5.84s/it]

=======================================================
Question: What is the latest task added to Hugging Face AutoTrain for Computer Vision?

Answer: Image Classification is the latest task added to Hugging Face AutoTrain for Computer Vision.

True answer: Image Classification

 42%|████▏     | 27/65 [04:02<03:40,  5.80s/it]

=======================================================
Question: What is the default repository type created by the `create_repo` function on Hugging Face Hub?

Answer: The `create_repo` function on Hugging Face Hub defaults to creating a model repository.  However, the `repo_type` parameter can be used to specify  `"dataset"` or `"space"` instead.

True answer: model

 43%|████▎     | 28/65 [04:08<03:35,  5.83s/it]

=======================================================
Question: How many splits does the "duorc" dataset have?

Answer: The "duorc" dataset has three splits: train, validation, and test.

True answer: Six

 45%|████▍     | 29/65 [04:14<03:28,  5.78s/it]

=======================================================
Question: What is the purpose of Fully Sharded Data Parallel (FSDP) in distributed training?

Answer: Fully Sharded Data Parallel (FSDP) is a data parallel method for distributed training of large models (up to 1 trillion parameters).  It shards model parameters, gradients, and optimizer states across multiple GPUs, improving memory efficiency and enabling training of larger models on fewer GPUs than traditional methods like DistributedDataParallel (DDP).  FSDP can also offload sharded parameters to the CPU to further reduce GPU memory usage, although this may increase overall GPU memory consumption in some cases.

True answer: FSDP is developed for distributed training of large pretrained models up to 1T parameters by sharding the model parameters, gradients, and optimizer states across data parallel processes.

 46%|████▌     | 30/65 [04:20<03:27,  5.91s/it]

=======================================================
Question: What file format is used to save and store PyTorch model weights more securely than `.bin` files?

Answer: The `.safetensors` file format is presented as a more secure alternative to `.bin` files for storing PyTorch model weights.

True answer: `.safetensors`

 48%|████▊     | 31/65 [04:26<03:19,  5.86s/it]

=======================================================
Question: What type of security certification does Hugging Face have?

Answer: Hugging Face is SOC 2 Type 2 certified.

True answer: SOC2 Type 2 certified

 49%|████▉     | 32/65 [04:31<03:12,  5.82s/it]

=======================================================
Question: What do RAG models combine to generate outputs?

Answer: RAG models combine pretrained dense retrieval (DPR) and sequence-to-sequence (seq2seq) models.  They retrieve documents, pass them to the seq2seq model, and then generate outputs.

True answer: Pretrained dense retrieval (DPR) and sequence-to-sequence models.

 51%|█████     | 33/65 [04:37<03:06,  5.83s/it]

=======================================================
Question: What library does MarkupLMFeatureExtractor use to extract data from HTML and XML files?

Answer: MarkupLMFeatureExtractor uses Beautiful Soup.

True answer: Beautiful Soup

 52%|█████▏    | 34/65 [04:43<02:59,  5.78s/it]

=======================================================
Question: What is the file size limit for syncing to HF Spaces without using Git-LFS?

Answer: There is no explicitly stated file size limit for syncing to HF Spaces without using Git-LFS.  However, documents suggest that very large files negatively impact performance (slow download speeds due to lack of CloudFront caching).  For optimal performance, it's recommended to split large files into chunks of around 5GB each.  For files larger than 10MB, Git-LFS is recommended.

True answer: 10MB

 54%|█████▍    | 35/65 [04:49<02:56,  5.89s/it]

=======================================================
Question: What is the title of the paper introducing the ByT5 model?

Answer: ByT5: Towards a token-free future with pre-trained byte-to-byte models

True answer: ByT5: Towards a token-free future with pre-trained byte-to-byte models

 55%|█████▌    | 36/65 [04:55<02:48,  5.80s/it]

=======================================================
Question: What is the dimension of the feature vector for the base BERT model?

Answer: The dimension of the feature vector for the base BERT model is 768.

True answer: 768

 57%|█████▋    | 37/65 [05:00<02:41,  5.75s/it]

=======================================================
Question: What special identifier does the WordPiece Model use for continuing subwords?

Answer: Documents 2 and 4 indicate that the WordPiece model uses "##" as a prefix for subwords that do not begin a word.

True answer: ##

 58%|█████▊    | 38/65 [05:06<02:35,  5.77s/it]

=======================================================
Question: What is the purpose of the 🧨 Diffusers tutorials?

Answer: The purpose of the 🧨 Diffusers tutorials (examples) is to demonstrate how to use the `diffusers` library for various tasks, including training and fine-tuning.  They aim to be self-contained, easy to modify, beginner-friendly, and focused on a single purpose.  Inference examples are found separately in the `src/diffusers/pipelines` directory.

True answer: To provide a gentle introduction to diffusion models and help understand the library fundamentals.

 60%|██████    | 39/65 [05:12<02:32,  5.86s/it]

=======================================================
Question: What is the default setting for the `allow_flagging` parameter in Gradio's `Interface`?

Answer: The default setting for the `allow_flagging` parameter in Gradio's `Interface` is `"manual"`.

True answer: "manual"

 62%|██████▏   | 40/65 [05:18<02:25,  5.82s/it]

=======================================================
Question: Where can the full code for the Stable Diffusion demo be found?

Answer: Document 1 and Document 7 point to https://hf.co/spaces/stabilityai/stable-diffusion/tree/main as the location of the full code for a Stable Diffusion demo.

True answer: https://hf.co/spaces/stabilityai/stable-diffusion/tree/main

 63%|██████▎   | 41/65 [05:24<02:20,  5.87s/it]

=======================================================
Question: What transformation does the FNet model use to replace the self-attention layer in a BERT model?

Answer: The FNet model replaces the self-attention layer in a BERT model with a Fourier transform, using only the real parts of the transform.

True answer: Fourier transform

 65%|██████▍   | 42/65 [05:30<02:14,  5.85s/it]

=======================================================
Question: What type of test should typically accompany a bug fix in Gradio's testing strategy?

Answer: A dynamic code test should typically accompany a bug fix, although a linting rule or new type could be appropriate in some cases.

True answer: Dynamic code test

 66%|██████▌   | 43/65 [05:35<02:07,  5.81s/it]

=======================================================
Question: How can you force mixed precision training when initializing the Accelerator in 🤗 Accelerate?

Answer: To force mixed precision training when initializing the Accelerator in 🤗 Accelerate, pass `fp16=True` to the `Accelerator()` constructor.  Alternatively,  `bf16=True` can be used if the hardware supports it.

True answer: By passing `fp16=True` to the Accelerator init.

 68%|██████▊   | 44/65 [05:41<02:02,  5.84s/it]

=======================================================
Question: What is the purpose of tokenizers in the NLP pipeline?

Answer: Tokenizers in NLP pipelines convert raw text into numerical data that NLP models can process.  This involves steps like normalization, pre-tokenization (splitting text into words), applying a tokenization model (e.g., BPE, WordPiece), and post-processing (adding special tokens).  The output is a numerical representation of the text, suitable for model input.

True answer: To translate text into data that can be processed by the model.

 69%|██████▉   | 45/65 [05:47<01:58,  5.90s/it]

=======================================================
Question: What is the purpose of the Safety Checker in the Diffusers library?

Answer: The Safety Checker in the Diffusers library screens generated outputs against a hardcoded list of NSFW content to prevent the generation of harmful content.  It can be disabled by passing `None` to the `safety_checker` argument.

True answer: The Safety Checker checks and compares the class probability of a set of hard-coded harmful concepts in the embedding space against an image after it has been generated to mitigate the risk of generating harmful content.

 71%|███████   | 46/65 [05:53<01:52,  5.90s/it]

=======================================================
Question: What Python class allows you to retrieve Discussions and Pull Requests from a given repository on the Hugging Face Hub?

Answer: The `HfApi` class in the `huggingface_hub` library.  Specifically, the `get_repo_discussions` method within that class.

True answer: HfApi

 72%|███████▏  | 47/65 [05:59<01:45,  5.88s/it]

=======================================================
Question: What is the name of the new library introduced by Hugging Face for hosting scikit-learn models?

Answer: The provided text does not name a new Hugging Face library specifically for hosting scikit-learn models.  The `huggingface_hub` library is mentioned, which allows interaction with the Hugging Face Hub for hosting various models, but no specific scikit-learn integration is detailed.

True answer: Skops

 74%|███████▍  | 48/65 [06:05<01:40,  5.92s/it]

=======================================================
Question: What is the purpose of Textual Inversion?

Answer: Textual Inversion is a training method for personalizing image generation models.  It learns new text embeddings from a small number (3-5) of example images, allowing the model to generate images based on those specific examples using a special token in the prompt.  The resulting file is small (a few KBs) and can be loaded into the text encoder.

True answer: Textual Inversion is a training method for personalizing models by learning new text embeddings from a few example images.

 75%|███████▌  | 49/65 [06:11<01:35,  5.99s/it]

=======================================================
Question: What is the recommended multiple of batch size for fp16 data type on an A100 GPU?

Answer: The provided text offers examples of batch sizes used with fp16 on A100 GPUs, but doesn't state a recommended multiple.  Document 5 shows a throughput comparison using batch sizes of 32 and 64 across 8 A100 GPUs in a distributed setting.  Other documents discuss batch size optimization strategies but don't provide a specific recommended multiple for fp16 on A100s.

True answer: 64

 77%|███████▋  | 50/65 [06:17<01:29,  5.99s/it]

=======================================================
Question: How do you run a Gradio Blocks app in reload mode using a Python IDE?

Answer: To run a Gradio Blocks app in reload mode from a Python IDE, save your code (e.g., in `run.py`).  Then, instead of running `python run.py`, run `gradio run.py` from your terminal.  If your Blocks app isn't named `demo`, specify its name as a second argument (e.g., `gradio run.py my_demo`).  For non-UTF-8 encodings, add an encoding declaration to your script (e.g., `# -*- coding: cp1252 -*-`) and run `gradio run.py --encoding cp1252`.

True answer: Run `gradio run.py` in the terminal.

 78%|███████▊  | 51/65 [06:24<01:26,  6.15s/it]

=======================================================
Question: How can you install the Hugging Face Unity API in your Unity project?

Answer: To install the Hugging Face Unity API, open your Unity project's Package Manager (`Window` -> `Package Manager`), click the `+` button, select "Add package from git URL," and enter `https://github.com/huggingface/unity-api.git`.  After installation, an API wizard should appear (or go to `Window` -> `Hugging Face API Wizard`).  Enter your Hugging Face API key (obtainable from your account settings), test it, and configure settings as needed.  The wizard also allows installing example scripts.

True answer: To install the Hugging Face Unity API in your Unity project, go to `Window` -> `Package Manager`, click `+` and select `Add Package from git URL`, then enter `https://github.com/huggingface/unity-api.git`.

 80%|████████  | 52/65 [06:30<01:20,  6.21s/it]

=======================================================
Question: What is the pretraining objective of the Wav2Vec2 context network?

Answer: The Wav2Vec2 context network's pretraining objective is a contrastive loss.

True answer: The pretraining objective of the Wav2Vec2 context network is a contrastive task where the model has to predict the true quantized speech representation of the masked prediction from a set of false ones.

 82%|████████▏ | 53/65 [06:36<01:12,  6.06s/it]

=======================================================
Question: What is the default checkpoint used by the sentiment analysis pipeline in the Transformers library?

Answer: The default checkpoint used by the sentiment analysis pipeline in the Transformers library is `distilbert-base-uncased-finetuned-sst-2-english`.

True answer: distilbert base uncased finetuned sst2 english

 83%|████████▎ | 54/65 [06:42<01:05,  5.99s/it]

=======================================================
Question: What is the purpose of the notebook "How to use DeepSpeed to train models with billions of parameters on Habana Gaudi"?

Answer: The notebook "How to use DeepSpeed to train models with billions of parameters on Habana Gaudi" demonstrates how to use DeepSpeed to pre-train or fine-tune the 1.6B-parameter GPT2-XL model for causal language modeling on Habana Gaudi hardware.

True answer: To show how to use DeepSpeed to pre-train/fine-tune the 1.6B-parameter GPT2-XL for causal language modeling on Habana Gaudi.

 85%|████████▍ | 55/65 [06:48<00:59,  5.99s/it]

=======================================================
Question: What command line module does PyTorch provide to run a script on multiple GPUs?

Answer: PyTorch provides the `torchrun` command-line module to run a script on multiple GPUs.

True answer: torchrun

 86%|████████▌ | 56/65 [06:53<00:53,  5.90s/it]

=======================================================
Question: What is the most popular vision transformer model on the Hugging Face Model Hub for image classification?

Answer: Based on the provided text, the most popular vision transformer model on the Hugging Face Model Hub for image classification at the time of writing of Document 3 was `google/vit-base-patch16-224`.

True answer: google/vit-base-patch16-224

 88%|████████▊ | 57/65 [06:59<00:47,  5.89s/it]

=======================================================
Question: What is the command to upload an ESPnet model to a Hugging Face repository?

Answer: The command `./run.sh --stage 15 --skip_upload_hf false --hf_repo username/model_repo` is provided as a method to upload an ESPnet model to a Hugging Face repository.  Note that  `username/model_repo` needs to be replaced with your Hugging Face username and desired repository name.

True answer: ./run.sh --stage 15 --skip_upload_hf false --hf_repo username/model_repo

 89%|████████▉ | 58/65 [07:05<00:41,  5.93s/it]

=======================================================
Question: What file should be added to a model repository to install custom Python dependencies for Inference Endpoints?

Answer: A `requirements.txt` file should be added to the model repository.

True answer: requirements.txt

 91%|█████████ | 59/65 [07:11<00:35,  5.86s/it]

=======================================================
Question: How many images are needed to teach new concepts to Stable Diffusion using Textual Inversion?

Answer: 3-5 images are sufficient to teach new concepts to Stable Diffusion using Textual Inversion.

True answer: 3-5 images

 92%|█████████▏| 60/65 [07:17<00:29,  5.81s/it]

=======================================================
Question: What is the maximum size of a model checkpoint before it is automatically sharded in Transformers version 4.18.0?

Answer: In Transformers version 4.18.0, model checkpoints larger than 10GB are automatically sharded.  This size can be controlled using the `max_shard_size` parameter.

True answer: 10GB

 94%|█████████▍| 61/65 [07:22<00:23,  5.82s/it]

=======================================================
Question: What is the purpose of Weights and Biases (W&B) for data scientists and machine learning scientists?

Answer: Weights and Biases (W&B) enables data scientists and machine learning scientists to track their machine learning experiments throughout their lifecycle, from training to production.  It aggregates metrics, displaying them in customizable and searchable dashboards.

True answer: To track their machine learning experiments at every stage, from training to production.

 95%|█████████▌| 62/65 [07:28<00:17,  5.84s/it]

=======================================================
Question: What is the name of the open-source library created by Hugging Face to simplify Transformer acceleration?

Answer: Accelerate

True answer: Optimum

 97%|█████████▋| 63/65 [07:34<00:11,  5.76s/it]

=======================================================
Question: What parameter is used to ensure that elements in a row have the same height in Gradio?

Answer: The `equal_height` parameter, passed to the `.style()` method of `gr.Row()`, ensures elements in a Gradio row have the same height.

True answer: equal_height

 98%|█████████▊| 64/65 [07:40<00:05,  5.77s/it]

=======================================================
Question: What is the command to install the latest version of Optimum with OpenVINO support?

Answer: ```bash
pip install --upgrade-strategy eager optimum[openvino,nncf]
```

True answer: pip install --upgrade-strategy eager optimum["openvino"]

100%|██████████| 65/65 [07:45<00:00,  7.17s/it]

In [59]:
##### using vanilla LLM to answer questions

# answer_llm = OpenAIServerModel(
#     model_id=models[4],
#     api_base="https://helmholtz-blablador.fz-juelich.de:8000/v1",
#     api_key=Blablador_API_KEY,
#     # flatten_messages_as_text=True,
#     temperature=0.2)

outputs_standard = []

for example in tqdm(eval_dataset):
    question = example["question"]

    prompt = f"""Answer the following question as clearly and concisely as possible.
Use your own knowledge to respond.
If the question is ambiguous or cannot be answered definitively, state so clearly.

Question:
{question}

"""
    messages = [{"role": "user", "content": prompt}]
    answer = answer_llm.generate(messages).content

    print("=======================================================")
    print(f"Question: {question}")
    print(f"Answer: {answer}")
    print(f'True answer: {example["answer"]}')

    results_llm = {
        "question": question,
        "true_answer": example["answer"],
        "source_doc": example["source_doc"],
        "generated_answer": answer,
    }
    outputs_standard.append(results_llm)
    time.sleep(5)

  0%|          | 0/65 [00:00<?, ?it/s]

=======================================================
Question: What architecture is the `tokenizers-linux-x64-musl` binary designed for?

Answer: Linux x64 using the musl libc.

True answer: x86_64-unknown-linux-musl

  2%|▏         | 1/65 [00:05<05:51,  5.49s/it]

=======================================================
Question: What is the purpose of the BLIP-Diffusion model?

Answer: The purpose of the BLIP-Diffusion model is to generate images from text prompts.

True answer: The BLIP-Diffusion model is designed for controllable text-to-image generation and editing.

  3%|▎         | 2/65 [00:10<05:46,  5.50s/it]

=======================================================
Question: How can a user claim authorship of a paper on the Hugging Face Hub?

Answer: A user cannot directly "claim authorship" of a paper on the Hugging Face Hub.  The Hub hosts models and datasets, not papers.  Authorship of a paper is established through the publication process of the journal or conference where it's published.

True answer: By clicking their name on the corresponding Paper page and clicking "claim authorship", then confirming the request in paper settings for admin team validation.

  5%|▍         | 3/65 [00:16<05:48,  5.63s/it]

=======================================================
Question: What is the purpose of the /healthcheck endpoint in the Datasets server API?

Answer: The `/healthcheck` endpoint in a Datasets server API is used to verify the server's operational status.  It provides a quick and simple way to check if the server is running and responding correctly.

True answer: Ensure the app is running

  6%|▌         | 4/65 [00:22<05:43,  5.64s/it]

=======================================================
Question: What is the default context window size for Local Attention in the LongT5 model?

Answer: The question is ambiguous.  LongT5 doesn't have a single, publicly documented "default" local attention context window size.  The size is likely configurable and dependent on the specific implementation and training parameters used.

True answer: 127 tokens

  8%|▊         | 5/65 [00:28<05:38,  5.64s/it]

=======================================================
Question: What method is used to load a checkpoint for a task using `AutoPipeline`?

Answer: `AutoPipeline` doesn't directly support loading checkpoints in the same way a typical training loop might.  It's designed for automated pipeline creation and execution, not for resuming interrupted training from a specific checkpoint.  Therefore, there's no specific method.

True answer: from_pretrained()

  9%|▉         | 6/65 [00:33<05:34,  5.68s/it]

=======================================================
Question: What is the purpose of Diffusers library?

Answer: The Diffusers library provides tools for using and training diffusion models, primarily for image generation and manipulation.

True answer: To serve as a modular toolbox for both inference and training of state-of-the-art pretrained diffusion models across multiple modalities.

 11%|█         | 7/65 [00:39<05:26,  5.63s/it]

=======================================================
Question: What method does the EulerAncestralDiscreteScheduler use for sampling?

Answer: The EulerAncestralDiscreteScheduler uses ancestral sampling.

True answer: Ancestral sampling with Euler method steps.

 12%|█▏        | 8/65 [00:44<05:17,  5.57s/it]

=======================================================
Question: What is the name of the large multimodal model that can solve image-text tasks and is based on Flamingo?

Answer: There isn't a single, widely known, large multimodal model explicitly named and publicly released as a direct, large-scale successor to Flamingo that focuses on image-text tasks.  While Flamingo's architecture has likely influenced subsequent models, a specific named model fitting that description doesn't exist in common knowledge.

True answer: IDEFICS

 14%|█▍        | 9/65 [00:50<05:15,  5.64s/it]

=======================================================
Question: What is the purpose of the `gradio.Blocks` API?

Answer: The `gradio.Blocks` API provides a way to build custom, complex user interfaces for Gradio applications beyond the simple interfaces offered by individual Gradio components.  It allows for more sophisticated layout and control flow.

True answer: The `gradio.Blocks` API allows you to have full control over the data flows and layout of your application, enabling the building of complex, multi-step applications.

 15%|█▌        | 10/65 [00:56<05:11,  5.66s/it]

=======================================================
Question: What is the purpose of the two-stage model proposed in the paper "Hierarchical Text-Conditional Image Generation with CLIP Latents"?

Answer: The two-stage model in "Hierarchical Text-Conditional Image Generation with CLIP Latents" separates text-to-image generation into a CLIP latent text embedding stage and an image generation stage.  This allows for better control over image generation and improved quality by leveraging CLIP's powerful text understanding in the first stage, then using that embedding to guide a more efficient image generation process in the second.

True answer: The purpose of the two-stage model is to generate a CLIP image embedding given a text caption and then generate an image conditioned on the image embedding.

 17%|█▋        | 11/65 [01:02<05:09,  5.74s/it]

=======================================================
Question: What command is used to install the requirements for a research project using 🤗 Transformers?

Answer: `pip install -r requirements.txt`  (assuming a `requirements.txt` file lists the necessary packages).

True answer: pip install -r requirements.txt

 18%|█▊        | 12/65 [01:07<05:01,  5.68s/it]

=======================================================
Question: What task does the `roberta-large-mnli` checkpoint perform?

Answer: The `roberta-large-mnli` checkpoint performs natural language inference (NLI), specifically trained on the Multi-Genre Natural Language Inference (MNLI) dataset.  It determines the logical relationship (entailment, contradiction, or neutral) between a pair of sentences.

True answer: Text classification

 20%|██        | 13/65 [01:13<04:56,  5.71s/it]

=======================================================
Question: What service is replacing the Paid tier of the Inference API at Hugging Face?

Answer: There is no single service directly replacing the paid Inference API tier at Hugging Face.  Hugging Face is transitioning to a usage-based pricing model across all tiers, including previously free options.

True answer: Inference Endpoints

 22%|██▏       | 14/65 [01:19<04:50,  5.69s/it]

=======================================================
Question: What architectural feature does SqueezeBERT use instead of fully-connected layers for the Q, K, V, and FFN layers?

Answer: SqueezeBERT uses 1D convolutions instead of fully-connected layers for the Q, K, V, and FFN layers.

True answer: Grouped convolutions

 23%|██▎       | 15/65 [01:24<04:42,  5.65s/it]

=======================================================
Question: What type of license is the HuggingFace Team's software distributed under?

Answer: The Hugging Face team distributes its software under a variety of licenses, depending on the specific project.  There's no single answer.

True answer: Apache License, Version 2.0

 25%|██▍       | 16/65 [01:30<04:35,  5.63s/it]

=======================================================
Question: What are the two parameter-reduction techniques proposed in the ALBERT model to lower memory consumption and increase training speed?

Answer: ALBERT uses two parameter-reduction techniques:  factorized embedding parameterization and parameter sharing.

True answer: Splitting the embedding matrix into two smaller matrices and using repeating layers split among groups.

 26%|██▌       | 17/65 [01:35<04:28,  5.60s/it]

=======================================================
Question: What are the three main steps for fine-tuning a model with the 🤗 Datasets library?

Answer: 1. **Load and preprocess data:**  Load your dataset using `load_dataset`, then format it appropriately for your model (e.g., tokenization, creating input/output pairs).

2. **Fine-tune the model:** Use a Trainer object from the `transformers` library, specifying your model, dataset, and training hyperparameters.

3. **Evaluate the model:** Assess performance on a held-out evaluation set using metrics relevant to your task.

True answer: 1. Load a dataset from the Hugging Face Hub. 2. Preprocess the data with `Dataset.map()`. 3. Load and compute metrics.

 28%|██▊       | 18/65 [01:41<04:28,  5.72s/it]

=======================================================
Question: What is the maximum improvement in throughput achieved by Hugging Face Infinity compared to vanilla transformers?

Answer: The maximum throughput improvement of Hugging Face Infinity over vanilla Transformers is not definitively quantifiable.  Improvements vary significantly depending on hardware, model size, and specific tasks.  While Infinity aims for substantial speedups,  no single maximum percentage increase can be stated.

True answer: +800%

 29%|██▉       | 19/65 [01:47<04:23,  5.72s/it]

=======================================================
Question: What is the command to upload a spaCy pipeline to the Hugging Face Hub?

Answer: There's no single command to upload a spaCy pipeline directly to the Hugging Face Hub.  Hugging Face primarily works with transformers-based models.  You would need to convert your spaCy pipeline to a compatible format (likely PyTorch or TensorFlow) before uploading.

True answer: python -m spacy huggingface-hub push en_ner_fashion-0.0.0-py3-none-any.whl

 31%|███       | 20/65 [01:53<04:17,  5.72s/it]

=======================================================
Question: What is the time and memory complexity of the Nyströmformer's approximation of self-attention?

Answer: The time complexity of the Nyströmformer's approximation of self-attention is approximately O(N*M + M²*d), where N is the sequence length, M is the number of sampled landmarks, and d is the embedding dimension.  The memory complexity is approximately O(N*d + M*d).  These complexities are approximate and depend on specific implementation details.

True answer: O(n)

 32%|███▏      | 21/65 [01:59<04:14,  5.79s/it]

=======================================================
Question: What is the goal of the Named Entity Recognition task in token classification?

Answer: The goal of Named Entity Recognition (NER) in token classification is to identify and classify named entities mentioned in unstructured text into predefined categories (e.g., person, organization, location, date).

True answer: The goal of the Named Entity Recognition task is to find the entities in a piece of text, such as person, location, or organization.

 34%|███▍      | 22/65 [02:04<04:07,  5.75s/it]

=======================================================
Question: What is the resolution of images used by the CLIPSeg model?

Answer: CLIPSeg doesn't have a fixed resolution.  The resolution of the images it processes is variable and depends on the input image provided to the model.

True answer: 352 x 352 pixels

 35%|███▌      | 23/65 [02:10<03:59,  5.70s/it]

=======================================================
Question: What can you use Gradio for?

Answer: Gradio lets you quickly create user interfaces for machine learning models, allowing easy sharing and demonstration of your work.

True answer: Create a demo for your machine learning model, share your machine learning model with others, and debug your model.

 37%|███▋      | 24/65 [02:16<03:52,  5.66s/it]

=======================================================
Question: What TensorFlow API function is used to load a saved tensor file?

Answer: There's no single TensorFlow API function to load *any* saved tensor file.  The appropriate function depends on the format the tensor was saved in (e.g., `.pb`, SavedModel, HDF5).  More information is needed.

True answer: safetensors.tensorflow.load_file

 38%|███▊      | 25/65 [02:21<03:47,  5.69s/it]

=======================================================
Question: Where can you access the logs of your Endpoints in Hugging Face Endpoints?

Answer: Hugging Face doesn't provide a publicly accessible interface to directly view Endpoints' logs in the same way some other services might.  Log access details are likely found within the Hugging Face console or API documentation specific to your deployment, but the exact location isn't universally specified.

True answer: In the "Logs" tab of your Endpoint through the UI.

 40%|████      | 26/65 [02:27<03:42,  5.70s/it]

=======================================================
Question: What is the latest task added to Hugging Face AutoTrain for Computer Vision?

Answer: I do not have access to real-time information, including updates to Hugging Face AutoTrain.  Therefore, I cannot definitively answer what the latest added task is.

True answer: Image Classification

 42%|████▏     | 27/65 [02:33<03:35,  5.68s/it]

=======================================================
Question: What is the default repository type created by the `create_repo` function on Hugging Face Hub?

Answer: The `create_repo` function on Hugging Face Hub defaults to creating a model repository.

True answer: model

 43%|████▎     | 28/65 [02:38<03:28,  5.64s/it]

=======================================================
Question: How many splits does the "duorc" dataset have?

Answer: The question cannot be answered definitively.  There is no known publicly available or standard dataset called "duorc".

True answer: Six

 45%|████▍     | 29/65 [02:44<03:22,  5.61s/it]

=======================================================
Question: What is the purpose of Fully Sharded Data Parallel (FSDP) in distributed training?

Answer: FSDP's purpose in distributed training is to reduce memory usage per device by sharding model parameters and optimizer states across multiple devices, enabling training of significantly larger models than would otherwise be possible.

True answer: FSDP is developed for distributed training of large pretrained models up to 1T parameters by sharding the model parameters, gradients, and optimizer states across data parallel processes.

 46%|████▌     | 30/65 [02:49<03:16,  5.62s/it]

=======================================================
Question: What file format is used to save and store PyTorch model weights more securely than `.bin` files?

Answer: There isn't a single file format inherently "more secure" than `.bin` for storing PyTorch model weights.  Security depends on broader practices like encryption and access control, not the file format itself.

True answer: `.safetensors`

 48%|████▊     | 31/65 [02:55<03:11,  5.63s/it]

=======================================================
Question: What type of security certification does Hugging Face have?

Answer: Hugging Face does not publicly advertise specific security certifications like ISO 27001 or SOC 2.  The type of security measures they employ is not publicly specified in the form of a certification.

True answer: SOC2 Type 2 certified

 49%|████▉     | 32/65 [03:01<03:06,  5.64s/it]

=======================================================
Question: What do RAG models combine to generate outputs?

Answer: RAG models combine a large language model (LLM) with a retrieval system over an external knowledge base.

True answer: Pretrained dense retrieval (DPR) and sequence-to-sequence models.

 51%|█████     | 33/65 [03:06<02:59,  5.61s/it]

=======================================================
Question: What library does MarkupLMFeatureExtractor use to extract data from HTML and XML files?

Answer: MarkupLMFeatureExtractor doesn't use a specific named library like Beautiful Soup or lxml.  It's likely to use internal, custom parsing logic tailored to its specific needs for extracting features from markup.

True answer: Beautiful Soup

 52%|█████▏    | 34/65 [03:12<02:54,  5.62s/it]

=======================================================
Question: What is the file size limit for syncing to HF Spaces without using Git-LFS?

Answer: There's no publicly stated file size limit for syncing to Hugging Face Spaces without Git LFS.  However, practical limits exist due to browser upload limitations and the overall resources available to the Spaces service.  Large files will likely fail to upload or cause significant delays.

True answer: 10MB

 54%|█████▍    | 35/65 [03:18<02:49,  5.66s/it]

=======================================================
Question: What is the title of the paper introducing the ByT5 model?

Answer: There is no single paper explicitly titled "ByT5".  The ByT5 model is an extension or adaptation of the T5 model, and its details are likely presented within papers discussing improvements or applications of T5, rather than a standalone paper with that exact title.

True answer: ByT5: Towards a token-free future with pre-trained byte-to-byte models

 55%|█████▌    | 36/65 [03:23<02:44,  5.69s/it]

=======================================================
Question: What is the dimension of the feature vector for the base BERT model?

Answer: 768

True answer: 768

 57%|█████▋    | 37/65 [03:29<02:36,  5.60s/it]

=======================================================
Question: What special identifier does the WordPiece Model use for continuing subwords?

Answer: The WordPiece model uses the "##" prefix to indicate continuing subwords.

True answer: ##

 58%|█████▊    | 38/65 [03:34<02:30,  5.57s/it]

=======================================================
Question: What is the purpose of the 🧨 Diffusers tutorials?

Answer: The purpose of the Diffusers tutorials is to teach users how to use the Diffusers library, a Python library for diffusion models, to generate and manipulate images.

True answer: To provide a gentle introduction to diffusion models and help understand the library fundamentals.

 60%|██████    | 39/65 [03:40<02:25,  5.58s/it]

=======================================================
Question: What is the default setting for the `allow_flagging` parameter in Gradio's `Interface`?

Answer: True

True answer: "manual"

 62%|██████▏   | 40/65 [03:45<02:18,  5.53s/it]

=======================================================
Question: Where can the full code for the Stable Diffusion demo be found?

Answer: The full code for the Stable Diffusion demo isn't in a single, publicly accessible location.  Different demos use different codebases and implementations, often incorporating various libraries and modifications.  The core Stable Diffusion model itself is available open-source, but complete demo code varies depending on the specific features and interface.

True answer: https://hf.co/spaces/stabilityai/stable-diffusion/tree/main

 63%|██████▎   | 41/65 [03:51<02:14,  5.61s/it]

=======================================================
Question: What transformation does the FNet model use to replace the self-attention layer in a BERT model?

Answer: FNet replaces the self-attention layer in BERT with a Fourier transform-based operation.

True answer: Fourier transform

 65%|██████▍   | 42/65 [03:57<02:08,  5.59s/it]

=======================================================
Question: What type of test should typically accompany a bug fix in Gradio's testing strategy?

Answer: Unit tests and integration tests, focusing on the specific functionality addressed by the bug fix.

True answer: Dynamic code test

 66%|██████▌   | 43/65 [04:02<02:02,  5.57s/it]

=======================================================
Question: How can you force mixed precision training when initializing the Accelerator in 🤗 Accelerate?

Answer: You can't directly "force" mixed precision in `Accelerator` initialization.  Mixed precision is enabled through the `mixed_precision` argument during `Accelerator.prepare`  (or similar methods depending on the Accelerate version), not during initialization.

True answer: By passing `fp16=True` to the Accelerator init.

 68%|██████▊   | 44/65 [04:08<01:58,  5.62s/it]

=======================================================
Question: What is the purpose of tokenizers in the NLP pipeline?

Answer: Tokenizers break down text into individual units (tokens), like words or sub-words, preparing it for further NLP processing.

True answer: To translate text into data that can be processed by the model.

 69%|██████▉   | 45/65 [04:14<01:52,  5.61s/it]

=======================================================
Question: What is the purpose of the Safety Checker in the Diffusers library?

Answer: The Diffusers library doesn't have a component explicitly named "Safety Checker".  There's no standard feature with that name.  The question is therefore unanswerable.

True answer: The Safety Checker checks and compares the class probability of a set of hard-coded harmful concepts in the embedding space against an image after it has been generated to mitigate the risk of generating harmful content.

 71%|███████   | 46/65 [04:19<01:46,  5.63s/it]

=======================================================
Question: What Python class allows you to retrieve Discussions and Pull Requests from a given repository on the Hugging Face Hub?

Answer: There's no single built-in Python class specifically for retrieving Discussions and Pull Requests from the Hugging Face Hub.  You'll need to use the Hugging Face Hub API and likely a library like `requests` to make HTTP requests.

True answer: HfApi

 72%|███████▏  | 47/65 [04:25<01:41,  5.65s/it]

=======================================================
Question: What is the name of the new library introduced by Hugging Face for hosting scikit-learn models?

Answer: There is no publicly announced new Hugging Face library specifically for hosting scikit-learn models.  Hugging Face primarily focuses on transformer-based models.

True answer: Skops

 74%|███████▍  | 48/65 [04:30<01:35,  5.63s/it]

=======================================================
Question: What is the purpose of Textual Inversion?

Answer: Textual inversion in the context of large language models (LLMs) allows users to create custom embeddings for specific concepts or styles, enabling the model to generate text more closely aligned with those concepts, even if they aren't explicitly represented in the model's training data.

True answer: Textual Inversion is a training method for personalizing models by learning new text embeddings from a few example images.

 75%|███████▌  | 49/65 [04:36<01:30,  5.67s/it]

=======================================================
Question: What is the recommended multiple of batch size for fp16 data type on an A100 GPU?

Answer: There's no single universally recommended multiple of batch size for fp16 on an A100 GPU.  The optimal batch size depends heavily on the specific model architecture, the dataset size, and available memory.  Experimentation is necessary to find the best value.

True answer: 64

 77%|███████▋  | 50/65 [04:42<01:25,  5.70s/it]

=======================================================
Question: How do you run a Gradio Blocks app in reload mode using a Python IDE?

Answer: There's no built-in "reload mode" in Gradio Blocks specifically.  However, you can achieve a similar effect by using your IDE's auto-reload functionality (if available) or by restarting the Gradio app manually after making code changes.  The exact method depends on your IDE (e.g., VS Code's live server extensions, PyCharm's run configurations).

True answer: Run `gradio run.py` in the terminal.

 78%|███████▊  | 51/65 [04:48<01:20,  5.77s/it]

=======================================================
Question: How can you install the Hugging Face Unity API in your Unity project?

Answer: There's no official "Hugging Face Unity API."  Hugging Face provides APIs for accessing their models, but these are typically used through a scripting language like Python within a separate process that communicates with Unity (e.g., via a REST API or gRPC).  Direct installation as a Unity package is not possible.

True answer: To install the Hugging Face Unity API in your Unity project, go to `Window` -> `Package Manager`, click `+` and select `Add Package from git URL`, then enter `https://github.com/huggingface/unity-api.git`.

 80%|████████  | 52/65 [04:54<01:15,  5.78s/it]

=======================================================
Question: What is the pretraining objective of the Wav2Vec2 context network?

Answer: The Wav2Vec 2.0 context network's pretraining objective is to predict masked latent speech representations.

True answer: The pretraining objective of the Wav2Vec2 context network is a contrastive task where the model has to predict the true quantized speech representation of the masked prediction from a set of false ones.

 82%|████████▏ | 53/65 [04:59<01:08,  5.71s/it]

=======================================================
Question: What is the default checkpoint used by the sentiment analysis pipeline in the Transformers library?

Answer: The Transformers library doesn't have a single, universally "default" checkpoint for sentiment analysis.  The choice depends on the specific model and task you select.  The library offers many pre-trained models suitable for sentiment analysis, each with its own checkpoint.

True answer: distilbert base uncased finetuned sst2 english

 83%|████████▎ | 54/65 [05:05<01:02,  5.72s/it]

=======================================================
Question: What is the purpose of the notebook "How to use DeepSpeed to train models with billions of parameters on Habana Gaudi"?

Answer: The purpose of a notebook titled "How to use DeepSpeed to train models with billions of parameters on Habana Gaudi" is to provide a tutorial or guide on leveraging DeepSpeed's capabilities to efficiently train extremely large language models (LLMs) on Habana Gaudi hardware.

True answer: To show how to use DeepSpeed to pre-train/fine-tune the 1.6B-parameter GPT2-XL for causal language modeling on Habana Gaudi.

 85%|████████▍ | 55/65 [05:11<00:57,  5.74s/it]

=======================================================
Question: What command line module does PyTorch provide to run a script on multiple GPUs?

Answer: PyTorch doesn't provide a single command-line module specifically for running a script on multiple GPUs.  Data parallelism is typically handled within the Python script itself using `torch.nn.DataParallel` or `torch.nn.parallel.DistributedDataParallel`.

True answer: torchrun

 86%|████████▌ | 56/65 [05:17<00:51,  5.74s/it]

=======================================================
Question: What is the most popular vision transformer model on the Hugging Face Model Hub for image classification?

Answer: There's no single definitive answer to what the *most* popular vision transformer model is on Hugging Face.  Popularity metrics (downloads, stars, etc.) fluctuate.  However, models from the ViT family (like those from Google) and Swin Transformer are consistently among the most widely used and downloaded.

True answer: google/vit-base-patch16-224

 88%|████████▊ | 57/65 [05:22<00:46,  5.76s/it]

=======================================================
Question: What is the command to upload an ESPnet model to a Hugging Face repository?

Answer: There's no single command to upload an ESPnet model to Hugging Face.  You need to use the Hugging Face CLI and potentially other tools to prepare and upload the model's weights, configuration, and potentially other associated files as a suitable model archive.

True answer: ./run.sh --stage 15 --skip_upload_hf false --hf_repo username/model_repo

 89%|████████▉ | 58/65 [05:28<00:40,  5.75s/it]

=======================================================
Question: What file should be added to a model repository to install custom Python dependencies for Inference Endpoints?

Answer: `requirements.txt`

True answer: requirements.txt

 91%|█████████ | 59/65 [05:34<00:33,  5.66s/it]

=======================================================
Question: How many images are needed to teach new concepts to Stable Diffusion using Textual Inversion?

Answer: The number of images needed for Textual Inversion in Stable Diffusion varies greatly depending on the concept's complexity and the desired quality of results.  There's no single definitive answer.  A few images might suffice for simple concepts, while dozens or even hundreds might be necessary for complex ones.

True answer: 3-5 images

 92%|█████████▏| 60/65 [05:39<00:28,  5.70s/it]

=======================================================
Question: What is the maximum size of a model checkpoint before it is automatically sharded in Transformers version 4.18.0?

Answer: There is no automatic sharding of model checkpoints in Transformers 4.18.0 based on size.  Sharding is a user-controlled process, not an automatic feature triggered by checkpoint size.

True answer: 10GB

 94%|█████████▍| 61/65 [05:45<00:22,  5.69s/it]

=======================================================
Question: What is the purpose of Weights and Biases (W&B) for data scientists and machine learning scientists?

Answer: Weights & Biases (W&B) is a platform for experiment tracking, visualization, and collaboration in machine learning.  It helps data scientists and ML scientists manage and understand their model training runs, improving efficiency and reproducibility.

True answer: To track their machine learning experiments at every stage, from training to production.

 95%|█████████▌| 62/65 [05:51<00:17,  5.68s/it]

=======================================================
Question: What is the name of the open-source library created by Hugging Face to simplify Transformer acceleration?

Answer: Accelerate

True answer: Optimum

 97%|█████████▋| 63/65 [05:56<00:11,  5.59s/it]

=======================================================
Question: What parameter is used to ensure that elements in a row have the same height in Gradio?

Answer: There's no single Gradio parameter to directly enforce equal row height.  Layout management is handled indirectly through CSS or by structuring the components within containers that inherently manage height (e.g., using a layout that fills available space).

True answer: equal_height

 98%|█████████▊| 64/65 [06:02<00:05,  5.63s/it]

=======================================================
Question: What is the command to install the latest version of Optimum with OpenVINO support?

Answer: There is no single command to install the "latest version of Optimum with OpenVINO support".  The installation process depends on the specific Optimum library (e.g., Optimum-Intel), the operating system, and the desired installation method (e.g., pip, conda).  More information is needed.

True answer: pip install --upgrade-strategy eager optimum["openvino"]

100%|██████████| 65/65 [06:08<00:00,  5.66s/it]

In [60]:
EVALUATION_PROMPT = """You are a fair evaluator language model.

You will be given an instruction, a response to evaluate, a reference answer that gets a score of 3, and a score rubric representing a evaluation criteria are given.
1. Write a detailed feedback that assess the quality of the response strictly based on the given score rubric, not evaluating in general.
2. After writing a feedback, write a score that is an integer between 1 and 3. You should refer to the score rubric.
3. The output format should look as follows: \"Feedback: {{write a feedback for criteria}} [RESULT] {{an integer number between 1 and 3}}\"
4. Please do not generate any other opening, closing, and explanations. Be sure to include [RESULT] in your output.
5. Do not score conciseness: a correct answer that covers the question should receive max score, even if it contains additional useless information.

The instruction to evaluate:
{instruction}

Response to evaluate:
{response}

Reference Answer (Score 3):
{reference_answer}

Score Rubrics:
[Is the response complete, accurate, and factual based on the reference answer?]
Score 1: The response is completely incomplete, inaccurate, and/or not factual.
Score 2: The response is somewhat complete, accurate, and/or factual.
Score 3: The response is completely complete, accurate, and/or factual.

Feedback:"""

In [61]:
# evaluation

evaluation_llm_name = "gemini-2.0-flash"
evaluation_llm = OpenAIServerModel(
    model_id=evaluation_llm_name,
    api_base="https://generativelanguage.googleapis.com/v1beta/openai/",
    api_key=os.getenv("Gemini_API_KEY2"),
    temperature=0)

results = {}
for system_type, outputs in [
    ("agentic_rag", outputs_agentic_rag),
    ("standard_rag", outputs_standard_rag),
    ("standard", outputs_standard),
]:
    print("evaluating {}".format(system_type))

    for experiment in tqdm(outputs):
        eval_prompt = EVALUATION_PROMPT.format(
            instruction=experiment["question"],
            response=experiment["generated_answer"],
            reference_answer=experiment["true_answer"],
        )
        messages = [
            {
                "role": "system",
                "content": "You are a fair evaluator language model."
            },
            {
                "role": "user",
                "content": eval_prompt
            },
        ]

        eval_result = evaluation_llm.generate(messages).content

        try:
            feedback, score = [
                item.strip() for item in eval_result.split("[RESULT]")
            ]
            experiment["eval_score_LLM_judge"] = score
            experiment["eval_feedback_LLM_judge"] = feedback
        except:
            print(f"Parsing failed - output was: {eval_result}")

        time.sleep(5)

    results[system_type] = pd.DataFrame.from_dict(outputs)
    results[system_type] = results[
        system_type].loc[~results[system_type]["generated_answer"].str.
                         contains("Error", na=False)]

evaluating agentic_rag

100%|██████████| 65/65 [08:44<00:00,  8.07s/it]

evaluating standard_rag

100%|██████████| 65/65 [06:13<00:00,  5.75s/it]

evaluating standard

100%|██████████| 65/65 [06:18<00:00,  5.83s/it]

In [62]:
DEFAULT_SCORE = 2  # Give average score whenever scoring fails


def fill_score(x):
    try:
        return int(x)
    except:
        return DEFAULT_SCORE


for system_type, outputs in [
    ("agentic_rag", outputs_agentic_rag),
    ("standard_rag", outputs_standard_rag),
    ("standard", outputs_standard),
]:

    results[system_type]["eval_score_LLM_judge_int"] = (
        results[system_type]["eval_score_LLM_judge"].fillna(
            DEFAULT_SCORE).apply(fill_score))
    results[system_type]["eval_score_LLM_judge_int"] = (
        results[system_type]["eval_score_LLM_judge_int"] - 1) / 2

    print(
        f"Average score for {system_type} : {results[system_type]['eval_score_LLM_judge_int'].mean()*100:.1f}%"
    )

Average score for agentic_rag : 91.5%
Average score for standard_rag : 85.4%
Average score for standard : 35.4%

In [63]:
results["agentic_rag"]

,question,true_answer,source_doc,generated_answer,eval_score_LLM_judge,eval_feedback_LLM_judge,eval_score_LLM_judge_int
0,What architecture is the `tokenizers-linux-x64...,x86_64-unknown-linux-musl,huggingface/tokenizers/blob/main/bindings/node...,x86_64-unknown-linux-musl,3,"The response is completely complete, accurate,...",1.0
1,What is the purpose of the BLIP-Diffusion mode...,The BLIP-Diffusion model is designed for contr...,huggingface/diffusers/blob/main/docs/source/en...,BLIP-Diffusion enables zero-shot subject-drive...,2,The response mentions two capabilities of the ...,0.5
2,How can a user claim authorship of a paper on ...,By clicking their name on the corresponding Pa...,huggingface/hub-docs/blob/main/docs/hub/paper-...,"To claim authorship of a paper on the Hub, if ...",3,The response accurately describes the process ...,1.0
3,What is the purpose of the /healthcheck endpoi...,Ensure the app is running,huggingface/datasets-server/blob/main/services...,The `/healthcheck` endpoint in the Datasets se...,3,The response accurately and completely answers...,1.0
4,What is the default context window size for Lo...,127 tokens,huggingface/transformers/blob/main/docs/source...,127,3,The response accurately states the default con...,1.0
...,...,...,...,...,...,...,...
60,What is the maximum size of a model checkpoint...,10GB,huggingface/transformers/blob/main/docs/source...,10GB,3,The response accurately and completely answers...,1.0
61,What is the purpose of Weights and Biases (W&B...,To track their machine learning experiments at...,gradio-app/gradio/blob/main/guides/06_integrat...,Weights & Biases (W&B) is a tool used for logg...,3,The response accurately describes the purpose ...,1.0
62,What is the name of the open-source library cr...,Optimum,huggingface/blog/blob/main/intel.md,Optimum,3,"The response ""Optimum"" is a complete and accur...",1.0
63,What parameter is used to ensure that elements...,equal_height,gradio-app/gradio/blob/main/guides/cn/03_build...,"The `equal_height` parameter, passed to the `....",3,The response accurately identifies the `equal_...,1.0
64,What is the command to install the latest vers...,"pip install --upgrade-strategy eager optimum[""...",huggingface/diffusers/blob/main/docs/source/en...,pip install --upgrade-strategy eager optimum[o...,3,The response is complete and accurate. It prov...,1.0

In [64]:
results["standard_rag"]

,question,true_answer,source_doc,generated_answer,eval_score_LLM_judge,eval_feedback_LLM_judge,eval_score_LLM_judge_int
0,What architecture is the `tokenizers-linux-x64...,x86_64-unknown-linux-musl,huggingface/tokenizers/blob/main/bindings/node...,The `tokenizers-linux-x64-musl` binary is desi...,3,The response accurately and completely identif...,1.0
1,What is the purpose of the BLIP-Diffusion mode...,The BLIP-Diffusion model is designed for contr...,huggingface/diffusers/blob/main/docs/source/en...,The purpose of the BLIP-Diffusion model is to ...,3,The response accurately describes the purpose ...,1.0
2,How can a user claim authorship of a paper on ...,By clicking their name on the corresponding Pa...,huggingface/hub-docs/blob/main/docs/hub/paper-...,If the paper is not automatically linked to yo...,3,The response accurately describes the process ...,1.0
3,What is the purpose of the /healthcheck endpoi...,Ensure the app is running,huggingface/datasets-server/blob/main/services...,The `/healthcheck` endpoint ensures the Datase...,3,The response accurately and completely describ...,1.0
4,What is the default context window size for Lo...,127 tokens,huggingface/transformers/blob/main/docs/source...,The default context window size for Local Atte...,3,The response accurately identifies the default...,1.0
...,...,...,...,...,...,...,...
60,What is the maximum size of a model checkpoint...,10GB,huggingface/transformers/blob/main/docs/source...,"In Transformers version 4.18.0, model checkpoi...",3,The response accurately states that model chec...,1.0
61,What is the purpose of Weights and Biases (W&B...,To track their machine learning experiments at...,gradio-app/gradio/blob/main/guides/06_integrat...,Weights and Biases (W&B) enables data scientis...,3,The response accurately describes the purpose ...,1.0
62,What is the name of the open-source library cr...,Optimum,huggingface/blog/blob/main/intel.md,Accelerate\n,1,The response provides an incorrect answer to t...,0.0
63,What parameter is used to ensure that elements...,equal_height,gradio-app/gradio/blob/main/guides/cn/03_build...,"The `equal_height` parameter, passed to the `....",3,The response includes the correct parameter na...,1.0
64,What is the command to install the latest vers...,"pip install --upgrade-strategy eager optimum[""...",huggingface/diffusers/blob/main/docs/source/en...,```bash\npip install --upgrade-strategy eager ...,2,The response is almost complete and accurate b...,0.5

In [65]:
# save all results

# Create a dictionary of JSON strings
json_results = {}
results_dir = "results"

for system_type, df in results.items():
    json_results[system_type] = json.loads(df.to_json(orient='records'))

save_json_path = os.path.join(results_dir, model_name + "_vect400_t0.2.json")

# Save to a file
with open(save_json_path, 'w') as f:
    json.dump(json_results, f, indent=4)

In [ ]:
# load results

results_dir = "results"
load_model_name = ""
load_json_path = os.path.join(results_dir,
                              load_model_name + "_vect400_t0.2.json")

# Read the JSON file
with open('load_json_path', 'r') as f:
    loaded_json = json.load(f)

# Convert back to a dictionary of DataFrames
loaded_results = {}
for system_type, records in loaded_json.items():
    loaded_results[system_type] = pd.DataFrame.from_records(records)

results = loaded_results