In [ ]:
from huggingface_hub import notebook_login

notebook_login()

In [46]:
import os
import datasets
import logging
import json
import threading
import time
import pandas as pd
from concurrent.futures import ThreadPoolExecutor
from dotenv import load_dotenv
from langchain.docstore.document import Document
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_community.vectorstores.utils import DistanceStrategy
from langchain_core.vectorstores import VectorStore
from smolagents import OpenAIServerModel, CodeAgent, Tool
from smolagents.monitoring import LogLevel
from transformers import AutoTokenizer
from tqdm import tqdm
from typing import List, Optional
from utils.blablador import Models

In [ ]:
## old vector creator
def sanitize_filename(dataset_name):
    """Convert dataset name to a valid filename by replacing '/' with '_'"""
    return dataset_name.replace("/", "_")


def load_or_create_vectordb(dataset_name):
    """Load existing vectordb or create new one if it doesn't exist"""

    # Create sanitized filename
    safe_filename = sanitize_filename(dataset_name)
    vectordb_path = os.path.join("vectordb", safe_filename)

    # Check if vectordb already exists
    if os.path.exists(vectordb_path):
        print(f"Found existing vector database at {vectordb_path}")
        print("Loading existing vector database...")

        # Load the embedding model (needed for loading)
        embedding_model = HuggingFaceEmbeddings(
            model_name="thenlper/gte-small")

        # Load the existing vectordb
        vectordb = FAISS.load_local(vectordb_path,
                                    embedding_model,
                                    allow_dangerous_deserialization=True)
        print("Vector database loaded successfully!")
        return vectordb

    else:
        print(f"No existing vector database found at {vectordb_path}")
        print("Creating new vector database...")

        # Load and process the dataset
        knowledge_base = datasets.load_dataset(dataset_name, split="train")
        source_docs = [
            Document(page_content=doc["text"],
                     metadata={"source": doc["source"].split("/")[1]})
            for doc in knowledge_base
        ]

        # Initialize text splitter
        text_splitter = RecursiveCharacterTextSplitter.from_huggingface_tokenizer(
            AutoTokenizer.from_pretrained("thenlper/gte-small"),
            chunk_size=200,
            chunk_overlap=20,
            add_start_index=True,
            strip_whitespace=True,
            separators=["\n\n", "\n", ".", " ", ""],
        )

        # Split docs and keep only unique ones
        print("Splitting documents...")
        docs_processed = []
        unique_texts = {}
        for doc in tqdm(source_docs):
            new_docs = text_splitter.split_documents([doc])
            for new_doc in new_docs:
                if new_doc.page_content not in unique_texts:
                    unique_texts[new_doc.page_content] = True
                    docs_processed.append(new_doc)

        print("Embedding documents...")
        embedding_model = HuggingFaceEmbeddings(
            model_name="thenlper/gte-small")
        vectordb = FAISS.from_documents(
            documents=docs_processed,
            embedding=embedding_model,
            distance_strategy=DistanceStrategy.COSINE,
        )

        # Save the vectordb
        print(f"Saving vector database to {vectordb_path}...")
        vectordb.save_local(vectordb_path)
        print("Vector database saved successfully!")

        return vectordb


# Usage
dataset_name = "m-ric/huggingface_doc"
vectordb = load_or_create_vectordb(dataset_name)

print(f"Vector database ready with {vectordb.index.ntotal} vectors!")

In [2]:
## Load or create vector database parallelly


def sanitize_filename(dataset_name: str) -> str:
    """Convert dataset name to a valid filename by replacing '/' with '_'"""
    return dataset_name.replace("/", "_")


class DocumentProcessor:
    """Thread-safe document processor to avoid pickling issues"""

    def __init__(self, chunk_size: int = 200, chunk_overlap: int = 20):
        self.text_splitter = None
        self.chunk_size = chunk_size
        self.chunk_overlap = chunk_overlap
        self._lock = threading.Lock()

    def _get_text_splitter(self):
        """Initialize text splitter in thread-local manner"""
        if self.text_splitter is None:
            with self._lock:
                if self.text_splitter is None:
                    self.text_splitter = RecursiveCharacterTextSplitter.from_huggingface_tokenizer(
                        AutoTokenizer.from_pretrained("thenlper/gte-small"),
                        chunk_size=self.chunk_size,
                        chunk_overlap=self.chunk_overlap,
                        add_start_index=True,
                        strip_whitespace=True,
                        separators=["\n\n", "\n", ".", " ", ""],
                    )
        return self.text_splitter

    def split_documents_chunk(self,
                              docs_chunk: List[Document]) -> List[Document]:
        """Split a chunk of documents using the text splitter"""
        text_splitter = self._get_text_splitter()
        processed_docs = []
        for doc in docs_chunk:
            new_docs = text_splitter.split_documents([doc])
            processed_docs.extend(new_docs)
        return processed_docs


def parallel_document_splitting(
        source_docs: List[Document],
        max_workers: int = None,
        chunk_size: int = 100,
        text_chunk_size: int = 200,
        text_chunk_overlap: int = 20) -> List[Document]:
    """Split documents in parallel using ThreadPoolExecutor"""
    if max_workers is None:
        max_workers = min(8, len(source_docs) // chunk_size + 1)

    print(f"Splitting documents in parallel using {max_workers} threads...")

    # Split source_docs into chunks for parallel processing
    doc_chunks = [
        source_docs[i:i + chunk_size]
        for i in range(0, len(source_docs), chunk_size)
    ]

    # Create a shared processor instance with configurable chunk size
    processor = DocumentProcessor(text_chunk_size, text_chunk_overlap)

    # Use ThreadPoolExecutor instead of ProcessPoolExecutor
    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        # Process chunks in parallel with progress bar
        results = list(
            tqdm(executor.map(processor.split_documents_chunk, doc_chunks),
                 total=len(doc_chunks),
                 desc="Processing document chunks"))

    # Flatten results
    all_processed_docs = []
    for chunk_result in results:
        all_processed_docs.extend(chunk_result)

    return all_processed_docs


def remove_duplicates(docs: List[Document]) -> List[Document]:
    """Remove duplicate documents based on page_content"""
    print("Removing duplicate documents...")
    unique_texts = set()
    unique_docs = []

    for doc in tqdm(docs, desc="Checking for duplicates"):
        if doc.page_content not in unique_texts:
            unique_texts.add(doc.page_content)
            unique_docs.append(doc)

    print(f"Removed {len(docs) - len(unique_docs)} duplicate documents")
    return unique_docs


def batch_embed_documents(docs: List[Document],
                          embedding_model,
                          batch_size: int = 100) -> FAISS:
    """Create FAISS vectorstore with batch processing for embeddings"""
    print(f"Embedding documents in batches of {batch_size}...")

    if not docs:
        raise ValueError("No documents to embed")

    # Create initial vectorstore with first batch
    first_batch = docs[:batch_size]
    print(f"Creating initial vectorstore with {len(first_batch)} documents...")

    vectordb = FAISS.from_documents(
        documents=first_batch,
        embedding=embedding_model,
        distance_strategy=DistanceStrategy.COSINE,
    )

    # Process remaining documents in batches
    remaining_docs = docs[batch_size:]
    if remaining_docs:
        total_batches = (len(remaining_docs) + batch_size - 1) // batch_size

        for i in tqdm(range(0, len(remaining_docs), batch_size),
                      desc="Adding document batches",
                      total=total_batches):
            batch = remaining_docs[i:i + batch_size]

            # Create temporary vectorstore for this batch
            batch_vectordb = FAISS.from_documents(
                documents=batch,
                embedding=embedding_model,
                distance_strategy=DistanceStrategy.COSINE,
            )

            # Merge with main vectorstore
            vectordb.merge_from(batch_vectordb)

    return vectordb


def sequential_document_splitting(
        source_docs: List[Document],
        text_chunk_size: int = 200,  # Add this parameter
        text_chunk_overlap: int = 20) -> List[Document]:
    """Fallback sequential document splitting if parallel processing fails"""
    print("Using sequential document splitting...")

    text_splitter = RecursiveCharacterTextSplitter.from_huggingface_tokenizer(
        AutoTokenizer.from_pretrained("thenlper/gte-small"),
        chunk_size=text_chunk_size,
        chunk_overlap=text_chunk_overlap,
        add_start_index=True,
        strip_whitespace=True,
        separators=["\n\n", "\n", ".", " ", ""],
    )

    docs_processed = []
    for doc in tqdm(source_docs, desc="Splitting documents"):
        new_docs = text_splitter.split_documents([doc])
        docs_processed.extend(new_docs)

    return docs_processed


def load_or_create_vectordb(dataset_name: str,
                            batch_size: int = 100,
                            max_workers: int = None,
                            doc_chunk_size: int = 100,
                            text_chunk_size: int = 200,
                            text_chunk_overlap: int = 20,
                            force_rebuild: bool = False,
                            use_parallel: bool = True) -> FAISS:
    """Load existing vectordb or create new one with optimized processing"""

    # Create sanitized filename
    safe_filename = sanitize_filename(dataset_name)
    vectordb_path = os.path.join(
        "vectordb",
        f"{safe_filename}_{text_chunk_size}")  # Include chunk size in filename

    # Check if vectordb already exists and not forcing rebuild
    if os.path.exists(vectordb_path) and not force_rebuild:
        print(f"Found existing vector database at {vectordb_path}")
        print("Loading existing vector database...")

        try:
            # Load the embedding model (needed for loading)
            embedding_model = HuggingFaceEmbeddings(
                model_name="thenlper/gte-small")

            # Load the existing vectordb
            vectordb = FAISS.load_local(vectordb_path,
                                        embedding_model,
                                        allow_dangerous_deserialization=True)
            print("Vector database loaded successfully!")
            return vectordb

        except Exception as e:
            print(f"Error loading existing vectordb: {e}")
            print("Creating new vector database...")

    else:
        if force_rebuild:
            print("Force rebuild requested. Creating new vector database...")
        else:
            print(f"No existing vector database found at {vectordb_path}")
            print("Creating new vector database...")

    # Load and process the dataset
    print("Loading dataset...")
    knowledge_base = datasets.load_dataset(dataset_name, split="train")
    source_docs = [
        Document(page_content=doc["text"],
                 metadata={"source": doc["source"].split("/")[1]})
        for doc in tqdm(knowledge_base, desc="Processing dataset")
    ]

    print(f"Loaded {len(source_docs)} documents from dataset")

    # Split documents (with fallback to sequential processing)
    try:
        if use_parallel and len(source_docs) > 50:
            docs_processed = parallel_document_splitting(
                source_docs, max_workers, doc_chunk_size, text_chunk_size,
                text_chunk_overlap)
        else:
            docs_processed = sequential_document_splitting(
                source_docs, text_chunk_size, text_chunk_overlap)

    except Exception as e:
        print(f"Parallel processing failed: {e}")
        print("Falling back to sequential processing...")
        docs_processed = sequential_document_splitting(
            source_docs, text_chunk_size,
            text_chunk_overlap)  # Pass new parameters

    print(f"Split into {len(docs_processed)} document chunks")

    # Remove duplicates
    docs_processed = remove_duplicates(docs_processed)

    print(f"Final document count after deduplication: {len(docs_processed)}")

    # Create embedding model
    print("Loading embedding model...")
    embedding_model = HuggingFaceEmbeddings(model_name="thenlper/gte-small")

    # Create vectordb with batch processing
    vectordb = batch_embed_documents(docs_processed, embedding_model,
                                     batch_size)

    # Save the vectordb
    print(f"Saving vector database to {vectordb_path}...")
    try:
        vectordb.save_local(vectordb_path)
        print("Vector database saved successfully!")
    except Exception as e:
        print(f"Error saving vectordb: {e}")
        print("Continuing without saving...")

    return vectordb


# Usage example with configurable parameters
dataset_name = "m-ric/huggingface_doc"

# Usage example with configurable chunk sizes
config = {
    "batch_size": 50,
    "max_workers": 4,
    "doc_chunk_size": 100,  # Parallel processing batch size
    "text_chunk_size": 400,  # Document content chunk size (tokens) 
    "text_chunk_overlap": 40,  # Overlap between chunks
    "force_rebuild": False,
    "use_parallel": True
}

vectordb = load_or_create_vectordb(dataset_name, **config)

Found existing vector database at vectordb\m-ric_huggingface_doc_400
Loading existing vector database...

C:\Users\Philippe\AppData\Local\Temp\ipykernel_21164\866353223.py:185: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-huggingface package and should be used instead. To use it run `pip install -U :class:`~langchain-huggingface` and import as `from :class:`~langchain_huggingface import HuggingFaceEmbeddings``.
  embedding_model = HuggingFaceEmbeddings(

Vector database loaded successfully!

In [9]:
# Example of using the vectordb for similarity search
query = "How to use transformers?"
results = vectordb.similarity_search(query, k=5)
for i, result in enumerate(results):
    print(f"Result {i+1}: {result.page_content}")

Result 1: . We can use this model as we would any other Transformers model, for instance by loading it in a pipeline. Try the push_to_hub API on your next training to easily share your model with the rest of the world!
Result 2: How do Transformers work?[[how-do-transformers-work]]

<CourseFloatingBanner
    chapter={1}
    classNames="absolute z-10 right-0 top-0"
/>

In this section, we will take a high-level look at the architecture of Transformer models.

## A bit of Transformer history[[a-bit-of-transformer-history]]

Here are some reference points in the (short) history of Transformer models:

<div class="flex justify-center">
<img class="block dark:hidden" src="https://huggingface.co/datasets/huggingface-course/documentation-images/resolve/main/en/chapter1/transformers_chrono.svg" alt="A brief chronology of Transformers models.">
<img class="hidden dark:block" src="https://huggingface.co/datasets/huggingface-course/documentation-images/resolve/main/en/chapter1/transformers_chrono-dark.svg" alt="A brief chronology of Transformers models.">
</div>

The [Transformer architecture](https://arxiv.org/abs/1706.03762) was introduced in June 2017. The focus of the original research was on translation tasks. This was followed by the introduction of several influential models, including:

- **June 2018**: [GPT](https://cdn.openai.com/research-covers/language-unsupervised/language_understanding_paper.pdf), the first pretrained Transformer model, used for fine-tuning on various NLP tasks and obtained state-of-the-art results
Result 3: Transformers, what can they do?[[transformers-what-can-they-do]]

<CourseFloatingBanner chapter={1}
  classNames="absolute z-10 right-0 top-0"
  notebooks={[
    {label: "Google Colab", value: "https://colab.research.google.com/github/huggingface/notebooks/blob/master/course/en/chapter1/section3.ipynb"},
    {label: "Aws Studio", value: "https://studiolab.sagemaker.aws/import/github/huggingface/notebooks/blob/master/course/en/chapter1/section3.ipynb"},
]} />

In this section, we will look at what Transformer models can do and use our first tool from the 🤗 Transformers library: the `pipeline()` function.

<Tip>
👀 See that <em>Open in Colab</em> button on the top right? Click on it to open a Google Colab notebook with all the code samples of this section. This button will be present in any section containing code examples.

If you want to run the examples locally, we recommend taking a look at the <a href="/course/chapter0">setup</a>.
</Tip>

## Transformers are everywhere![[transformers-are-everywhere]]

Transformer models are used to solve all kinds of NLP tasks, like the ones mentioned in the previous section. Here are some of the companies and organizations using Hugging Face and Transformer models, who also contribute back to the community by sharing their models:
Result 4: In the following, we try to give you a general recipe that we found most
useful when porting a model to 🤗 Transformers.

The following list is a summary of everything that has to be done to add
a model and can be used by you as a To-Do List:

1.  [ ] (Optional) Understood theoretical aspects

2.  [ ] Prepared transformers dev environment

3.  [ ] Set up debugging environment of the original repository

4.  [ ] Created script that successfully runs forward pass using
    original repository and checkpoint

5.  [ ] Successfully opened a PR and added the model skeleton to Transformers

6.  [ ] Successfully converted original checkpoint to Transformers
    checkpoint

7.  [ ] Successfully ran forward pass in Transformers that gives
    identical output to original checkpoint

8.  [ ] Finished model tests in Transformers

9.  [ ] Successfully added Tokenizer in Transformers

10. [ ] Run end-to-end integration tests

11. [ ] Finished docs

12. [ ] Uploaded model weights to the hub

13. [ ] Submitted the pull request for review

14. [ ] (Optional) Added a demo notebook

To begin with, we usually recommend to start by getting a good
theoretical understanding of `[camelcase name of model]`. However, if you prefer to
understand the theoretical aspects of the model *on-the-job*, then it is
totally fine to directly dive into the `[camelcase name of model]`'s code-base. This
option might suit you better, if your engineering skills are better than
your theoretical skill, if you have trouble understanding
`[camelcase name of model]`'s paper, or if you just enjoy programming much more than
reading scientific papers.

### 1. (Optional) Theoretical aspects of [camelcase name of model]
Result 5: 1. 필요한 대로 모델이나 예시를 커스터마이즈하세요:
    - 우리는 저자가 공개한 결과를 재현하기 위해 각 모델 구조의 예시를 제공합니다.
    - 모델 내부 구조는 가능한 일관적으로 공개되어 있습니다.
    - 빠른 실험을 위해 모델 파일은 라이브러리와 독립적으로 사용될 수 있습니다.

## 왜 transformers를 사용하지 말아야 할까요?

In [3]:
class RetrieverTool(Tool):
    name = "retriever"
    description = """
    Retrieves relevant documents from the knowledge base using semantic similarity search.
    Choose k based on query complexity:
    - k=5-7: For standard questions needing some context  
    - k=8-10: For complex topics requiring multiple perspectives
    - k=10-13: For comprehensive research or broad exploration
    """

    # inputs = {
    #     "query": {
    #         "type":
    #         "string",
    #         "description":
    #         "The search query. Use descriptive keywords and phrases rather than questions. Example: 'machine learning algorithms' instead of 'what are ML algorithms?'",
    #     },
    #     "k": {
    #         "type": "integer",
    #         "description":
    #         "Number of documents to retrieve (3-10). Choose based on query complexity: 3 for standard questions, 5-7 for complex topics, 8-10 for comprehensive research. Default: 3 if not specified.",
    #         "nullable": True
    #     }
    # }
    inputs = {
        "query": {
            "type":
            "string",
            "description":
            "The search query. Use descriptive keywords and phrases rather than questions. Example: 'machine learning algorithms' instead of 'what are ML algorithms?'",
        },
        "k": {
            "type": "integer",
            "description":
            "Number of documents to retrieve (7-20). Start with 7, increase if no relevant information is found. Default: 7 if not specified.",
            "nullable": True
        }
    }
    output_type = "string"

    def __init__(self,
                 vectordb: VectorStore,
                 k: int = 7,
                 score_threshold: Optional[float] = None,
                 max_content_length: int = 10000,
                 **kwargs):
        super().__init__(**kwargs)
        self.vectordb = vectordb
        self.k = k
        self.score_threshold = score_threshold
        self.max_content_length = max_content_length
        self.logger = logging.getLogger(self.__class__.__name__)

    def forward(self, query: str, k: Optional[int] = None) -> str:
        # Input validation
        if not query or not isinstance(query, str) or not query.strip():
            return "Error: Query must be a non-empty string"

        # Parameter validation
        retrieval_k = k if k is not None else self.k
        if retrieval_k is not None and (not isinstance(retrieval_k, int) or
                                        retrieval_k < 3 or retrieval_k > 20):
            retrieval_k = self.k

        query = query.strip()

        try:
            # Try to get documents with scores if available
            if hasattr(self.vectordb, 'similarity_search_with_score'
                       ) and self.score_threshold is not None:
                docs_with_scores = self.vectordb.similarity_search_with_score(
                    query, k=retrieval_k)
                # Filter by score threshold
                filtered_docs = [
                    doc for doc, score in docs_with_scores
                    if score >= self.score_threshold
                ]
                docs = filtered_docs[:retrieval_k] if filtered_docs else []

                if not docs and docs_with_scores:
                    # If no docs meet threshold, take the best one anyway
                    docs = [docs_with_scores[0][0]]

            else:
                docs = self.vectordb.similarity_search(query, k=retrieval_k)

        except Exception as e:
            self.logger.error(f"Error during similarity search: {str(e)}")
            return f"Error retrieving documents: {str(e)}"

        # Handle no results
        if not docs:
            return f"No relevant documents found for query: '{query}'"

        # Format results
        return self._format_results(query, docs)

    def _format_results(self, query: str, docs) -> str:
        """Format the retrieved documents into a readable string."""
        result_parts = [
            f"Search Query: {query}",
            f"Retrieved {len(docs)} relevant document(s):", ""
        ]

        for i, doc in enumerate(docs, 1):
            # Add document header
            result_parts.append(f"=== Document {i} ===")

            # Add metadata if available
            if hasattr(doc, 'metadata') and doc.metadata:
                metadata_info = []
                if 'source' in doc.metadata:
                    metadata_info.append(f"Source: {doc.metadata['source']}")
                if 'title' in doc.metadata:
                    metadata_info.append(f"Title: {doc.metadata['title']}")
                if 'page' in doc.metadata:
                    metadata_info.append(f"Page: {doc.metadata['page']}")

                if metadata_info:
                    result_parts.append(" | ".join(metadata_info))

            # Add content (with truncation if needed)
            content = doc.page_content
            if len(content) > self.max_content_length:
                content = content[:self.max_content_length].rsplit(
                    ' ', 1)[0] + "... [truncated]"

            result_parts.append(content)
            result_parts.append("")  # Empty line between documents

        return "\n".join(result_parts).strip()

    def get_retrieval_stats(self) -> dict:
        """Get basic stats about the vector store if available."""
        try:
            # This depends on the vector store implementation
            if hasattr(self.vectordb, '__len__'):
                return {"total_documents": len(self.vectordb)}
            return {"status": "Vector store connected"}
        except Exception:
            return {"status": "Unable to retrieve stats"}

In [6]:
# old retriever tool
from smolagents import Tool
from langchain_core.vectorstores import VectorStore


class RetrieverTool(Tool):
    name = "retriever"
    description = "Using semantic similarity, retrieves some documents from the knowledge base that have the closest embeddings to the input query."
    inputs = {
        "query": {
            "type":
            "string",
            "description":
            "The query to perform. This should be semantically close to your target documents. Use the affirmative form rather than a question.",
        }
    }
    output_type = "string"

    def __init__(self, vectordb: VectorStore, **kwargs):
        super().__init__(**kwargs)
        self.vectordb = vectordb

    def forward(self, query: str) -> str:
        assert isinstance(query, str), "Your search query must be a string"

        docs = self.vectordb.similarity_search(
            query,
            k=7,
        )

        return "\nRetrieved documents:\n" + "".join([
            f"===== Document {str(i)} =====\n" + doc.page_content
            for i, doc in enumerate(docs)
        ])

In [39]:
# answer LLM model initialization

load_dotenv()
# model_name = "gemini-2.5-flash-preview-05-20"
model_name = "gemini-2.0-flash"

answer_llm = OpenAIServerModel(
    # model_id="gemini-1.5-flash",
    model_id=model_name,
    api_base="https://generativelanguage.googleapis.com/v1beta/openai/",
    api_key=os.getenv("Gemini_API_KEY2"),
    temperature=0.2)

# models = Models(api_key=Blablador_API_KEY).get_model_ids()

# answer_llm = OpenAIServerModel(
#     model_id=models[4],
#     api_base="https://helmholtz-blablador.fz-juelich.de:8000/v1",
#     api_key=Blablador_API_KEY,
#     flatten_messages_as_text=True,
#     temperature=0.2)

retriever_tool = RetrieverTool(vectordb)
# retriever_tool = RetrieverTool(vectordb, score_threshold=0.7)

agent = CodeAgent(
    tools=[retriever_tool],
    model=answer_llm,
    planning_interval=2,
    max_steps=30,
    verbosity_level=LogLevel.ERROR,
)

In [ ]:
agent_output = agent.run("How can I push a model to the Hub?")

print("Final output:")
print(agent_output)

In [6]:
eval_dataset = datasets.load_dataset("m-ric/huggingface_doc_qa_eval",
                                     split="train")

In [ ]:
inspect = eval_dataset.select([4])

print(inspect[0]["context"])

!--Copyright 2022 The HuggingFace Team. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
the License. You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.

⚠️ Note that this file is in Markdown but contain specific syntax for our doc-builder (similar to MDX) that may not be
rendered properly in your Markdown viewer.

-->

# LongT5

## Overview

The LongT5 model was proposed in [LongT5: Efficient Text-To-Text Transformer for Long Sequences](https://arxiv.org/abs/2112.07916)
by Mandy Guo, Joshua Ainslie, David Uthus, Santiago Ontanon, Jianmo Ni, Yun-Hsuan Sung and Yinfei Yang. It's an
encoder-decoder transformer pre-trained in a text-to-text denoising generative setting. LongT5 model is an extension of
T5 model, and it enables using one of the two different efficient attention mechanisms - (1) Local attention, or (2)
Transient-Global attention.


The abstract from the paper is the following:

*Recent work has shown that either (1) increasing the input length or (2) increasing model size can improve the
performance of Transformer-based neural models. In this paper, we present a new model, called LongT5, with which we
explore the effects of scaling both the input length and model size at the same time. Specifically, we integrated
attention ideas from long-input transformers (ETC), and adopted pre-training strategies from summarization pre-training
(PEGASUS) into the scalable T5 architecture. The result is a new attention mechanism we call {\em Transient Global}
(TGlobal), which mimics ETC's local/global attention mechanism, but without requiring additional side-inputs. We are
able to achieve state-of-the-art results on several summarization tasks and outperform the original T5 models on
question answering tasks.*

This model was contributed by [stancld](https://huggingface.co/stancld).
The original code can be found [here](https://github.com/google-research/longt5).

## Usage tips

- [`LongT5ForConditionalGeneration`] is an extension of [`T5ForConditionalGeneration`] exchanging the traditional
encoder *self-attention* layer with efficient either *local* attention or *transient-global* (*tglobal*) attention.
- Unlike the T5 model, LongT5 does not use a task prefix. Furthermore, it uses a different pre-training objective
inspired by the pre-training of [`PegasusForConditionalGeneration`].
- LongT5 model is designed to work efficiently and very well on long-range *sequence-to-sequence* tasks where the
input sequence exceeds commonly used 512 tokens. It is capable of handling input sequences of a length up to 16,384 tokens.
- For *Local Attention*, the sparse sliding-window local attention operation allows a given token to attend only `r`
tokens to the left and right of it (with `r=127` by default). *Local Attention* does not introduce any new parameters
to the model. The complexity of the mechanism is linear in input sequence length `l`: `O(l*r)`.
- *Transient Global Attention* is an extension of the *Local Attention*. It, furthermore, allows each input token to
interact with all other tokens in the layer. This is achieved via splitting an input sequence into blocks of a fixed
length `k` (with a default `k=16`). Then, a global token for such a block is obtained via summing and normalizing the embeddings of every token
in the block. Thanks to this, the attention allows each token to attend to both nearby tokens like in Local attention, and
also every global token like in the case of standard global attention (*transient* represents the fact the global tokens
are constructed dynamically within each attention operation).  As a consequence, *TGlobal* attention introduces
a few new parameters -- global relative position biases and a layer normalization for global token's embedding.
The complexity of this mechanism is `O(l(r + l/k))`.
- An example showing how to evaluate a fine-tuned LongT5 model on the [pubmed dataset](https://huggingface.co/datasets/scientific_papers) is below.

```python
>>> import evaluate
>>> from datasets import load_dataset
>>> from transformers import AutoTokenizer, LongT5ForConditionalGeneration

>>> dataset = load_dataset("scientific_papers", "pubmed", split="validation")
>>> model = (
...     LongT5ForConditionalGeneration.from_pretrained("Stancld/longt5-tglobal-large-16384-pubmed-3k_steps")
...     .to("cuda")
...     .half()
... )
>>> tokenizer = AutoTokenizer.from_pretrained("Stancld/longt5-tglobal-large-16384-pubmed-3k_steps")


>>> def generate_answers(batch):
...     inputs_dict = tokenizer(
...         batch["article"], max_length=16384, padding="max_length", truncation=True, return_tensors="pt"
...     )
...     input_ids = inputs_dict.input_ids.to("cuda")
...     attention_mask = inputs_dict.attention_mask.to("cuda")
...     output_ids = model.generate(input_ids, attention_mask=attention_mask, max_length=512, num_beams=2)
...     batch["predicted_abstract"] = tokenizer.batch_decode(output_ids, skip_special_tokens=True)
...     return batch


>>> result = dataset.map(generate_answer, batched=True, batch_size=2)
>>> rouge = evaluate.load("rouge")
>>> rouge.compute(predictions=result["predicted_abstract"], references=result["abstract"])
```


## Resources

- [Translation task guide](../tasks/translation)
- [Summarization task guide](../tasks/summarization)

## LongT5Config

[[autodoc]] LongT5Config

<frameworkcontent>
<pt>

## LongT5Model

[[autodoc]] LongT5Model
    - forward

## LongT5ForConditionalGeneration

[[autodoc]] LongT5ForConditionalGeneration
    - forward

## LongT5EncoderModel

[[autodoc]] LongT5EncoderModel
    - forward

</pt>
<jax>

## FlaxLongT5Model

[[autodoc]] FlaxLongT5Model
    - __call__
    - encode
    - decode

## FlaxLongT5ForConditionalGeneration

[[autodoc]] FlaxLongT5ForConditionalGeneration
    - __call__
    - encode
    - decode

</jax>
</frameworkcontent>

In [13]:
retriever_tool = RetrieverTool(vectordb, max_content_length=float('inf'))
print(
    retriever_tool(
        "The LongT5 model was proposed in [LongT5: Efficient Text-To-Text Transformer for Long Sequences]",
        k=3))

Search Query: The LongT5 model was proposed in [LongT5: Efficient Text-To-Text Transformer for Long Sequences]
Retrieved 3 relevant document(s):

=== Document 1 ===
Source: transformers
!--Copyright 2022 The HuggingFace Team. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
the License. You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.

⚠️ Note that this file is in Markdown but contain specific syntax for our doc-builder (similar to MDX) that may not be
rendered properly in your Markdown viewer.

-->

# LongT5

## Overview

The LongT5 model was proposed in [LongT5: Efficient Text-To-Text Transformer for Long Sequences](https://arxiv.org/abs/2112.07916)
by Mandy Guo, Joshua Ainslie, David Uthus, Santiago Ontanon, Jianmo Ni, Yun-Hsuan Sung and Yinfei Yang. It's an
encoder-decoder transformer pre-trained in a text-to-text denoising generative setting. LongT5 model is an extension of
T5 model, and it enables using one of the two different efficient attention mechanisms - (1) Local attention, or (2)
Transient-Global attention.


The abstract from the paper is the following:

=== Document 2 ===
Source: transformers
## Overview

The Longformer model was presented in [Longformer: The Long-Document Transformer](https://arxiv.org/pdf/2004.05150.pdf) by Iz Beltagy, Matthew E. Peters, Arman Cohan.

The abstract from the paper is the following:

*Transformer-based models are unable to process long sequences due to their self-attention operation, which scales
quadratically with the sequence length. To address this limitation, we introduce the Longformer with an attention
mechanism that scales linearly with sequence length, making it easy to process documents of thousands of tokens or
longer. Longformer's attention mechanism is a drop-in replacement for the standard self-attention and combines a local
windowed attention with a task motivated global attention. Following prior work on long-sequence transformers, we
evaluate Longformer on character-level language modeling and achieve state-of-the-art results on text8 and enwik8. In
contrast to most prior work, we also pretrain Longformer and finetune it on a variety of downstream tasks. Our
pretrained Longformer consistently outperforms RoBERTa on long document tasks and sets new state-of-the-art results on
WikiHop and TriviaQA.*

This model was contributed by [beltagy](https://huggingface.co/beltagy). The Authors' code can be found [here](https://github.com/allenai/longformer).

## Usage tips

=== Document 3 ===
Source: blog
Recently, long sequence modeling has experienced a surge of interest as can be seen by the many submissions from this year alone - [Beltagy et al. (2020)](https://arxiv.org/abs/2004.05150), [Roy et al. (2020)](https://arxiv.org/abs/2003.05997), [Tay et al.](https://arxiv.org/abs/2002.11296), [Wang et al.](https://arxiv.org/abs/2006.04768) to name  a few.
The motivation behind long sequence modeling is that many tasks in NLP, *e.g.* summarization, question answering, require the model to process longer input sequences than models, such as BERT, are able to handle. In tasks that require the model to process a large input sequence, long sequence models do not have to cut the input sequence to avoid memory overflow and thus have been shown to outperform standard "BERT"-like models *cf.* [Beltagy et al. (2020)](https://arxiv.org/abs/2004.05150).

The Reformer pushes the limit of longe sequence modeling by its ability to process up to half a million tokens at once as shown in this [demo](https://github.com/patrickvonplaten/notebooks/blob/master/PyTorch_Reformer.ipynb). As a comparison, a conventional `bert-base-uncased` model limits the input length to only 512 tokens. In Reformer, each part of the standard transformer architecture is re-engineered to optimize for minimal memory requirement without a significant drop in performance.

In [ ]:
##### Using agentic RAG to answer questions

outputs_agentic_rag = []

inspect = eval_dataset.select([20])
# inspect = eval_dataset.select([42, 43, 47, 49])
# inspect = eval_dataset.select([20])

for example in tqdm(inspect):
    question = example["question"]

    #     enhanced_question = f"""Using the information contained in your knowledge base, which you can access with the 'retriever' tool,
    # give a comprehensive answer to the question below.
    # Respond only to the question asked, response should be concise and relevant to the question.
    # If you cannot find information, do not give up and try calling your retriever again with different arguments!
    # Make sure to have covered the question completely by calling the retriever tool several times with semantically different queries.
    # Your queries should not be questions but affirmative form sentences: e.g. rather than "How do I load a model from the Hub in bf16?", query should be "load a model from the Hub bf16 weights".

    # Question:
    # {question}"""
    # enhanced_question = f"""Use the 'retriever' tool to find information and answer this question: {question}

    # Instructions:
    # - Search the knowledge base using relevant keywords (avoid using "hugging face" in search terms)
    # - Start with k=7, then try k=12, k=15, or k=20 if no relevant information is found
    # - Keep increasing the number of documents until you find the answer
    # - Try different search terms if initial results don't answer the question
    # - Don't stop until you have enough information to answer the question

    # """

    # enhanced_question = f"""Use the 'retriever' tool to find information and answer this question: {question}

    # REQUIRED SEARCH PATTERN:
    # 1. Search with k=7 using your best keywords
    # 2. If no relevant info found, search same keywords with k=10
    # 3. If still no relevant info, search same keywords with k=13
    # 4. If still no relevant info, try different keywords and repeat steps 1-3

    # SEARCH RULES:
    # - Use specific technical keywords
    # - Do NOT use "Hugging Face" in query
    # - Focus on the core concept/function/method being asked about
    # - Try different keyword combinations if first set doesn't work
    # - Don't stop until you find relevant information or exhaust keyword options

    # Start searching now with k=7.
    # """

    enhanced_question = f"""Use the 'retriever' tool to find information and answer this question: {question}

    SEARCH STRATEGY:
    1. Start with k=7 using your best keywords from the question
    2. If information is incomplete or irrelevant, retry with k=10 (same keywords)
    3. If the same documents are retrieved and information is still insufficient, try different keywords:
    - Use synonym words from the question to find different documents
    - Reduce keywords to search for broader documents
    - Use related concepts from previously retrieved documents
    4. Repeat steps 1-3 with new keyword combinations until you find the answer

    SEARCH RULES:
    - Do NOT include "Hugging Face" in queries (all questions relate to Hugging Face ecosystem)
    - The answer exists in the database - keep searching with different approaches
    - Try both specific and broad keyword strategies

    RESPONSE RULES:
    - Answer strictly based on retrieved documents, not prior knowledge
    - If answer is found: provide clear, direct response with relevant details
    - If answer not found: summarize the most relevant information retrieved

    Begin your search systematically.
    """

    answer = agent.run(enhanced_question)
    print("=======================================================")
    print(f"Question: {question}")
    print(f"Answer: {answer}")
    print(f'True answer: {example["answer"]}')

    results_agentic = {
        "question": question,
        "true_answer": example["answer"],
        "source_doc": example["source_doc"],
        "generated_answer": answer,
    }
    outputs_agentic_rag.append(results_agentic)
    # time.sleep(5)

In [121]:
with open("checkpoints/rag_checkpoint.json", 'r') as f:
    loaded_json = json.load(f)

# Convert back to a dictionary of DataFrames
# loaded_results = {}
# for system_type, records in loaded_json.items():
#     loaded_results[system_type] = pd.DataFrame.from_records(records)

In [42]:
## Set a checkpoint for query limitations (limited API) to use agentic RAG to answer questions


def run_agentic_rag_with_checkpointing(
        eval_dataset,
        agent,
        checkpoint_file="checkpoints/rag_checkpoint.json"):
    """
    Run agentic RAG with checkpointing to allow resuming from interruptions.
    
    Args:
        eval_dataset: Dataset containing questions and answers
        agent: The agent to run queries with
        checkpoint_file: File to store checkpointing information
    
    Returns:
        List of results from agentic RAG
    """
    outputs_agentic_rag = []
    start_idx = 0

    # Load checkpoint if exists
    if os.path.exists(checkpoint_file):
        try:
            with open(checkpoint_file, 'r') as f:
                checkpoint_data = json.load(f)
                outputs_agentic_rag = checkpoint_data.get('results', [])
                start_idx = checkpoint_data.get('next_idx', 0)
                print(
                    f"Resuming from checkpoint at index {start_idx} with {len(outputs_agentic_rag)} results already processed"
                )
        except Exception as e:
            print(f"Error loading checkpoint: {e}")
            print("Starting from beginning")

    # Create progress bar starting from checkpoint
    total_examples = len(eval_dataset)
    pbar = tqdm(total=total_examples, initial=start_idx)

    try:
        for idx in range(start_idx, total_examples):
            example = eval_dataset[idx]
            question = example["question"]

            enhanced_question = f"""Use the 'retriever' tool to find information and answer this question: {question}

            SEARCH STRATEGY:
            1. Start with k=7 using your best keywords from the question
            2. If information is incomplete or irrelevant, retry with k=10 (same keywords)
            3. If the same documents are retrieved and information is still insufficient, try different keywords:
            - Use synonym words from the question to find different documents
            - Reduce keywords to search for broader documents
            - Use related concepts from previously retrieved documents
            4. Repeat steps 1-3 with new keyword combinations until you find the answer

            SEARCH RULES:
            - Do NOT include "Hugging Face" in queries (all questions relate to Hugging Face ecosystem)
            - The answer exists in the database - keep searching with different approaches
            - Try both specific and broad keyword strategies

            RESPONSE RULES:
            - Answer strictly based on retrieved documents, not prior knowledge
            - If answer is found: provide clear, direct response with relevant details
            - If answer not found: summarize the most relevant information retrieved

            Begin your search systematically.
            """

            try:
                answer = agent.run(enhanced_question)

                print(
                    "=======================================================")
                print(f"Question: {question}")
                print(f"Answer: {answer}")
                print(f'True answer: {example["answer"]}')

                results_agentic = {
                    "question": question,
                    "true_answer": example["answer"],
                    "source_doc": example["source_doc"],
                    "generated_answer": answer,
                }

                outputs_agentic_rag.append(results_agentic)

                # Update checkpoint after each successful query
                save_checkpoint(checkpoint_file, outputs_agentic_rag, idx + 1)

                pbar.update(1)
                time.sleep(10)  # Rate limiting

            except Exception as e:
                print(f"Error processing example {idx}: {e}")
                # Save checkpoint before exiting
                save_checkpoint(checkpoint_file, outputs_agentic_rag, idx)
                print(f"Checkpoint saved. Resume from index {idx}")
                raise

    except KeyboardInterrupt:
        print("\nProcess interrupted by user")
        # Save checkpoint before exiting
        save_checkpoint(checkpoint_file, outputs_agentic_rag, idx)
        print(f"Checkpoint saved. Resume from index {idx}")

    finally:
        pbar.close()

    return outputs_agentic_rag


def save_checkpoint(checkpoint_file, results, next_idx):
    """Save checkpoint data to file"""
    checkpoint_data = {
        "results": results,
        "next_idx": next_idx,
        "timestamp": time.time()
    }

    # Use a temporary file to avoid corruption if interrupted during writing
    temp_file = f"{checkpoint_file}.temp"
    with open(temp_file, 'w') as f:
        json.dump(checkpoint_data, f)

    # Safely replace the old checkpoint file
    if os.path.exists(checkpoint_file):
        os.replace(temp_file, checkpoint_file)
    else:
        os.rename(temp_file, checkpoint_file)


outputs_agentic_rag = run_agentic_rag_with_checkpointing(eval_dataset, agent)

Resuming from checkpoint at index 60 with 60 results already processed

 94%|█████████▍| 61/65 [00:04<00:18,  4.62s/it]

=======================================================
Question: What is the maximum size of a model checkpoint before it is automatically sharded in Transformers version 4.18.0?

Answer: In Transformers version 4.18.0, model checkpoints that exceed 10GB are automatically sharded.
True answer: 10GB

 95%|█████████▌| 62/65 [00:30<00:51, 17.03s/it]

=======================================================
Question: What is the purpose of Weights and Biases (W&B) for data scientists and machine learning scientists?

Answer: Weights and Biases (W&B) allows data scientists and machine learning scientists to track their machine learning experiments at every stage, from training to production. It provides a customizable and searchable dashboard where any metric can be aggregated over samples.
True answer: To track their machine learning experiments at every stage, from training to production.

 97%|█████████▋| 63/65 [00:45<00:32, 16.17s/it]

=======================================================
Question: What is the name of the open-source library created by Hugging Face to simplify Transformer acceleration?

Answer: Optimum
True answer: Optimum

 98%|█████████▊| 64/65 [01:01<00:16, 16.10s/it]

=======================================================
Question: What parameter is used to ensure that elements in a row have the same height in Gradio?

Answer: The `equal_height` parameter should be passed to the `.style()` method of `gr.Row()` to ensure that elements in a row have the same height in Gradio.
True answer: equal_height

100%|██████████| 65/65 [01:16<00:00, 15.72s/it]

=======================================================
Question: What is the command to install the latest version of Optimum with OpenVINO support?

Answer: pip install --upgrade-strategy eager optimum[openvino,nncf]
True answer: pip install --upgrade-strategy eager optimum["openvino"]

100%|██████████| 65/65 [01:26<00:00, 17.30s/it]

In [43]:
##### using only RAG to answer questions

answer_llm = OpenAIServerModel(
    model_id=model_name,
    api_base="https://generativelanguage.googleapis.com/v1beta/openai/",
    api_key=os.getenv("Gemini_API_KEY2"),
    # flatten_messages_as_text=True,
    temperature=0.2)

# answer_llm = OpenAIServerModel(
#     model_id=models[4],
#     api_base="https://helmholtz-blablador.fz-juelich.de:8000/v1",
#     api_key=Blablador_API_KEY,
#     # flatten_messages_as_text=True,
#     temperature=0.2)

# inspect = eval_dataset.select(list(range(20)))

outputs_standard_rag = []

for example in tqdm(eval_dataset):
    question = example["question"]
    context = retriever_tool(question, k=7)

    prompt = f"""Given the question and supporting documents below, give a comprehensive answer to the question.
Respond only to the question asked, response should be concise and relevant to the question.
If the question is ambiguous or cannot be answered definitively, state so clearly.

Question:
{question}

{context}
"""
    messages = [{"role": "user", "content": prompt}]
    answer = answer_llm.generate(messages).content

    print("=======================================================")
    print(f"Question: {question}")
    # print(f"Context: {context}")
    print(f"Answer: {answer}")
    print(f'True answer: {example["answer"]}')

    results_agentic = {
        "question": question,
        "true_answer": example["answer"],
        "source_doc": example["source_doc"],
        "generated_answer": answer,
    }
    outputs_standard_rag.append(results_agentic)
    time.sleep(5)

  0%|          | 0/65 [00:00<?, ?it/s]

=======================================================
Question: What architecture is the `tokenizers-linux-x64-musl` binary designed for?

Answer: The `tokenizers-linux-x64-musl` binary is designed for the **x86_64-unknown-linux-musl** architecture.

True answer: x86_64-unknown-linux-musl

  2%|▏         | 1/65 [00:05<06:07,  5.74s/it]

=======================================================
Question: What is the purpose of the BLIP-Diffusion model?

Answer: BLIP-Diffusion enables zero-shot subject-driven generation and control-guided zero-shot generation.

True answer: The BLIP-Diffusion model is designed for controllable text-to-image generation and editing.

  3%|▎         | 2/65 [00:11<05:52,  5.60s/it]

=======================================================
Question: How can a user claim authorship of a paper on the Hugging Face Hub?

Answer: A user can claim authorship of a paper on the Hugging Face Hub by:

1.  **Automatic Matching:** The Hub attempts to automatically match papers to users based on their email.
2.  **Manual Claim:** If the paper is not automatically linked, the user can click their name on the paper's page and select "claim authorship." This redirects to paper settings where the request can be confirmed. The admin team will then validate the request.

True answer: By clicking their name on the corresponding Paper page and clicking "claim authorship", then confirming the request in paper settings for admin team validation.

  5%|▍         | 3/65 [00:17<05:54,  5.72s/it]

=======================================================
Question: What is the purpose of the /healthcheck endpoint in the Datasets server API?

Answer: The `/healthcheck` endpoint in the Datasets server API is used to ensure that the application is running.

True answer: Ensure the app is running

  6%|▌         | 4/65 [00:22<05:43,  5.63s/it]

=======================================================
Question: What is the default context window size for Local Attention in the LongT5 model?

Answer: The default context window size for Local Attention in the LongT5 model is `r=127` tokens to the left and right, meaning a total window size of 255.

True answer: 127 tokens

  8%|▊         | 5/65 [00:28<05:40,  5.68s/it]

=======================================================
Question: What method is used to load a checkpoint for a task using `AutoPipeline`?

Answer: The `from_pretrained()` method is used to load a checkpoint for a task using `AutoPipeline`.

True answer: from_pretrained()

  9%|▉         | 6/65 [00:33<05:32,  5.64s/it]

=======================================================
Question: What is the purpose of Diffusers library?

Answer: The Diffusers library is designed for using and training state-of-the-art pretrained diffusion models for generating images, audio, and 3D structures of molecules. It provides diffusion pipelines for inference, interchangeable noise schedulers, and pretrained models as building blocks.

True answer: To serve as a modular toolbox for both inference and training of state-of-the-art pretrained diffusion models across multiple modalities.

 11%|█         | 7/65 [00:39<05:27,  5.65s/it]

=======================================================
Question: What method does the EulerAncestralDiscreteScheduler use for sampling?

Answer: The EulerAncestralDiscreteScheduler uses ancestral sampling with Euler method steps.

True answer: Ancestral sampling with Euler method steps.

 12%|█▏        | 8/65 [00:45<05:19,  5.61s/it]

=======================================================
Question: What is the name of the large multimodal model that can solve image-text tasks and is based on Flamingo?

Answer: IDEFICS is a large multimodal model that can solve image-text tasks and is based on Flamingo.

True answer: IDEFICS

 14%|█▍        | 9/65 [00:50<05:13,  5.60s/it]

=======================================================
Question: What is the purpose of the `gradio.Blocks` API?

Answer: The `gradio.Blocks` API is a low-level API that provides full control over the data flows and layout of a Gradio application. It allows for building complex, multi-step applications with flexible layouts, data flows, and the ability to update component properties based on user input. It offers more customization compared to the `gradio.Interface` API.

True answer: The `gradio.Blocks` API allows you to have full control over the data flows and layout of your application, enabling the building of complex, multi-step applications.

 15%|█▌        | 10/65 [00:56<05:13,  5.70s/it]

=======================================================
Question: What is the purpose of the two-stage model proposed in the paper "Hierarchical Text-Conditional Image Generation with CLIP Latents"?

Answer: The two-stage model proposed in the paper "Hierarchical Text-Conditional Image Generation with CLIP Latents" uses a Prior Transformer to predict CLIP image embeddings from CLIP text embeddings through a denoising diffusion process.

True answer: The purpose of the two-stage model is to generate a CLIP image embedding given a text caption and then generate an image conditioned on the image embedding.

 17%|█▋        | 11/65 [01:02<05:06,  5.67s/it]

=======================================================
Question: What command is used to install the requirements for a research project using 🤗 Transformers?

Answer: To install the requirements for a research project using 🤗 Transformers, the command is:

```bash
pip install -r requirements.txt
```

True answer: pip install -r requirements.txt

 18%|█▊        | 12/65 [01:07<05:00,  5.67s/it]

=======================================================
Question: What task does the `roberta-large-mnli` checkpoint perform?

Answer: The `roberta-large-mnli` checkpoint performs text classification, specifically natural language inference, classifying if two sentences are logically linked across three labels: contradiction, neutral, and entailment.

True answer: Text classification

 20%|██        | 13/65 [01:13<04:53,  5.65s/it]

=======================================================
Question: What service is replacing the Paid tier of the Inference API at Hugging Face?

Answer: The Paid tier of the Inference API service at Hugging Face is being replaced by Inference Endpoints.

True answer: Inference Endpoints

 22%|██▏       | 14/65 [01:19<04:45,  5.60s/it]

=======================================================
Question: What architectural feature does SqueezeBERT use instead of fully-connected layers for the Q, K, V, and FFN layers?

Answer: SqueezeBERT uses grouped convolutions instead of fully-connected layers for the Q, K, V, and FFN layers.

True answer: Grouped convolutions

 23%|██▎       | 15/65 [01:24<04:40,  5.61s/it]

=======================================================
Question: What type of license is the HuggingFace Team's software distributed under?

Answer: The HuggingFace Team's software is distributed under the Apache License, Version 2.0.

True answer: Apache License, Version 2.0

 25%|██▍       | 16/65 [01:30<04:33,  5.57s/it]

=======================================================
Question: What are the two parameter-reduction techniques proposed in the ALBERT model to lower memory consumption and increase training speed?

Answer: The two parameter-reduction techniques proposed in the ALBERT model are:

1.  Splitting the embedding matrix into two smaller matrices.
2.  Using repeating layers split among groups.

True answer: Splitting the embedding matrix into two smaller matrices and using repeating layers split among groups.

 26%|██▌       | 17/65 [01:35<04:26,  5.55s/it]

=======================================================
Question: What are the three main steps for fine-tuning a model with the 🤗 Datasets library?

Answer: According to Document 1, the three main steps for fine-tuning a model with the 🤗 Datasets library are:

1.  Load a dataset from the Hugging Face Hub.
2.  Preprocess the data with `Dataset.map()`.
3.  Load and compute metrics.

True answer: 1. Load a dataset from the Hugging Face Hub. 2. Preprocess the data with `Dataset.map()`. 3. Load and compute metrics.

 28%|██▊       | 18/65 [01:41<04:24,  5.63s/it]

=======================================================
Question: What is the maximum improvement in throughput achieved by Hugging Face Infinity compared to vanilla transformers?

Answer: Hugging Face Infinity can deliver up to 800% higher throughput compared to vanilla transformers.

True answer: +800%

 29%|██▉       | 19/65 [01:46<04:17,  5.59s/it]

=======================================================
Question: What is the command to upload a spaCy pipeline to the Hugging Face Hub?

Answer: The command to upload a spaCy pipeline to the Hugging Face Hub is:

```bash
python -m spacy huggingface-hub push [whl_path] [--org] [--msg] [--local-repo] [--verbose]
```

where `[whl_path]` is the path to the packaged pipeline.

True answer: python -m spacy huggingface-hub push en_ner_fashion-0.0.0-py3-none-any.whl

 31%|███       | 20/65 [01:52<04:12,  5.61s/it]

=======================================================
Question: What is the time and memory complexity of the Nyströmformer's approximation of self-attention?

Answer: The Nyströmformer approximates standard self-attention with a time and memory complexity of O(n), where n is the length of the input sequence.

True answer: O(n)

 32%|███▏      | 21/65 [01:58<04:05,  5.59s/it]

=======================================================
Question: What is the goal of the Named Entity Recognition task in token classification?

Answer: The goal of Named Entity Recognition (NER) in token classification is to identify and classify named entities (like persons, locations, or organizations) within a text by assigning a label to each token.

True answer: The goal of the Named Entity Recognition task is to find the entities in a piece of text, such as person, location, or organization.

 34%|███▍      | 22/65 [02:03<04:01,  5.62s/it]

=======================================================
Question: What is the resolution of images used by the CLIPSeg model?

Answer: The CLIPSeg model uses images of 352 x 352 pixels.

True answer: 352 x 352 pixels

 35%|███▌      | 23/65 [02:09<03:55,  5.61s/it]

=======================================================
Question: What can you use Gradio for?

Answer: Gradio can be used to:

*   Quickly create customizable web apps for machine learning models and data processing pipelines.
*   Deploy apps on Hugging Face Spaces or your own web server.
*   Customize the appearance and behavior of web components.
*   Connect to your data and display it.
*   Set up your own server to serve Gradio share links.
*   Add arbitrary JS to your apps and arbitrary modifications to the `<head>` of your app.
True answer: Create a demo for your machine learning model, share your machine learning model with others, and debug your model.

 37%|███▋      | 24/65 [02:15<03:55,  5.74s/it]

=======================================================
Question: What TensorFlow API function is used to load a saved tensor file?

Answer: Based on the provided documents, the TensorFlow API functions used to load a saved tensor file using the `safetensors` library are:

*   `safetensors.tensorflow.load_file`
*   `safetensors.tensorflow.load`

True answer: safetensors.tensorflow.load_file

 38%|███▊      | 25/65 [02:21<03:48,  5.71s/it]

=======================================================
Question: Where can you access the logs of your Endpoints in Hugging Face Endpoints?

Answer: You can access the logs of your Endpoints in Hugging Face Endpoints through the UI in the “Logs” tab of your Endpoint. You will have access to the build logs of your Image artifacts as well as access to the Container Logs during inference. The Container Logs are only available when your Endpoint is in the “Running” state. If your Endpoint creation is in the “Failed” state, you can check the Build Logs to see what the reason was.

True answer: In the "Logs" tab of your Endpoint through the UI.

 40%|████      | 26/65 [02:27<03:47,  5.83s/it]

=======================================================
Question: What is the latest task added to Hugging Face AutoTrain for Computer Vision?

Answer: Based on the provided documents, the latest task added to Hugging Face AutoTrain for Computer Vision is **Image Classification** (Document 1).

True answer: Image Classification

 42%|████▏     | 27/65 [02:32<03:39,  5.77s/it]

=======================================================
Question: What is the default repository type created by the `create_repo` function on Hugging Face Hub?

Answer: By default, the `create_repo` function creates a model repository.

True answer: model

 43%|████▎     | 28/65 [02:38<03:29,  5.66s/it]

=======================================================
Question: How many splits does the "duorc" dataset have?

Answer: The "duorc" dataset has three splits: train, validation, and test. (Document 2 and 4)
True answer: Six

 45%|████▍     | 29/65 [02:44<03:26,  5.75s/it]

=======================================================
Question: What is the purpose of Fully Sharded Data Parallel (FSDP) in distributed training?

Answer: The purpose of Fully Sharded Data Parallel (FSDP) in distributed training is to shard the model parameters, gradients, and optimizer states across multiple GPUs (or workers) to improve memory efficiency and enable the training of larger models, even up to 1T parameters, on fewer GPUs. It can also offload sharded model parameters to the CPU.

True answer: FSDP is developed for distributed training of large pretrained models up to 1T parameters by sharding the model parameters, gradients, and optimizer states across data parallel processes.

 46%|████▌     | 30/65 [02:50<03:23,  5.80s/it]

=======================================================
Question: What file format is used to save and store PyTorch model weights more securely than `.bin` files?

Answer: The `.safetensors` file format is used to save and store PyTorch model weights more securely than `.bin` files.

True answer: `.safetensors`

 48%|████▊     | 31/65 [02:55<03:15,  5.75s/it]

=======================================================
Question: What type of security certification does Hugging Face have?

Answer: Hugging Face is SOC2 Type 2 certified.

True answer: SOC2 Type 2 certified

 49%|████▉     | 32/65 [03:01<03:07,  5.69s/it]

=======================================================
Question: What do RAG models combine to generate outputs?

Answer: RAG models combine retrieved documents and a seq2seq model to generate outputs. The retriever and seq2seq modules are initialized from pretrained models and fine-tuned jointly.

True answer: Pretrained dense retrieval (DPR) and sequence-to-sequence models.

 51%|█████     | 33/65 [03:06<03:02,  5.69s/it]

=======================================================
Question: What library does MarkupLMFeatureExtractor use to extract data from HTML and XML files?

Answer: MarkupLMFeatureExtractor uses Beautiful Soup, a Python library, to extract data from HTML and XML files.

True answer: Beautiful Soup

 52%|█████▏    | 34/65 [03:12<02:55,  5.65s/it]

=======================================================
Question: What is the file size limit for syncing to HF Spaces without using Git-LFS?

Answer: The file size limit for syncing to HF Spaces without using Git-LFS is 10MB.

True answer: 10MB

 54%|█████▍    | 35/65 [03:18<02:48,  5.63s/it]

=======================================================
Question: What is the title of the paper introducing the ByT5 model?

Answer: The title of the paper introducing the ByT5 model is "ByT5: Towards a token-free future with pre-trained byte-to-byte models".

True answer: ByT5: Towards a token-free future with pre-trained byte-to-byte models

 55%|█████▌    | 36/65 [03:23<02:42,  5.60s/it]

=======================================================
Question: What is the dimension of the feature vector for the base BERT model?

Answer: The dimension of the feature vector for the base BERT model is 768.

True answer: 768

 57%|█████▋    | 37/65 [03:29<02:35,  5.54s/it]

=======================================================
Question: What special identifier does the WordPiece Model use for continuing subwords?

Answer: The WordPiece Model uses `##` as a special identifier for continuing subwords.

True answer: ##

 58%|█████▊    | 38/65 [03:34<02:30,  5.58s/it]

=======================================================
Question: What is the purpose of the 🧨 Diffusers tutorials?

Answer: The 🧨 Diffusers examples/tutorials demonstrate how to effectively use the `diffusers` library for various use cases involving training or fine-tuning. They aspire to be self-contained, easy-to-tweak, beginner-friendly, and for one-purpose-only. Pipelines are also designed to be easy to use and should loosely be seen as examples of how to use models and schedulers for inference.

True answer: To provide a gentle introduction to diffusion models and help understand the library fundamentals.

 60%|██████    | 39/65 [03:40<02:28,  5.70s/it]

=======================================================
Question: What is the default setting for the `allow_flagging` parameter in Gradio's `Interface`?

Answer: The default setting for the `allow_flagging` parameter in Gradio's `Interface` is `"manual"`.

True answer: "manual"

 62%|██████▏   | 40/65 [03:46<02:21,  5.67s/it]

=======================================================
Question: Where can the full code for the Stable Diffusion demo be found?

Answer: The full code for the Stable Diffusion demo can be found at: https://hf.co/spaces/stabilityai/stable-diffusion/tree/main

True answer: https://hf.co/spaces/stabilityai/stable-diffusion/tree/main

 63%|██████▎   | 41/65 [03:51<02:15,  5.65s/it]

=======================================================
Question: What transformation does the FNet model use to replace the self-attention layer in a BERT model?

Answer: The FNet model replaces the self-attention layer in a BERT model with a Fourier Transform, returning only the real parts of the transform.

True answer: Fourier transform

 65%|██████▍   | 42/65 [03:57<02:09,  5.63s/it]

=======================================================
Question: What type of test should typically accompany a bug fix in Gradio's testing strategy?

Answer: Every bug fix in Gradio should typically be accompanied by a test that failed before the fix and passes afterward. This test should typically be a dynamic code test, but it could also be a linting rule or new type if appropriate.

True answer: Dynamic code test

 66%|██████▌   | 43/65 [04:03<02:04,  5.66s/it]

=======================================================
Question: How can you force mixed precision training when initializing the Accelerator in 🤗 Accelerate?

Answer: You can force mixed precision training when initializing the `Accelerator` in 🤗 Accelerate by passing `fp16=True` or `bf16=True` to the `Accelerator` constructor. Alternatively, you can use the `accelerate launch` command with the `--mixed_precision` argument, setting it to "fp16" or "bf16". You can also configure mixed precision training using the `accelerate config` command, which creates a `config_file.yaml` file.

True answer: By passing `fp16=True` to the Accelerator init.

 68%|██████▊   | 44/65 [04:09<02:01,  5.78s/it]

=======================================================
Question: What is the purpose of tokenizers in the NLP pipeline?

Answer: The purpose of tokenizers in the NLP pipeline is to translate text into numerical data that can be processed by machine learning models.

True answer: To translate text into data that can be processed by the model.

 69%|██████▉   | 45/65 [04:14<01:55,  5.77s/it]

=======================================================
Question: What is the purpose of the Safety Checker in the Diffusers library?

Answer: The purpose of the Safety Checker in the Diffusers library is to screen generated outputs against known hardcoded NSFW (Not Safe For Work) content, mitigating the risk of generating harmful content.

True answer: The Safety Checker checks and compares the class probability of a set of hard-coded harmful concepts in the embedding space against an image after it has been generated to mitigate the risk of generating harmful content.

 71%|███████   | 46/65 [04:20<01:49,  5.74s/it]

=======================================================
Question: What Python class allows you to retrieve Discussions and Pull Requests from a given repository on the Hugging Face Hub?

Answer: The `HfApi` class, specifically using the `HfApi.get_repo_discussions` method, allows you to retrieve Discussions and Pull Requests from a given repository on the Hugging Face Hub.

True answer: HfApi

 72%|███████▏  | 47/65 [04:26<01:42,  5.72s/it]

=======================================================
Question: What is the name of the new library introduced by Hugging Face for hosting scikit-learn models?

Answer: Based on the provided documents, the question cannot be definitively answered. While the documents discuss the Hugging Face Hub and its support for various libraries and model hosting, none of them explicitly mention a new library specifically introduced by Hugging Face for hosting scikit-learn models.

True answer: Skops

 74%|███████▍  | 48/65 [04:32<01:37,  5.76s/it]

=======================================================
Question: What is the purpose of Textual Inversion?

Answer: The purpose of Textual Inversion is to personalize text-to-image models by learning new text embeddings from a few example images. This allows the model to learn new concepts and generate images that match the provided examples.

True answer: Textual Inversion is a training method for personalizing models by learning new text embeddings from a few example images.

 75%|███████▌  | 49/65 [04:37<01:31,  5.73s/it]

=======================================================
Question: What is the recommended multiple of batch size for fp16 data type on an A100 GPU?

Answer: While the documents mention using fp16 on A100 GPUs and discuss batch sizes, none of them provide a specific, universally "recommended" multiple for the batch size when using fp16 on an A100 GPU. Document 5 shows A100 throughput for batch sizes of 32 and 64. Document 1 suggests increasing the batch size as much as possible to maximize GPU efficiency.

True answer: 64

 77%|███████▋  | 50/65 [04:43<01:27,  5.80s/it]

=======================================================
Question: How do you run a Gradio Blocks app in reload mode using a Python IDE?

Answer: To run a Gradio Blocks app in reload mode using a Python IDE, use the command `gradio <your_file_name>.py` in the terminal.  For example, if your file is named `run.py`, you would type `gradio run.py`. If your Gradio app is named something other than `demo`, you need to specify the name of the app as the second parameter: `gradio run.py <your_app_name>`.

True answer: Run `gradio run.py` in the terminal.

 78%|███████▊  | 51/65 [04:49<01:21,  5.85s/it]

=======================================================
Question: How can you install the Hugging Face Unity API in your Unity project?

Answer: To install the Hugging Face Unity API in your Unity project:

1.  Open your Unity project.
2.  Go to `Window` -> `Package Manager`.
3.  Click `+` and select `Add Package from git URL`.
4.  Enter `https://github.com/huggingface/unity-api.git`.
5.  Once installed, the Unity API wizard should pop up. If not, go to `Window` -> `Hugging Face API Wizard`.

True answer: To install the Hugging Face Unity API in your Unity project, go to `Window` -> `Package Manager`, click `+` and select `Add Package from git URL`, then enter `https://github.com/huggingface/unity-api.git`.

 80%|████████  | 52/65 [04:55<01:16,  5.87s/it]

=======================================================
Question: What is the pretraining objective of the Wav2Vec2 context network?

Answer: The pretraining objective of Wav2Vec2 is a contrastive loss objective. (Document 4)

True answer: The pretraining objective of the Wav2Vec2 context network is a contrastive task where the model has to predict the true quantized speech representation of the masked prediction from a set of false ones.

 82%|████████▏ | 53/65 [05:01<01:09,  5.75s/it]

=======================================================
Question: What is the default checkpoint used by the sentiment analysis pipeline in the Transformers library?

Answer: The default checkpoint used by the sentiment analysis pipeline in the Transformers library is `distilbert-base-uncased-finetuned-sst2-english`.

True answer: distilbert base uncased finetuned sst2 english

 83%|████████▎ | 54/65 [05:06<01:02,  5.68s/it]

=======================================================
Question: What is the purpose of the notebook "How to use DeepSpeed to train models with billions of parameters on Habana Gaudi"?

Answer: The notebook "How to use DeepSpeed to train models with billions of parameters on Habana Gaudi" demonstrates how to use DeepSpeed to pre-train or fine-tune a large language model (specifically, the 1.6B-parameter GPT2-XL) for causal language modeling on Habana Gaudi hardware.

True answer: To show how to use DeepSpeed to pre-train/fine-tune the 1.6B-parameter GPT2-XL for causal language modeling on Habana Gaudi.

 85%|████████▍ | 55/65 [05:12<00:57,  5.78s/it]

=======================================================
Question: What command line module does PyTorch provide to run a script on multiple GPUs?

Answer: PyTorch provides the `torchrun` command line module to run a script on multiple GPUs.

True answer: torchrun

 86%|████████▌ | 56/65 [05:18<00:51,  5.73s/it]

=======================================================
Question: What is the most popular vision transformer model on the Hugging Face Model Hub for image classification?

Answer: According to Document 3, at the time of writing, the most popular vision transformer model on the Hugging Face Model Hub for image classification was `google/vit-base-patch16-224`.

True answer: google/vit-base-patch16-224

 88%|████████▊ | 57/65 [05:24<00:46,  5.85s/it]

=======================================================
Question: What is the command to upload an ESPnet model to a Hugging Face repository?

Answer: Based on the provided documents, the command to upload an ESPnet model to a Hugging Face repository is:

```bash
./run.sh --stage 15 --skip_upload_hf false --hf_repo username/model_repo
```

Where `username/model_repo` should be replaced with your Hugging Face username and the desired repository name.

True answer: ./run.sh --stage 15 --skip_upload_hf false --hf_repo username/model_repo

 89%|████████▉ | 58/65 [05:30<00:40,  5.84s/it]

=======================================================
Question: What file should be added to a model repository to install custom Python dependencies for Inference Endpoints?

Answer: To install custom Python dependencies for Inference Endpoints, add a `requirements.txt` file to your model repository on the Hugging Face Hub.

True answer: requirements.txt

 91%|█████████ | 59/65 [05:36<00:34,  5.81s/it]

=======================================================
Question: How many images are needed to teach new concepts to Stable Diffusion using Textual Inversion?

Answer: To teach new concepts to Stable Diffusion using Textual Inversion, you generally need just 3-5 example images.

True answer: 3-5 images

 92%|█████████▏| 60/65 [05:41<00:29,  5.84s/it]

=======================================================
Question: What is the maximum size of a model checkpoint before it is automatically sharded in Transformers version 4.18.0?

Answer: In Transformers version 4.18.0, model checkpoints exceeding 10GB are automatically sharded into smaller pieces.

True answer: 10GB

 94%|█████████▍| 61/65 [05:47<00:22,  5.74s/it]

=======================================================
Question: What is the purpose of Weights and Biases (W&B) for data scientists and machine learning scientists?

Answer: Weights & Biases (W&B) allows data scientists and machine learning scientists to track their machine learning experiments at every stage, from training to production. It helps aggregate metrics over samples and display them in customizable and searchable dashboards. (Document 1)

True answer: To track their machine learning experiments at every stage, from training to production.

 95%|█████████▌| 62/65 [05:53<00:17,  5.78s/it]

=======================================================
Question: What is the name of the open-source library created by Hugging Face to simplify Transformer acceleration?

Answer: The open-source library created by Hugging Face to simplify Transformer acceleration is called **Accelerate**.

True answer: Optimum

 97%|█████████▋| 63/65 [05:58<00:11,  5.71s/it]

=======================================================
Question: What parameter is used to ensure that elements in a row have the same height in Gradio?

Answer: The `equal_height` parameter should be passed to the `.style()` method of `gr.Row()` to ensure that elements in a row have the same height in Gradio.

True answer: equal_height

 98%|█████████▊| 64/65 [06:04<00:05,  5.69s/it]

=======================================================
Question: What is the command to install the latest version of Optimum with OpenVINO support?

Answer: ```bash
pip install --upgrade-strategy eager optimum[openvino,nncf]
```

True answer: pip install --upgrade-strategy eager optimum["openvino"]

100%|██████████| 65/65 [06:10<00:00,  5.69s/it]

In [44]:
##### using vanilla LLM to answer questions

# answer_llm = OpenAIServerModel(
#     model_id=models[4],
#     api_base="https://helmholtz-blablador.fz-juelich.de:8000/v1",
#     api_key=Blablador_API_KEY,
#     # flatten_messages_as_text=True,
#     temperature=0.2)

outputs_standard = []

for example in tqdm(eval_dataset):
    question = example["question"]

    prompt = f"""Answer the following question as clearly and concisely as possible.
Use your own knowledge to respond.
If the question is ambiguous or cannot be answered definitively, state so clearly.

Question:
{question}

"""
    messages = [{"role": "user", "content": prompt}]
    answer = answer_llm.generate(messages).content

    print("=======================================================")
    print(f"Question: {question}")
    print(f"Answer: {answer}")
    print(f'True answer: {example["answer"]}')

    results_llm = {
        "question": question,
        "true_answer": example["answer"],
        "source_doc": example["source_doc"],
        "generated_answer": answer,
    }
    outputs_standard.append(results_llm)
    time.sleep(5)

  0%|          | 0/65 [00:00<?, ?it/s]

=======================================================
Question: What architecture is the `tokenizers-linux-x64-musl` binary designed for?

Answer: The `tokenizers-linux-x64-musl` binary is designed for Linux systems using the x86-64 (also known as amd64) architecture and the musl C standard library.

True answer: x86_64-unknown-linux-musl

  2%|▏         | 1/65 [00:05<06:10,  5.79s/it]

=======================================================
Question: What is the purpose of the BLIP-Diffusion model?

Answer: The BLIP-Diffusion model aims to improve the quality and controllability of text-to-image generation by leveraging the BLIP (Bootstrapping Language-Image Pre-training) model. Its purpose is to generate images that are more faithful to the given text prompt and offer better control over the image's composition and style.

True answer: The BLIP-Diffusion model is designed for controllable text-to-image generation and editing.

  3%|▎         | 2/65 [00:11<06:06,  5.81s/it]

=======================================================
Question: How can a user claim authorship of a paper on the Hugging Face Hub?

Answer: A user can claim authorship of a paper on the Hugging Face Hub by:

1.  **Linking the Paper in the Model Card:** Edit the model card (README.md) of the relevant model/dataset repository on the Hub. Include a section, often titled "Citation" or "References," where you provide the BibTeX entry or a direct link to the paper.  Explicitly state that the paper describes the model/dataset.

2.  **Adding the Paper to the Hugging Face Papers Section (if applicable):** Hugging Face has a papers section. If the paper isn't already there, you can potentially submit it (check Hugging Face's documentation for the exact process, as it may involve a pull request or a specific submission form).  Linking the paper to the relevant models/datasets during this submission process is crucial.

3.  **Using the `inference=false` tag:** If the paper describes a model that *cannot* be used for inference, add the `inference=false` tag to the model card. This helps users understand the purpose of the model and its relation to the paper.

4.  **Community Engagement:** Engage in discussions on the Hub, in forums, or on social media, clearly stating your role as an author of the paper and its connection to the model/dataset.

It's important to note that Hugging Face relies on users to accurately represent authorship.  Misrepresenting authorship is unethical.

True answer: By clicking their name on the corresponding Paper page and clicking "claim authorship", then confirming the request in paper settings for admin team validation.

  5%|▍         | 3/65 [00:19<06:49,  6.61s/it]

=======================================================
Question: What is the purpose of the /healthcheck endpoint in the Datasets server API?

Answer: The `/healthcheck` endpoint in the Datasets Server API is used to determine the health and availability of the server. It typically returns a simple "OK" or a 200 status code if the server is running and responsive. This allows monitoring systems and other services to automatically check if the Datasets Server is operational and ready to serve requests.

True answer: Ensure the app is running

  6%|▌         | 4/65 [00:25<06:28,  6.37s/it]

=======================================================
Question: What is the default context window size for Local Attention in the LongT5 model?

Answer: The default context window size for Local Attention in the LongT5 model is **256**.

True answer: 127 tokens

  8%|▊         | 5/65 [00:30<06:06,  6.11s/it]

=======================================================
Question: What method is used to load a checkpoint for a task using `AutoPipeline`?

Answer: The `AutoPipeline` class in libraries like Hugging Face's Transformers uses the `from_pretrained()` method to load a checkpoint. You provide the checkpoint's path or name (e.g., a model name from the Hugging Face Model Hub) as an argument to `from_pretrained()`.

True answer: from_pretrained()

  9%|▉         | 6/65 [00:36<05:55,  6.02s/it]

=======================================================
Question: What is the purpose of Diffusers library?

Answer: The Diffusers library, primarily developed by Hugging Face, provides pre-trained diffusion models and modular components for creating and experimenting with diffusion-based generative AI models. Its purpose is to make diffusion models more accessible and easier to use for researchers, developers, and artists.

True answer: To serve as a modular toolbox for both inference and training of state-of-the-art pretrained diffusion models across multiple modalities.

 11%|█         | 7/65 [00:42<05:44,  5.94s/it]

=======================================================
Question: What method does the EulerAncestralDiscreteScheduler use for sampling?

Answer: The EulerAncestralDiscreteScheduler uses a **stochastic Euler method** (also known as Euler-Maruyama) for sampling. It's a first-order numerical method for solving stochastic differential equations (SDEs). The "ancestral" part refers to how it handles noise; it adds noise at each step based on the schedule and the previous step's noise level, ensuring the noise is consistent with the diffusion process.

True answer: Ancestral sampling with Euler method steps.

 12%|█▏        | 8/65 [00:48<05:40,  5.97s/it]

=======================================================
Question: What is the name of the large multimodal model that can solve image-text tasks and is based on Flamingo?

Answer: There isn't a single, universally recognized "large multimodal model based on Flamingo" that is definitively *the* answer.

However, **Flamingo** *is* the name of the large multimodal model developed by Google DeepMind that excels at image-text tasks. It's the foundation upon which other models might be built or inspired by.

Therefore, the most direct and accurate answer is **Flamingo**.

It's important to note that Google and other organizations are constantly developing new models, so there might be newer, more advanced models based on Flamingo's architecture, but they would likely have different names.

True answer: IDEFICS

 14%|█▍        | 9/65 [00:54<05:39,  6.07s/it]

=======================================================
Question: What is the purpose of the `gradio.Blocks` API?

Answer: The purpose of the `gradio.Blocks` API is to provide a **low-level, highly customizable interface for building complex Gradio web applications**.  It allows developers to create custom layouts, define complex input/output relationships, and manage application state in a more flexible way than the simpler `gradio.Interface` API.  Essentially, it gives you fine-grained control over the structure and behavior of your Gradio app.

True answer: The `gradio.Blocks` API allows you to have full control over the data flows and layout of your application, enabling the building of complex, multi-step applications.

 15%|█▌        | 10/65 [01:00<05:35,  6.10s/it]

=======================================================
Question: What is the purpose of the two-stage model proposed in the paper "Hierarchical Text-Conditional Image Generation with CLIP Latents"?

Answer: The two-stage model in "Hierarchical Text-Conditional Image Generation with CLIP Latents" (often referred to as DALL-E 2) serves the purpose of **decoupling the text-to-image generation process into two distinct stages to improve image quality and controllability.**

Specifically:

*   **Stage 1 (Prior):** This stage maps the input text prompt to a CLIP image embedding. The CLIP image embedding acts as a semantic representation of the text, capturing the key visual concepts described in the text. This stage is crucial for understanding the text and translating it into a visual representation.

*   **Stage 2 (Decoder):** This stage takes the CLIP image embedding generated by the prior and uses it to generate the final image. This stage focuses on generating high-quality, realistic images that accurately reflect the visual concepts encoded in the CLIP embedding.

By separating the process into these two stages, DALL-E 2 can leverage the strengths of CLIP's semantic understanding in the first stage and focus on high-fidelity image generation in the second stage. This approach allows for better control over the generated image and results in higher quality and more accurate image generation compared to single-stage models.

True answer: The purpose of the two-stage model is to generate a CLIP image embedding given a text caption and then generate an image conditioned on the image embedding.

 17%|█▋        | 11/65 [01:08<05:46,  6.42s/it]

=======================================================
Question: What command is used to install the requirements for a research project using 🤗 Transformers?

Answer: The command used to install the requirements for a research project using 🤗 Transformers is typically:

```bash
pip install -r requirements.txt
```

This assumes that the project has a `requirements.txt` file listing all the necessary packages, including `transformers` itself, along with any other dependencies like `torch`, `tensorflow`, `datasets`, etc.  If a `requirements.txt` file does not exist, you can install the transformers package directly using:

```bash
pip install transformers
```

You may also need to install other packages depending on the specific needs of your project.

True answer: pip install -r requirements.txt

 18%|█▊        | 12/65 [01:14<05:33,  6.30s/it]

=======================================================
Question: What task does the `roberta-large-mnli` checkpoint perform?

Answer: The `roberta-large-mnli` checkpoint performs **natural language inference (NLI)**, specifically trained on the **Multi-Genre Natural Language Inference (MNLI)** dataset. It's designed to determine the relationship between two sentences: a premise and a hypothesis. The model classifies the relationship as either entailment, contradiction, or neutral.

True answer: Text classification

 20%|██        | 13/65 [01:19<05:20,  6.16s/it]

=======================================================
Question: What service is replacing the Paid tier of the Inference API at Hugging Face?

Answer: The Inference Endpoints service is replacing the Paid tier of the Inference API at Hugging Face.

True answer: Inference Endpoints

 22%|██▏       | 14/65 [01:25<05:10,  6.09s/it]

=======================================================
Question: What architectural feature does SqueezeBERT use instead of fully-connected layers for the Q, K, V, and FFN layers?

Answer: SqueezeBERT uses **grouped convolutions** instead of fully-connected layers for the Q, K, V (query, key, value) projections in the attention mechanism and for the feed-forward network (FFN) layers.

True answer: Grouped convolutions

 23%|██▎       | 15/65 [01:31<04:56,  5.94s/it]

=======================================================
Question: What type of license is the HuggingFace Team's software distributed under?

Answer: Hugging Face uses a variety of licenses for their software, but primarily favors the **Apache 2.0 license** and the **MIT license**. The specific license used depends on the individual project or library within the Hugging Face ecosystem. It is important to check the license for each specific piece of software you intend to use.

True answer: Apache License, Version 2.0

 25%|██▍       | 16/65 [01:37<04:49,  5.92s/it]

=======================================================
Question: What are the two parameter-reduction techniques proposed in the ALBERT model to lower memory consumption and increase training speed?

Answer: The two main parameter-reduction techniques in ALBERT are:

1.  **Factorized Embedding Parameterization:** Instead of directly projecting the one-hot encoded vocabulary to a high-dimensional embedding space, ALBERT projects it to a lower-dimensional space first, and then to the high-dimensional space. This reduces the number of embedding parameters from V * H to V * E + E * H, where V is the vocabulary size, H is the hidden size, and E is the embedding size (E < H).

2.  **Cross-Layer Parameter Sharing:** ALBERT shares parameters across different layers of the Transformer encoder. This drastically reduces the number of parameters that need to be learned, as all layers essentially use the same set of parameters (or a subset of parameters).

True answer: Splitting the embedding matrix into two smaller matrices and using repeating layers split among groups.

 26%|██▌       | 17/65 [01:43<04:52,  6.10s/it]

=======================================================
Question: What are the three main steps for fine-tuning a model with the 🤗 Datasets library?

Answer: While the 🤗 Datasets library primarily focuses on data loading and preparation, not the fine-tuning process itself, here's how it integrates into a typical fine-tuning workflow, highlighting the three main steps where it plays a crucial role:

1.  **Load and Prepare the Dataset:** Use `datasets.load_dataset()` to load your dataset (e.g., from Hugging Face Hub, a local file, or a custom script).  Then, use the `map()` function to preprocess the data. This includes tokenization (using a 🤗 Transformers tokenizer), potentially formatting the data into the expected input format for your model, and any other necessary transformations.

2.  **Create DataLoaders (Optional but Recommended):** While not strictly required by all training loops, creating `torch.utils.data.DataLoader` (or TensorFlow equivalents) from your `datasets.Dataset` object is common. This handles batching, shuffling, and parallel data loading, optimizing the training process.  The 🤗 Datasets library integrates seamlessly with PyTorch and TensorFlow.

3.  **Evaluate with Metrics (Integration):** After fine-tuning, use the `datasets.load_metric()` function to load evaluation metrics (e.g., accuracy, F1-score).  You can then use the `compute()` method of the loaded metric object to calculate the performance of your fine-tuned model on a held-out evaluation set that you've loaded and prepared using 🤗 Datasets.

In summary, the 🤗 Datasets library is primarily used for loading, preprocessing, and evaluating data during fine-tuning, rather than handling the actual training loop itself.

True answer: 1. Load a dataset from the Hugging Face Hub. 2. Preprocess the data with `Dataset.map()`. 3. Load and compute metrics.

 28%|██▊       | 18/65 [01:51<05:11,  6.63s/it]

=======================================================
Question: What is the maximum improvement in throughput achieved by Hugging Face Infinity compared to vanilla transformers?

Answer: Hugging Face claims that Infinity can achieve up to **10x** throughput improvement compared to vanilla Transformers. However, this is a *maximum* improvement, and the actual performance gain depends heavily on factors like:

*   **Model architecture:** Some models benefit more from Infinity's optimizations than others.
*   **Hardware:** The underlying hardware (CPU, GPU, etc.) significantly impacts performance.
*   **Batch size:** Infinity's optimizations often shine at larger batch sizes.
*   **Sequence length:** Shorter sequences may not see as dramatic an improvement.
*   **Specific optimizations enabled:** Infinity offers various optimization techniques, and the combination used affects the outcome.

Therefore, while a 10x improvement is possible under ideal conditions, it's not a guaranteed result.

True answer: +800%

 29%|██▉       | 19/65 [01:58<05:01,  6.56s/it]

=======================================================
Question: What is the command to upload a spaCy pipeline to the Hugging Face Hub?

Answer: The command to upload a spaCy pipeline to the Hugging Face Hub is:

```bash
spacy project push-hf
```

This command assumes you are within a spaCy project directory that has been initialized with `spacy project init`. It packages your pipeline and uploads it to your specified Hugging Face Hub repository. You will likely be prompted for your Hugging Face credentials if you haven't already logged in via the `huggingface-cli login` command.

True answer: python -m spacy huggingface-hub push en_ner_fashion-0.0.0-py3-none-any.whl

 31%|███       | 20/65 [02:04<04:47,  6.38s/it]

=======================================================
Question: What is the time and memory complexity of the Nyströmformer's approximation of self-attention?

Answer: The Nyströmformer approximates self-attention with a time complexity of **O(n*m)** and a memory complexity of **O(n*m)**, where *n* is the sequence length and *m* is the number of landmarks (selected tokens) used in the approximation, with *m << n*.

True answer: O(n)

 32%|███▏      | 21/65 [02:09<04:33,  6.22s/it]

=======================================================
Question: What is the goal of the Named Entity Recognition task in token classification?

Answer: The goal of Named Entity Recognition (NER) in token classification is to **identify and classify named entities within a text into predefined categories.**

In simpler terms, it aims to:

1.  **Locate:** Find the spans of text that represent named entities (e.g., "Apple", "Paris", "July 4th").
2.  **Categorize:** Assign a label to each identified entity, indicating its type (e.g., ORGANIZATION, LOCATION, DATE).

So, the output of NER is a text where each token is labeled with either a named entity type or a label indicating it's not part of any named entity.

True answer: The goal of the Named Entity Recognition task is to find the entities in a piece of text, such as person, location, or organization.

 34%|███▍      | 22/65 [02:16<04:27,  6.23s/it]

=======================================================
Question: What is the resolution of images used by the CLIPSeg model?

Answer: The CLIPSeg model doesn't have a fixed input resolution. It can accept images of varying sizes. However, larger images will require more memory and processing time. It's common to resize images to a reasonable size (e.g., 384x384 or 512x512) for efficiency, but the model itself isn't strictly limited to a specific resolution.

True answer: 352 x 352 pixels

 35%|███▌      | 23/65 [02:22<04:19,  6.18s/it]

=======================================================
Question: What can you use Gradio for?

Answer: Gradio is primarily used for **quickly creating and sharing interactive web interfaces for machine learning models, APIs, or arbitrary Python functions.**

Specifically, you can use Gradio to:

*   **Demo and test models:** Easily build a user-friendly interface to showcase your model's capabilities and get feedback.
*   **Share models with others:** Generate a shareable link to allow others to interact with your model without needing to install any software.
*   **Gather data and feedback:** Collect user input and model outputs to improve your model's performance.
*   **Create educational tools:** Build interactive applications to teach others about machine learning concepts.
*   **Prototype and iterate rapidly:** Quickly experiment with different model architectures and user interface designs.

True answer: Create a demo for your machine learning model, share your machine learning model with others, and debug your model.

 37%|███▋      | 24/65 [02:28<04:17,  6.29s/it]

=======================================================
Question: What TensorFlow API function is used to load a saved tensor file?

Answer: The TensorFlow API function used to load a saved tensor file (specifically a file saved using `tf.io.write_file` and containing a serialized tensor) is `tf.io.read_file`.

True answer: safetensors.tensorflow.load_file

 38%|███▊      | 25/65 [02:34<04:05,  6.13s/it]

=======================================================
Question: Where can you access the logs of your Endpoints in Hugging Face Endpoints?

Answer: You can access the logs of your Hugging Face Endpoints in the **Hugging Face Hub**. Specifically, you'll find them within the **Endpoint's page** itself.

Navigate to your Endpoint on the Hub, and there should be a section or tab dedicated to "Logs" or "Monitoring". This section typically provides access to both:

*   **Request Logs:** Showing details about incoming requests, including timestamps, input data (if enabled), and response times.
*   **Server Logs:** Providing insights into the server's internal operations, including errors, warnings, and debugging information.

True answer: In the "Logs" tab of your Endpoint through the UI.

 40%|████      | 26/65 [02:40<04:00,  6.16s/it]

=======================================================
Question: What is the latest task added to Hugging Face AutoTrain for Computer Vision?

Answer: As of my last knowledge update, the latest task added to Hugging Face AutoTrain for Computer Vision is **Object Detection**.

True answer: Image Classification

 42%|████▏     | 27/65 [02:46<03:46,  5.97s/it]

=======================================================
Question: What is the default repository type created by the `create_repo` function on Hugging Face Hub?

Answer: The default repository type created by the `create_repo` function on the Hugging Face Hub is a **model repository**.

True answer: model

 43%|████▎     | 28/65 [02:51<03:36,  5.85s/it]

=======================================================
Question: How many splits does the "duorc" dataset have?

Answer: The "duorc" dataset has two splits: **ParaphraseQA** and **SelfQA**.

True answer: Six

 45%|████▍     | 29/65 [02:57<03:27,  5.77s/it]

=======================================================
Question: What is the purpose of Fully Sharded Data Parallel (FSDP) in distributed training?

Answer: The purpose of Fully Sharded Data Parallel (FSDP) in distributed training is to **enable training of very large models that would otherwise not fit in the memory of a single GPU.**

It achieves this by sharding (splitting) the model parameters, optimizer states, and gradients across multiple GPUs. This reduces the memory footprint on each individual GPU, allowing for larger models and batch sizes to be used. FSDP dynamically gathers the necessary shards during the forward and backward passes, performing computations efficiently while minimizing memory usage.

True answer: FSDP is developed for distributed training of large pretrained models up to 1T parameters by sharding the model parameters, gradients, and optimizer states across data parallel processes.

 46%|████▌     | 30/65 [03:03<03:25,  5.88s/it]

=======================================================
Question: What file format is used to save and store PyTorch model weights more securely than `.bin` files?

Answer: There isn't a single file format that inherently provides *more* security than `.bin` files for storing PyTorch model weights. Security depends more on how the files are handled (encryption, access control, etc.) than the file format itself.

However, `.pth` or `.pt` are the *conventionally* used file extensions for saving PyTorch models. These files are typically Python pickle files, which can store the model's state dictionary (weights and biases).

While `.pth` or `.pt` offer no inherent security advantage over `.bin`, using them signals intent and allows for easier integration with PyTorch's loading and saving mechanisms.

**To achieve better security, regardless of the file format (.bin, .pth, .pt), you should focus on:**

*   **Encryption:** Encrypt the model weights before saving them to disk.
*   **Access Control:** Restrict access to the model weight files using appropriate file system permissions.
*   **Secure Storage:** Store the model weights in a secure location, such as a dedicated server or cloud storage with access controls.
*   **Integrity Checks:** Use checksums or digital signatures to verify the integrity of the model weights.

In summary, the file format itself doesn't guarantee security. Security is achieved through proper handling and protection of the model weights.

True answer: `.safetensors`

 48%|████▊     | 31/65 [03:10<03:31,  6.22s/it]

=======================================================
Question: What type of security certification does Hugging Face have?

Answer: As of my knowledge cutoff date, Hugging Face does not publicly advertise or claim to hold any specific, formal security certifications like SOC 2, ISO 27001, or FedRAMP.

It's possible they have internal certifications or are working towards external ones, but this information is not readily available.

True answer: SOC2 Type 2 certified

 49%|████▉     | 32/65 [03:16<03:22,  6.13s/it]

=======================================================
Question: What do RAG models combine to generate outputs?

Answer: RAG (Retrieval-Augmented Generation) models combine two main components to generate outputs:

1.  **A pre-trained language model (LLM):** This provides the general knowledge and text generation capabilities.
2.  **Retrieved information from an external knowledge source:** This provides specific, up-to-date, and relevant information that the LLM uses to ground its response.

In essence, RAG models retrieve relevant information and then use the LLM to generate an output that is informed by both its pre-existing knowledge and the retrieved context.

True answer: Pretrained dense retrieval (DPR) and sequence-to-sequence models.

 51%|█████     | 33/65 [03:22<03:17,  6.18s/it]

=======================================================
Question: What library does MarkupLMFeatureExtractor use to extract data from HTML and XML files?

Answer: MarkupLMFeatureExtractor uses the **Beautiful Soup** library to extract data from HTML and XML files.

True answer: Beautiful Soup

 52%|█████▏    | 34/65 [03:28<03:05,  5.99s/it]

=======================================================
Question: What is the file size limit for syncing to HF Spaces without using Git-LFS?

Answer: Without using Git LFS, the file size limit for syncing to Hugging Face Spaces is **25MB per file**.

True answer: 10MB

 54%|█████▍    | 35/65 [03:33<02:54,  5.83s/it]

=======================================================
Question: What is the title of the paper introducing the ByT5 model?

Answer: The paper introducing the ByT5 model is titled **"ByT5: Towards a token-free future with pre-trained byte-to-byte models"**.

True answer: ByT5: Towards a token-free future with pre-trained byte-to-byte models

 55%|█████▌    | 36/65 [03:39<02:47,  5.78s/it]

=======================================================
Question: What is the dimension of the feature vector for the base BERT model?

Answer: The dimension of the feature vector (also known as the hidden size or embedding dimension) for the base BERT model is **768**.

True answer: 768

 57%|█████▋    | 37/65 [03:45<02:40,  5.73s/it]

=======================================================
Question: What special identifier does the WordPiece Model use for continuing subwords?

Answer: The WordPiece model, and its common implementation in BERT and related models, uses the prefix "##" to denote that a subword is a continuation of a previous word piece.

True answer: ##

 58%|█████▊    | 38/65 [03:50<02:34,  5.73s/it]

=======================================================
Question: What is the purpose of the 🧨 Diffusers tutorials?

Answer: The purpose of the Diffusers tutorials is to guide users on how to effectively use the Hugging Face Diffusers library for generating images, audio, and other data using diffusion models. They aim to provide practical, hands-on examples and explanations to help users learn the core concepts and functionalities of the library, enabling them to create and customize their own diffusion-based generative models.

True answer: To provide a gentle introduction to diffusion models and help understand the library fundamentals.

 60%|██████    | 39/65 [03:56<02:29,  5.76s/it]

=======================================================
Question: What is the default setting for the `allow_flagging` parameter in Gradio's `Interface`?

Answer: The default setting for the `allow_flagging` parameter in Gradio's `Interface` is `"auto"`.

True answer: "manual"

 62%|██████▏   | 40/65 [04:02<02:22,  5.70s/it]

=======================================================
Question: Where can the full code for the Stable Diffusion demo be found?

Answer: The full code for the *original* Stable Diffusion demo, as presented by Stability AI, is **not publicly available as a single, unified codebase.**

Here's why and what you *can* find:

*   **Core Model Weights:** The core Stable Diffusion model weights are publicly available. This is the crucial part that allows you to generate images.
*   **Diffusers Library:** The most common way to interact with Stable Diffusion is through the Hugging Face `diffusers` library. This library provides a high-level API and example code for running inference, training, and fine-tuning Stable Diffusion. You can find many example scripts and notebooks on the Hugging Face Hub and in the `diffusers` repository.
*   **Individual Demos/Implementations:** Many individuals and organizations have created their own demos and implementations of Stable Diffusion using the core model weights and libraries like `diffusers`. These are often available on GitHub or other code repositories.
*   **Stability AI's Commercial Offerings:** Stability AI offers commercial APIs and services built on Stable Diffusion. The code for these specific services is generally proprietary.

In summary, you won't find a single "Stable Diffusion demo" repository with all the code. Instead, you'll find the core model weights, libraries like `diffusers` that make it easy to use the model, and numerous individual demos and implementations built by the community.

True answer: https://hf.co/spaces/stabilityai/stable-diffusion/tree/main

 63%|██████▎   | 41/65 [04:09<02:28,  6.19s/it]

=======================================================
Question: What transformation does the FNet model use to replace the self-attention layer in a BERT model?

Answer: The FNet model replaces the self-attention layer in a BERT model with a **Fourier Transform**. Specifically, it applies a Fourier Transform to the input sequence in the frequency domain and then applies an inverse Fourier Transform to return to the time domain. This process is done separately for the real and imaginary parts of the input.

True answer: Fourier transform

 65%|██████▍   | 42/65 [04:18<02:41,  7.04s/it]

=======================================================
Question: What type of test should typically accompany a bug fix in Gradio's testing strategy?

Answer: A bug fix in Gradio should typically be accompanied by a **regression test**.

A regression test is specifically designed to verify that the bug has been fixed and, crucially, that the fix hasn't introduced any new issues or broken existing functionality. It ensures that the bug *doesn't regress* (reappear) in future versions of the code.

True answer: Dynamic code test

 66%|██████▌   | 43/65 [04:24<02:26,  6.66s/it]

=======================================================
Question: How can you force mixed precision training when initializing the Accelerator in 🤗 Accelerate?

Answer: You can force mixed precision training when initializing the `Accelerator` in 🤗 Accelerate using the `mixed_precision` argument.  You can set it to either `"fp16"` or `"bf16"` to enable the corresponding mixed precision mode.

Example:

```python
from accelerate import Accelerator

# Force FP16 mixed precision
accelerator_fp16 = Accelerator(mixed_precision="fp16")

# Force BF16 mixed precision
accelerator_bf16 = Accelerator(mixed_precision="bf16")
```

If you don't specify `mixed_precision`, Accelerate will try to determine the best mixed precision mode automatically based on your hardware and environment.

True answer: By passing `fp16=True` to the Accelerator init.

 68%|██████▊   | 44/65 [04:30<02:17,  6.55s/it]

=======================================================
Question: What is the purpose of tokenizers in the NLP pipeline?

Answer: The purpose of tokenizers in the NLP pipeline is to **break down raw text into smaller units called tokens**. These tokens are typically words, sub-words, or characters, and they serve as the fundamental building blocks for further processing, such as:

*   **Feature extraction:** Tokens are used to create numerical representations of the text (e.g., word embeddings, TF-IDF vectors) that machine learning models can understand.
*   **Vocabulary creation:** Tokenizers help define the vocabulary of a model by identifying the unique tokens present in the training data.
*   **Text normalization:** Tokenization can involve lowercasing, stemming, or lemmatization, which helps to standardize the text and improve model performance.
*   **Parsing and analysis:** Tokens provide a structured representation of the text that facilitates syntactic and semantic analysis.

True answer: To translate text into data that can be processed by the model.

 69%|██████▉   | 45/65 [04:37<02:11,  6.56s/it]

=======================================================
Question: What is the purpose of the Safety Checker in the Diffusers library?

Answer: The Safety Checker in the Diffusers library is designed to **detect and mitigate potentially harmful or inappropriate content generated by diffusion models, primarily images.** It aims to prevent the generation of outputs that violate safety guidelines, such as those containing:

*   **Hate speech:** Content that promotes violence or discrimination against individuals or groups based on protected characteristics.
*   **Violence:** Graphic or explicit depictions of violence.
*   **Sexual content:** Explicit or suggestive sexual imagery, particularly involving minors.
*   **Other harmful content:** Content that could be considered offensive, dangerous, or illegal.

The Safety Checker typically works by analyzing the generated image and comparing it to a database of known harmful concepts or patterns. If a potential safety violation is detected, the Safety Checker can take actions such as:

*   **Blurring the image:** Obscuring the potentially harmful content.
*   **Replacing the image:** Substituting the generated image with a safe alternative.
*   **Blocking the image:** Preventing the image from being displayed or saved.
*   **Raising a flag:** Alerting the user or administrator about the potential safety issue.

The specific implementation and effectiveness of the Safety Checker can vary depending on the model, configuration, and the specific safety guidelines being enforced.

True answer: The Safety Checker checks and compares the class probability of a set of hard-coded harmful concepts in the embedding space against an image after it has been generated to mitigate the risk of generating harmful content.

 71%|███████   | 46/65 [04:44<02:07,  6.71s/it]

=======================================================
Question: What Python class allows you to retrieve Discussions and Pull Requests from a given repository on the Hugging Face Hub?

Answer: The `huggingface_hub` library doesn't have a single, dedicated class that *directly* retrieves both Discussions and Pull Requests. However, you can achieve this using a combination of the `HfApi` class and its methods.

Specifically, you would use the `HfApi` class to:

1.  **Retrieve Discussions:** Use the `get_repo_discussions` method.
2.  **Retrieve Pull Requests:** Use the `get_repo_discussions` method, filtering for discussions that are pull requests (usually identified by a specific tag or status).

Therefore, while there isn't *one* class, the `HfApi` class is the primary tool, and you'd use its `get_repo_discussions` method (with filtering) to get both discussions and pull requests.

True answer: HfApi

 72%|███████▏  | 47/65 [04:50<01:58,  6.61s/it]

=======================================================
Question: What is the name of the new library introduced by Hugging Face for hosting scikit-learn models?

Answer: Hugging Face does not have a dedicated library specifically for hosting scikit-learn models. However, scikit-learn models can be hosted on the Hugging Face Hub using libraries like `gradio` or `streamlit` to create an interface, or by creating a custom inference endpoint using frameworks like `transformers` and deploying it on Hugging Face Inference Endpoints.

True answer: Skops

 74%|███████▍  | 48/65 [04:56<01:48,  6.39s/it]

=======================================================
Question: What is the purpose of Textual Inversion?

Answer: The purpose of Textual Inversion is to personalize and customize text-to-image models (like Stable Diffusion) by teaching them new concepts or styles using only a few example images, without retraining the entire model. It achieves this by finding a new "token" (a sequence of characters) in the model's vocabulary that, when used in a prompt, produces images resembling the provided examples. This allows users to inject specific objects, styles, or even people into the generated images with minimal data and computational cost.

True answer: Textual Inversion is a training method for personalizing models by learning new text embeddings from a few example images.

 75%|███████▌  | 49/65 [05:02<01:41,  6.33s/it]

=======================================================
Question: What is the recommended multiple of batch size for fp16 data type on an A100 GPU?

Answer: While there isn't a single, universally "recommended" multiple for batch size with FP16 on an A100, **multiples of 8 are generally recommended and often necessary to achieve optimal performance due to the Tensor Cores' architecture.**

Here's why:

*   **Tensor Cores:** A100 GPUs leverage Tensor Cores, which are specialized hardware units designed for accelerating matrix multiplications, the core operation in deep learning. Tensor Cores operate most efficiently when the input matrices have dimensions that are multiples of 8 (or sometimes 16, depending on the specific operation and library).

*   **FP16 and Tensor Cores:** FP16 (half-precision floating point) is commonly used with Tensor Cores to increase throughput and reduce memory footprint. To fully utilize the Tensor Cores with FP16, the batch size (and other relevant dimensions like sequence length in NLP) should be multiples of 8.

*   **Performance Degradation:** If the batch size is not a multiple of 8, the Tensor Cores might not be fully utilized, leading to performance degradation. The GPU may fall back to using standard CUDA cores, which are less efficient for matrix multiplications.

*   **Library Specifics:** The exact optimal multiple can sometimes depend on the specific deep learning framework (PyTorch, TensorFlow) and the libraries used (cuDNN, etc.). Some libraries might handle padding automatically to ensure compatibility with Tensor Cores, but it's still generally best practice to use multiples of 8.

**In summary:** Aim for batch sizes that are multiples of 8 when using FP16 on an A100 to maximize Tensor Core utilization and achieve optimal performance. While other factors can influence performance, this is a crucial starting point.

True answer: 64

 77%|███████▋  | 50/65 [05:10<01:41,  6.74s/it]

=======================================================
Question: How do you run a Gradio Blocks app in reload mode using a Python IDE?

Answer: While Gradio doesn't have a built-in "reload mode" like some web frameworks, you can achieve a similar effect within a Python IDE by leveraging the IDE's debugging and auto-reload features, or by using a separate file-watching library. Here's how:

**1. IDE Debugger with Restart:**

   *   **Set Breakpoints:** Place breakpoints in your Gradio Blocks app code where you want to inspect variables or step through execution.
   *   **Run in Debug Mode:** Start your script using the IDE's debugger.
   *   **Modify and Restart:** When you make changes to your code, stop the debugger and restart it.  This effectively reloads the app with the updated code.  This is the most common and reliable method.

**2. IDE Auto-Reload (If Supported):**

   *   Some IDEs (like VS Code with specific extensions) have features that automatically restart the script when changes are detected in the source files.  Configure your IDE to enable this feature for your Gradio app's main script.  This is the closest you'll get to a true "reload mode."

**3. External File Watcher (e.g., `watchdog`):**

   *   Install the `watchdog` library: `pip install watchdog`
   *   Create a separate script (or integrate into your main script) that uses `watchdog` to monitor your Gradio app's files. When a change is detected, the script can restart your Gradio app process.

   ```python
   import time
   import subprocess
   from watchdog.observers import Observer
   from watchdog.events import FileSystemEventHandler

   class GradioHandler(FileSystemEventHandler):
       def __init__(self, command):
           self.command = command
           self.process = None

       def on_modified(self, event):
           if event.is_directory:
               return
           print(f"File changed: {event.src_path}. Restarting Gradio app...")
           self.restart_app()

       def start_app(self):
           self.process = subprocess.Popen(self.command)

       def restart_app(self):
           if self.process:
               self.process.terminate()
               self.process.wait()  # Ensure process is terminated
           self.start_app()

   if __name__ == "__main__":
       command = ["python", "your_gradio_app.py"]  # Replace with your app's execution command
       event_handler = GradioHandler(command)
       observer = Observer()
       observer.schedule(event_handler, path=".", recursive=True)  # Watch the current directory recursively
       observer.start()
       event_handler.start_app() # Start the app initially

       try:
           while True:
               time.sleep(1)
       except KeyboardInterrupt:
           observer.stop()
           if event_handler.process:
               event_handler.process.terminate()
               event_handler.process.wait()
       observer.join()
   ```

   *   **Explanation:** This script watches for file changes in the current directory (or a specified directory). When a change is detected, it terminates the existing Gradio app process and starts a new one.  Replace `"your_gradio_app.py"` with the name of your Gradio app's Python file.

**Important Considerations:**

*   **State Management:**  Reloading the app will reset its state.  If your app relies on persistent data, you'll need to implement a mechanism to save and restore that data across reloads (e.g., using a database or file storage).
*   **Dependencies:** Ensure that all necessary dependencies are installed in your environment.
*   **Error Handling:** Implement robust error handling to catch exceptions during the reload process.
*   **IDE Configuration:**  The specific steps for configuring auto-reload or debugging will vary depending on your IDE.  Consult your IDE's documentation.
*   **Gradio's `queue()`:** If your Gradio app uses `queue()`, be aware that restarting the app will interrupt any queued tasks.

In summary, while Gradio doesn't have a direct "reload mode," you can use IDE debugging, IDE auto-reload features (if available), or a file-watching library like `watchdog` to achieve a similar development workflow. The IDE debugger with manual restart is often the simplest and most reliable approach.

True answer: Run `gradio run.py` in the terminal.

 78%|███████▊  | 51/65 [05:21<01:53,  8.14s/it]

=======================================================
Question: How can you install the Hugging Face Unity API in your Unity project?

Answer: As of my last knowledge update, there isn't an officially supported "Hugging Face Unity API" directly provided by Hugging Face. However, you can integrate Hugging Face models and functionalities into your Unity project using a combination of methods:

1.  **Hugging Face Transformers.js:** You can use Transformers.js, a JavaScript library for running Hugging Face models in the browser, and then integrate it into your Unity project using Unity's JavaScript integration capabilities (e.g., `WebGL`). This involves:
    *   Exporting your Unity project as a WebGL build.
    *   Including Transformers.js and your desired model in the WebGL build.
    *   Using Unity's `Application.ExternalCall` or similar methods to call JavaScript functions that use Transformers.js to process data and return results to Unity.

2.  **Custom API Wrapper:** You can create a custom API wrapper that communicates with a server running your Hugging Face models. This involves:
    *   Setting up a server (e.g., using Python and Flask or FastAPI) that hosts your Hugging Face models.
    *   Creating API endpoints on the server to handle requests and return predictions.
    *   In your Unity project, use Unity's `UnityWebRequest` class to send HTTP requests to the server and receive responses.

3.  **ONNX Runtime:** Convert your Hugging Face model to ONNX format and use the ONNX Runtime Unity package to run the model directly within Unity. This approach can offer better performance than using JavaScript, but requires converting the model and ensuring compatibility.

**In summary, there is no direct "Hugging Face Unity API" for easy installation. You need to use one of the above methods to integrate Hugging Face models into your Unity project.** The best approach depends on your specific needs, performance requirements, and the complexity of the models you want to use.

True answer: To install the Hugging Face Unity API in your Unity project, go to `Window` -> `Package Manager`, click `+` and select `Add Package from git URL`, then enter `https://github.com/huggingface/unity-api.git`.

 80%|████████  | 52/65 [05:29<01:45,  8.14s/it]

=======================================================
Question: What is the pretraining objective of the Wav2Vec2 context network?

Answer: The pretraining objective of the Wav2Vec 2.0 context network is **contrastive learning**, specifically to **distinguish between quantized representations of the true masked audio segment and distractor quantized representations**.

In simpler terms:

*   The model is given a masked audio segment.
*   It predicts a quantized representation of the masked part.
*   It's also given several other (distractor) quantized representations.
*   The objective is to correctly identify which quantized representation corresponds to the actual masked audio segment.

This forces the context network to learn useful representations of the audio that can be used to differentiate between similar-sounding segments.

True answer: The pretraining objective of the Wav2Vec2 context network is a contrastive task where the model has to predict the true quantized speech representation of the masked prediction from a set of false ones.

 82%|████████▏ | 53/65 [05:36<01:32,  7.68s/it]

=======================================================
Question: What is the default checkpoint used by the sentiment analysis pipeline in the Transformers library?

Answer: The default checkpoint used by the sentiment analysis pipeline in the Transformers library depends on which pipeline you are using.

*   **`pipeline("sentiment-analysis")` (without specifying a model):** This defaults to `distilbert-base-uncased-finetuned-sst-2-english`. This model is a DistilBERT model fine-tuned on the SST-2 (Stanford Sentiment Treebank) dataset for binary sentiment classification (positive or negative).

It's important to note that the "default" can sometimes change with library updates, so it's always best practice to explicitly specify the model you want to use for reproducibility and clarity.

True answer: distilbert base uncased finetuned sst2 english

 83%|████████▎ | 54/65 [05:43<01:20,  7.33s/it]

=======================================================
Question: What is the purpose of the notebook "How to use DeepSpeed to train models with billions of parameters on Habana Gaudi"?

Answer: The purpose of the notebook "How to use DeepSpeed to train models with billions of parameters on Habana Gaudi" is to provide a practical guide and code examples demonstrating how to leverage the DeepSpeed library to train very large (billions of parameters) deep learning models efficiently on Habana Gaudi AI accelerators. It aims to help users understand and implement the necessary configurations and techniques to overcome memory limitations and achieve faster training speeds when working with massive models on Habana's hardware.

True answer: To show how to use DeepSpeed to pre-train/fine-tune the 1.6B-parameter GPT2-XL for causal language modeling on Habana Gaudi.

 85%|████████▍ | 55/65 [05:49<01:10,  7.03s/it]

=======================================================
Question: What command line module does PyTorch provide to run a script on multiple GPUs?

Answer: PyTorch provides the `torch.distributed.launch` command-line module (often aliased as `torchrun` or `python -m torch.distributed.launch`) to run a script on multiple GPUs using distributed data parallel (DDP).

True answer: torchrun

 86%|████████▌ | 56/65 [05:55<00:59,  6.64s/it]

=======================================================
Question: What is the most popular vision transformer model on the Hugging Face Model Hub for image classification?

Answer: Determining the *most* popular Vision Transformer (ViT) model on the Hugging Face Model Hub for image classification is tricky because popularity can be measured in different ways (downloads, likes, usage in projects, etc.), and these metrics fluctuate.

However, based on general awareness and common usage, some of the most popular and frequently used ViT models for image classification on the Hugging Face Model Hub include:

*   **google/vit-base-patch16-224:** This is a foundational ViT model and is often used as a starting point for fine-tuning.
*   **facebook/deit-base-distilled-patch16-224:** DeiT is a ViT variant that uses distillation techniques, often leading to improved performance.
*   **microsoft/beit-base-patch16-224:** BEiT is another popular ViT variant known for its masked image modeling pre-training approach.

It's important to check the Hugging Face Model Hub directly and sort by metrics like "downloads" or "likes" to get the most up-to-date view of popularity at any given time.

True answer: google/vit-base-patch16-224

 88%|████████▊ | 57/65 [06:02<00:54,  6.78s/it]

=======================================================
Question: What is the command to upload an ESPnet model to a Hugging Face repository?

Answer: There isn't a single, dedicated "ESPnet command" to directly upload a model to Hugging Face. ESPnet itself is a toolkit for end-to-end speech processing, and Hugging Face is a platform for sharing models.

The process generally involves these steps:

1.  **Save your ESPnet model:** Use ESPnet's functionalities to save your trained model to a local directory. This will typically involve saving model weights, configuration files (e.g., YAML), and potentially vocabulary files.

2.  **Create a Hugging Face Transformers compatible model (if necessary):**  Depending on the ESPnet model architecture, you might need to adapt it to be compatible with the Hugging Face Transformers library. This might involve creating a custom model class that inherits from a Transformers base class and loads the ESPnet weights.  This step is crucial for easy integration with the Hugging Face ecosystem.

3.  **Use the Hugging Face `transformers` library:**  The `transformers` library provides tools for uploading models.  The key command is usually used in conjunction with Python code:

    ```python
    from transformers import AutoModel, AutoTokenizer

    # Assuming you have a model and tokenizer loaded
    model = AutoModel.from_pretrained("path/to/your/model") # Or your custom model class
    tokenizer = AutoTokenizer.from_pretrained("path/to/your/tokenizer")

    # Push to Hugging Face Hub
    model.push_to_hub("your_model_name", organization="your_org_name") # Replace with your details
    tokenizer.push_to_hub("your_model_name", organization="your_org_name")
    ```

    *   `model.push_to_hub()` and `tokenizer.push_to_hub()` are the core functions.
    *   You'll need to be logged in to your Hugging Face account (using `huggingface-cli login` in your terminal).
    *   `your_model_name` is the name you want to give your model on the Hugging Face Hub.
    *   `your_org_name` is optional; it's your Hugging Face organization name if you're uploading to an organization.

4.  **Create a `README.md`:**  Include a `README.md` file in your repository describing your model, its intended use, training data, evaluation metrics, and any other relevant information.

**In summary:** There's no direct ESPnet command. You save your ESPnet model, potentially adapt it for Hugging Face Transformers, and then use the `transformers` library's `push_to_hub()` function to upload it.

True answer: ./run.sh --stage 15 --skip_upload_hf false --hf_repo username/model_repo

 89%|████████▉ | 58/65 [06:11<00:53,  7.58s/it]

=======================================================
Question: What file should be added to a model repository to install custom Python dependencies for Inference Endpoints?

Answer: A `requirements.txt` file should be added to the model repository to install custom Python dependencies for Inference Endpoints.

True answer: requirements.txt

 91%|█████████ | 59/65 [06:17<00:41,  7.00s/it]

=======================================================
Question: How many images are needed to teach new concepts to Stable Diffusion using Textual Inversion?

Answer: While there's no magic number, **generally, 3-50 images are used for Textual Inversion**.

*   **Fewer images (3-10):** Can work for simple concepts or styles, but might lead to overfitting or a less nuanced representation.
*   **More images (20-50):** Usually results in a more robust and generalizable embedding, especially for complex objects or styles with variations.

The optimal number depends on:

*   **Complexity of the concept:** A simple object (e.g., a specific hat) needs fewer images than a complex style (e.g., a particular painting technique).
*   **Image quality and diversity:** High-quality, diverse images are more effective than many similar or low-quality ones.
*   **Training parameters:** Learning rate, number of training steps, and other parameters influence the outcome.
*   **Desired level of accuracy:** More images generally lead to a more accurate representation of the concept.

Ultimately, experimentation is key to finding the right balance for your specific use case.

True answer: 3-5 images

 92%|█████████▏| 60/65 [06:24<00:34,  7.00s/it]

=======================================================
Question: What is the maximum size of a model checkpoint before it is automatically sharded in Transformers version 4.18.0?

Answer: Transformers version 4.18.0 does **not** automatically shard model checkpoints based on size. Sharding needs to be explicitly configured and enabled using features like Fully Sharded Data Parallel (FSDP) or other sharding strategies. There is no built-in, automatic sharding mechanism triggered by a size threshold in that version.

True answer: 10GB

 94%|█████████▍| 61/65 [06:30<00:26,  6.70s/it]

=======================================================
Question: What is the purpose of Weights and Biases (W&B) for data scientists and machine learning scientists?

Answer: Weights & Biases (W&B) is a platform designed to help data scientists and machine learning engineers track, visualize, and collaborate on their machine learning experiments. Its primary purposes are:

*   **Experiment Tracking:** Logging and tracking all aspects of an experiment, including hyperparameters, code versions, metrics (loss, accuracy, etc.), system resources (GPU usage), and even model weights. This allows for easy reproducibility and comparison of different runs.

*   **Visualization:** Providing interactive dashboards and visualizations to analyze experiment results, identify trends, and understand model behavior.

*   **Collaboration:** Enabling teams to share experiments, compare results, and collaborate on projects more effectively.

*   **Model Management:** Storing and versioning trained models, making it easier to deploy and track model performance over time.

In essence, W&B helps manage the complexity of the machine learning workflow, making it easier to iterate, debug, and improve models.

True answer: To track their machine learning experiments at every stage, from training to production.

 95%|█████████▌| 62/65 [06:37<00:20,  6.71s/it]

=======================================================
Question: What is the name of the open-source library created by Hugging Face to simplify Transformer acceleration?

Answer: The open-source library created by Hugging Face to simplify Transformer acceleration is called **Optimum**.

True answer: Optimum

 97%|█████████▋| 63/65 [06:42<00:12,  6.35s/it]

=======================================================
Question: What parameter is used to ensure that elements in a row have the same height in Gradio?

Answer: There isn't a single, dedicated parameter in Gradio to *directly* enforce equal height for elements within a `Row`. Gradio's layout primarily relies on CSS Flexbox.

To achieve equal height, you'd typically use CSS styling, either directly or by leveraging Gradio's `css` parameter within the `Row` component (or individual components within the row).  Common CSS approaches include:

*   **`align-items: stretch;`**:  This is often the most straightforward.  It tells the items within the flex container (the `Row`) to stretch to fill the available height.  You might need to ensure the parent container of the `Row` has a defined height or a height that allows the children to stretch.
*   **Setting explicit heights**: You could calculate the maximum height of the elements in the row and then set the `height` property of each element to that value. This is less flexible if content changes dynamically.
*   **Using JavaScript**:  You could use JavaScript to dynamically calculate the maximum height and apply it to the elements after the page loads.

Therefore, while no specific Gradio parameter exists, CSS styling, often in conjunction with the `css` parameter, is the mechanism to achieve equal height elements in a `Row`.

True answer: equal_height

 98%|█████████▊| 64/65 [06:49<00:06,  6.64s/it]

=======================================================
Question: What is the command to install the latest version of Optimum with OpenVINO support?

Answer: There isn't a single, definitive command to install the "latest version of Optimum with OpenVINO support" because the installation process can depend on your environment and desired level of customization. However, here's a breakdown of how you'd typically approach it, along with the most common commands:

**General Approach:**

1.  **Install Optimum:**  Optimum is the core library.
2.  **Install OpenVINO:**  You need the OpenVINO runtime.
3.  **Verify Installation:**  Confirm that Optimum recognizes OpenVINO.

**Commands (Typical):**

*   **Install Optimum:**

    ```bash
    pip install optimum
    ```

    This installs the base Optimum library.  To get the absolute latest (potentially unstable) version, you could use:

    ```bash
    pip install git+https://github.com/huggingface/optimum.git
    ```

*   **Install OpenVINO:**

    This is the trickiest part, as OpenVINO has its own installation methods.  The recommended way is usually through `pip`:

    ```bash
    pip install openvino
    ```

    However, sometimes you might need to install the OpenVINO Development Tools package:

    ```bash
    pip install openvino-dev
    ```

    Or, for more control, you might download and install the OpenVINO toolkit directly from the Intel website, following their specific instructions for your operating system.  This is often necessary for optimal performance or to use specific hardware acceleration features.

*   **Install OpenVINO-related dependencies for Optimum:**

    ```bash
    pip install optimum[openvino]
    ```

    This installs the extra dependencies required by Optimum to work with OpenVINO.

**Important Considerations:**

*   **OpenVINO Version Compatibility:**  Optimum might have specific OpenVINO version requirements. Check the Optimum documentation for compatibility information.  Using incompatible versions can lead to errors.
*   **Environment:**  Ensure you're using a Python environment (virtual environment is highly recommended) to avoid conflicts with other packages.
*   **Hardware:**  OpenVINO is optimized for Intel hardware.  Performance may vary on other platforms.
*   **Documentation:**  Always refer to the official Optimum and OpenVINO documentation for the most up-to-date and accurate installation instructions.  The Hugging Face and Intel websites are the primary sources.
*   **Troubleshooting:**  If you encounter issues, carefully read the error messages and consult the documentation or online forums for solutions.  Common problems include missing dependencies, incorrect environment variables, or version conflicts.

**In summary:**  While `pip install optimum` and `pip install openvino` are the starting points, a successful installation often requires additional steps and careful attention to version compatibility and environment configuration.  The `pip install optimum[openvino]` command is crucial for getting the necessary dependencies for Optimum to use OpenVINO. Always consult the official documentation for the most accurate and up-to-date instructions.

True answer: pip install --upgrade-strategy eager optimum["openvino"]

100%|██████████| 65/65 [06:59<00:00,  6.45s/it]

In [45]:
EVALUATION_PROMPT = """You are a fair evaluator language model.

You will be given an instruction, a response to evaluate, a reference answer that gets a score of 3, and a score rubric representing a evaluation criteria are given.
1. Write a detailed feedback that assess the quality of the response strictly based on the given score rubric, not evaluating in general.
2. After writing a feedback, write a score that is an integer between 1 and 3. You should refer to the score rubric.
3. The output format should look as follows: \"Feedback: {{write a feedback for criteria}} [RESULT] {{an integer number between 1 and 3}}\"
4. Please do not generate any other opening, closing, and explanations. Be sure to include [RESULT] in your output.
5. Do not score conciseness: a correct answer that covers the question should receive max score, even if it contains additional useless information.

The instruction to evaluate:
{instruction}

Response to evaluate:
{response}

Reference Answer (Score 3):
{reference_answer}

Score Rubrics:
[Is the response complete, accurate, and factual based on the reference answer?]
Score 1: The response is completely incomplete, inaccurate, and/or not factual.
Score 2: The response is somewhat complete, accurate, and/or factual.
Score 3: The response is completely complete, accurate, and/or factual.

Feedback:"""

In [47]:
# evaluation

evaluation_llm_name = "gemini-2.0-flash"
evaluation_llm = OpenAIServerModel(
    model_id=evaluation_llm_name,
    api_base="https://generativelanguage.googleapis.com/v1beta/openai/",
    api_key=os.getenv("Gemini_API_KEY2"),
    temperature=0)

results = {}
for system_type, outputs in [
    ("agentic_rag", outputs_agentic_rag),
    ("standard_rag", outputs_standard_rag),
    ("standard", outputs_standard),
]:
    print("evaluating {}".format(system_type))

    for experiment in tqdm(outputs):
        eval_prompt = EVALUATION_PROMPT.format(
            instruction=experiment["question"],
            response=experiment["generated_answer"],
            reference_answer=experiment["true_answer"],
        )
        messages = [
            {
                "role": "system",
                "content": "You are a fair evaluator language model."
            },
            {
                "role": "user",
                "content": eval_prompt
            },
        ]

        eval_result = evaluation_llm.generate(messages).content

        try:
            feedback, score = [
                item.strip() for item in eval_result.split("[RESULT]")
            ]
            experiment["eval_score_LLM_judge"] = score
            experiment["eval_feedback_LLM_judge"] = feedback
        except:
            print(f"Parsing failed - output was: {eval_result}")

        time.sleep(5)

    results[system_type] = pd.DataFrame.from_dict(outputs)
    results[system_type] = results[
        system_type].loc[~results[system_type]["generated_answer"].str.
                         contains("Error", na=False)]

evaluating agentic_rag

100%|██████████| 65/65 [06:13<00:00,  5.74s/it]

evaluating standard_rag

100%|██████████| 65/65 [06:18<00:00,  5.82s/it]

evaluating standard

100%|██████████| 65/65 [06:22<00:00,  5.88s/it]

In [52]:
DEFAULT_SCORE = 2  # Give average score whenever scoring fails


def fill_score(x):
    try:
        return int(x)
    except:
        return DEFAULT_SCORE


for system_type, outputs in [
    ("agentic_rag", outputs_agentic_rag),
    ("standard_rag", outputs_standard_rag),
    ("standard", outputs_standard),
]:

    results[system_type]["eval_score_LLM_judge_int"] = (
        results[system_type]["eval_score_LLM_judge"].fillna(
            DEFAULT_SCORE).apply(fill_score))
    results[system_type]["eval_score_LLM_judge_int"] = (
        results[system_type]["eval_score_LLM_judge_int"] - 1) / 2

    print(
        f"Average score for {system_type} : {results[system_type]['eval_score_LLM_judge_int'].mean()*100:.1f}%"
    )

Average score for agentic_rag : 90.8%
Average score for standard_rag : 85.4%
Average score for standard : 64.1%

In [53]:
results["agentic_rag"]

,question,true_answer,source_doc,generated_answer,eval_score_LLM_judge,eval_feedback_LLM_judge,eval_score_LLM_judge_int
0,What architecture is the `tokenizers-linux-x64...,x86_64-unknown-linux-musl,huggingface/tokenizers/blob/main/bindings/node...,The architecture is x86_64-unknown-linux-musl.,3,The response accurately identifies the archite...,1.0
1,What is the purpose of the BLIP-Diffusion mode...,The BLIP-Diffusion model is designed for contr...,huggingface/diffusers/blob/main/docs/source/en...,The purpose of BLIP-Diffusion is to enable zer...,3,The response accurately identifies the core fu...,1.0
2,How can a user claim authorship of a paper on ...,By clicking their name on the corresponding Pa...,huggingface/hub-docs/blob/main/docs/hub/paper-...,"If your paper is not linked to your account, y...",3,The response accurately describes the process ...,1.0
3,What is the purpose of the /healthcheck endpoi...,Ensure the app is running,huggingface/datasets-server/blob/main/services...,The /healthcheck endpoint in the Datasets serv...,3,The response accurately and completely states ...,1.0
4,What is the default context window size for Lo...,127 tokens,huggingface/transformers/blob/main/docs/source...,The default context window size for Local Atte...,3,The response provides more information than ne...,1.0
...,...,...,...,...,...,...,...
60,What is the maximum size of a model checkpoint...,10GB,huggingface/transformers/blob/main/docs/source...,"In Transformers version 4.18.0, model checkpoi...",3,The response accurately states that model chec...,1.0
61,What is the purpose of Weights and Biases (W&B...,To track their machine learning experiments at...,gradio-app/gradio/blob/main/guides/06_integrat...,Weights and Biases (W&B) allows data scientist...,3,The response accurately describes the purpose ...,1.0
62,What is the name of the open-source library cr...,Optimum,huggingface/blog/blob/main/intel.md,Optimum,3,"The response ""Optimum"" is a complete and accur...",1.0
63,What parameter is used to ensure that elements...,equal_height,gradio-app/gradio/blob/main/guides/cn/03_build...,The `equal_height` parameter should be passed ...,3,The response mentions the correct parameter `e...,1.0
64,What is the command to install the latest vers...,"pip install --upgrade-strategy eager optimum[""...",huggingface/diffusers/blob/main/docs/source/en...,pip install --upgrade-strategy eager optimum[o...,3,The response is complete and accurate. It prov...,1.0

In [54]:
results["standard_rag"]

,question,true_answer,source_doc,generated_answer,eval_score_LLM_judge,eval_feedback_LLM_judge,eval_score_LLM_judge_int
0,What architecture is the `tokenizers-linux-x64...,x86_64-unknown-linux-musl,huggingface/tokenizers/blob/main/bindings/node...,The `tokenizers-linux-x64-musl` binary is desi...,3,The response accurately identifies the archite...,1.0
1,What is the purpose of the BLIP-Diffusion mode...,The BLIP-Diffusion model is designed for contr...,huggingface/diffusers/blob/main/docs/source/en...,BLIP-Diffusion enables zero-shot subject-drive...,2,The response is somewhat accurate but lacks th...,0.5
2,How can a user claim authorship of a paper on ...,By clicking their name on the corresponding Pa...,huggingface/hub-docs/blob/main/docs/hub/paper-...,A user can claim authorship of a paper on the ...,3,"The response is complete and accurate, providi...",1.0
3,What is the purpose of the /healthcheck endpoi...,Ensure the app is running,huggingface/datasets-server/blob/main/services...,The `/healthcheck` endpoint in the Datasets se...,3,The response accurately states the purpose of ...,1.0
4,What is the default context window size for Lo...,127 tokens,huggingface/transformers/blob/main/docs/source...,The default context window size for Local Atte...,3,The response provides the correct context wind...,1.0
...,...,...,...,...,...,...,...
60,What is the maximum size of a model checkpoint...,10GB,huggingface/transformers/blob/main/docs/source...,"In Transformers version 4.18.0, model checkpoi...",3,The response accurately states that model chec...,1.0
61,What is the purpose of Weights and Biases (W&B...,To track their machine learning experiments at...,gradio-app/gradio/blob/main/guides/06_integrat...,Weights & Biases (W&B) allows data scientists ...,3,The response accurately describes the purpose ...,1.0
62,What is the name of the open-source library cr...,Optimum,huggingface/blog/blob/main/intel.md,The open-source library created by Hugging Fac...,1,The response is inaccurate because it mentions...,0.0
63,What parameter is used to ensure that elements...,equal_height,gradio-app/gradio/blob/main/guides/cn/03_build...,The `equal_height` parameter should be passed ...,2,The response mentions the `equal_height` param...,0.5
64,What is the command to install the latest vers...,"pip install --upgrade-strategy eager optimum[""...",huggingface/diffusers/blob/main/docs/source/en...,```bash\npip install --upgrade-strategy eager ...,2,The response is almost complete and accurate b...,0.5

In [55]:
# save all results

# Create a dictionary of JSON strings
json_results = {}
results_dir = "results"

for system_type, df in results.items():
    json_results[system_type] = json.loads(df.to_json(orient='records'))

save_json_path = os.path.join(results_dir, model_name + "_vect400_t0.2.json")

# Save to a file
with open(save_json_path, 'w') as f:
    json.dump(json_results, f, indent=4)

In [ ]:
# load results
import json
import pandas as pd

# Read the JSON file
with open('.//results//gemini-2.5-flash-preview-04-17.json', 'r') as f:
    loaded_json = json.load(f)

# Convert back to a dictionary of DataFrames
loaded_results = {}
for system_type, records in loaded_json.items():
    loaded_results[system_type] = pd.DataFrame.from_records(records)

results = loaded_results